// node --test packages/mcp/test/*.test.mjs   (needs the bundles: node packages/mcp/scripts/dev-build.mjs or the forge build)
import { test, describe, before, after } from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'
import os from 'node:os'
import { createRequire } from 'node:module'
import { Client } from '@modelcontextprotocol/sdk/client/index.js'
import { StdioClientTransport } from '@modelcontextprotocol/sdk/client/stdio.js'

const dist = path.join(path.dirname(fileURLToPath(import.meta.url)), '..', 'dist')
// tool results: structuredContent (the text block is a compact copy, or a summary for search_icons)
const parse = r => r.structuredContent || JSON.parse(r.content[0].text)
// PNG / animated exports need @resvg/resvg-js (optional dependency)
let hasRenderer = true
try { createRequire(path.join(dist, 'stdio.mjs')).resolve('@resvg/resvg-js') } catch {
  try { createRequire(path.join(dist, '..', '..', '..', 'package.json')).resolve('@resvg/resvg-js') } catch { hasRenderer = false }
}
const R = { skip: !hasRenderer && 'no @resvg/resvg-js' }

describe('stdio server (SDK client)', () => {
  let client
  before(async () => {
    client = new Client({ name: 'withicons-test', version: '1.0.0' })
    await client.connect(new StdioClientTransport({ command: process.execPath, args: [path.join(dist, 'stdio.mjs')], stderr: 'ignore' }))
  })
  after(async () => { await client.close() })

  test('lists the nine tools', async () => {
    const { tools } = await client.listTools()
    assert.deepEqual(tools.map(t => t.name).sort(), ['animate_icon', 'export_icon', 'get_icon', 'list_categories', 'list_palettes', 'list_styles', 'recommend_styles', 'resolve_icon', 'search_icons'])
    const x = tools.find(t => t.name === 'export_icon')
    for (const k of ['name', 'format', 'motion', 'background', 'out_dir', 'to', 'fps']) assert.ok(x.inputSchema.properties[k], k)
    assert.match(x.description, /gif/)
    assert.match(x.description, /pptx-animated/)
    const g = tools.find(t => t.name === 'get_icon')
    assert.ok(g.inputSchema.properties.palette && g.inputSchema.properties.colors)
    const s = tools.find(t => t.name === 'search_icons')
    assert.ok(s.inputSchema.properties.query)
    assert.ok(s.annotations.readOnlyHint)
  })
  test('search_icons "trash can" -> trash with reason and snippet', async () => {
    const raw = await client.callTool({ name: 'search_icons', arguments: { query: 'trash can', limit: 5 } })
    // the text block is a short summary, not a second copy of the JSON
    assert.equal(raw.content.length, 1)
    assert.match(raw.content[0].text, /^\d+ icons? for "trash can"/)
    assert.match(raw.content[0].text, /\n1\. trash \(/)
    assert.ok(raw.content[0].text.length < JSON.stringify(raw.structuredContent).length / 2, 'summary is short')
    const r = parse(raw)
    assert.equal(r.results[0].name, 'trash')
    assert.match(r.results[0].reason, /trash/)
    assert.match(r.results[0].snippet, /import \{ Trash \} from '@withicons\/react'/)
  })
  test('get_icon home react', async () => {
    const r = parse(await client.callTool({ name: 'get_icon', arguments: { name: 'home', format: 'react' } }))
    assert.equal(r.name, 'home')
    assert.match(r.code, /import \{ Home \} from '@withicons\/react'/)
    assert.match(r.code, /<Home \/>/)
  })
  test('get_icon resolves aliases, styles and sizes', async () => {
    const r = parse(await client.callTool({ name: 'get_icon', arguments: { name: 'delete', style: 'solid', format: 'svg', size: 32 } }))
    assert.equal(r.name, 'trash')
    assert.equal(r.requested, 'delete')
    assert.match(r.code, /^<svg[^>]* width="32" height="32"/)
  })
  test('get_icon every format', async () => {
    for (const format of ['svg', 'react', 'vue', 'svelte', 'angular', 'solid', 'html-class', 'web-component', 'data-uri']) {
      const r = parse(await client.callTool({ name: 'get_icon', arguments: { name: 'arrow-right', style: 'duo', format } }))
      assert.ok(r.code.length > 20, format)
    }
  })
  test('unknown icon is a tool error with suggestions', async () => {
    const r = await client.callTool({ name: 'get_icon', arguments: { name: 'setings' } })
    assert.equal(r.isError, true)
    assert.match(r.content[0].text, /settings/)
  })
  test('list_styles / list_categories / resolve_icon', async () => {
    const styles = parse(await client.callTool({ name: 'list_styles', arguments: {} })).styles
    assert.ok(styles.length >= 7)
    assert.equal(styles[0].name, 'line')
    for (const s of styles.filter(x => x.palette)) assert.ok(Object.keys(s.vars).length > 0, s.name)
    const c = parse(await client.callTool({ name: 'list_categories', arguments: {} }))
    assert.ok(c.categories.length > 10)
    const w = parse(await client.callTool({ name: 'list_categories', arguments: { category: 'weather' } }))
    assert.ok(w.icons.some(i => i.name === 'sun'))
    assert.equal(parse(await client.callTool({ name: 'resolve_icon', arguments: { name: 'house' } })).name, 'home')
  })
  test('animate_icon: loop, hover (react), swap, errors', async () => {
    const loop = parse(await client.callTool({ name: 'animate_icon', arguments: { name: 'bell' } }))
    assert.equal(loop.trigger, 'loop')
    assert.match(loop.code, /wm wm-loop/)
    assert.match(loop.code, /^<link rel="stylesheet"/)
    const hover = parse(await client.callTool({ name: 'animate_icon', arguments: { name: 'notification', trigger: 'hover', format: 'react' } }))
    assert.equal(hover.name, 'bell')
    assert.match(hover.code, /import \{ Bell \} from '@withicons\/react'/)
    assert.match(hover.code, /className="wm-trigger"/)
    const sw = parse(await client.callTool({ name: 'animate_icon', arguments: { name: 'eye', trigger: 'swap', to: 'eye-off', effect: 'flip', format: 'vue' } }))
    assert.equal(sw.to, 'eye-off')
    assert.match(sw.code, /wm-swap wm-fx-flip/)
    const pre = parse(await client.callTool({ name: 'animate_icon', arguments: { name: 'settings', preset: 'spin', duration: 3 } }))
    assert.match(pre.code, /wm-p-spin/)
    assert.match(pre.code, /--wm-dur:3s/)
    // inview and draw only run through the JS runtime, so every format wires up motion()
    for (const format of ['html', 'react', 'vue', 'svelte', 'solid', 'angular', 'js']) {
      const iv = parse(await client.callTool({ name: 'animate_icon', arguments: { name: 'rocket', trigger: 'inview', format } }))
      assert.match(iv.code, /motion\(.*'rocket', \{ trigger: 'inview' \}\)/, format)
    }
    // web component: motion attributes on <with-icon> itself + the @withicons/motion element upgrade (no wrapper span)
    const wc = parse(await client.callTool({ name: 'animate_icon', arguments: { name: 'rocket', trigger: 'inview', format: 'web-component' } }))
    assert.match(wc.code, /<with-icon name="rocket" motion="inview"><\/with-icon>/)
    assert.match(wc.code, /web@latest\/dist\/cdn\.js"><\/script>\n<script type="module" src="[^"]*motion@latest\/dist\/element\.js"/)
    assert.doesNotMatch(wc.code, /class="wm /)
    const wh = parse(await client.callTool({ name: 'animate_icon', arguments: { name: 'bell', trigger: 'hover', format: 'web-component', preset: 'shake', duration: 2 } }))
    assert.match(wh.code, /<button type="button" class="wm-trigger" aria-label="[^"]+"><with-icon name="bell" motion="hover" preset="shake" style="--wm-dur:2s"><\/with-icon><\/button>/)
    const ws = parse(await client.callTool({ name: 'animate_icon', arguments: { name: 'play', trigger: 'swap', to: 'pause', effect: 'morph', format: 'web-component' } }))
    assert.match(ws.code, /<with-icon name="play" swap-to="pause" swap-effect="morph" swap-trigger="hover"><\/with-icon>/)
    for (const r of [wc, wh, ws]) for (const u of r.code.match(/https:\/\/cdn\.jsdelivr\.net\/npm\/@withicons\/[^"']+/g)) assert.match(u, /@withicons\/[\w-]+@latest\//, u)
    const draw = parse(await client.callTool({ name: 'animate_icon', arguments: { name: 'check', trigger: 'hover', preset: 'draw', format: 'vue' } }))
    assert.match(draw.code, /onMounted\(\(\) => \{ m = motion\(el\.value, 'check', \{ trigger: 'hover', preset: 'draw' \}\) \}\)/)
    const bad = await client.callTool({ name: 'animate_icon', arguments: { name: 'home', trigger: 'swap' } })
    assert.ok(bad.isError || parse(bad).to, 'swap needs a target or a suggestion')
  })
  test('get_icon: palette styles report their variables; flat svg has none', async () => {
    const styles = parse(await client.callTool({ name: 'list_styles', arguments: {} })).styles
    const pal = styles.find(s => s.palette)
    if (!pal) return
    const r = parse(await client.callTool({ name: 'get_icon', arguments: { name: 'heart', style: pal.name } }))
    assert.ok(r.palette && Object.keys(r.palette).length)
    const flat = parse(await client.callTool({ name: 'get_icon', arguments: { name: 'heart', style: pal.name, flat: true } }))
    assert.doesNotMatch(flat.code, /var\(--/)
  })
  test('every style x every format works', async () => {
    const styles = parse(await client.callTool({ name: 'list_styles', arguments: {} })).styles.map(s => s.name)
    // every style the build rendered (the core package's style list), studio styles included
    const built = JSON.parse(fs.readFileSync(path.join(dist, '..', '..', 'core', 'dist', 'styles.json'), 'utf8')).map(s => s.name)
    assert.deepEqual(styles, built)
    for (const s of ['luxe', 'bauhaus', 'skeuo', 'anime', 'gothic', 'pastel', 'coquette', 'plush']) assert.ok(styles.includes(s), s)
    for (const style of styles) for (const format of ['svg', 'react', 'vue', 'svelte', 'angular', 'solid', 'html-class', 'web-component', 'data-uri']) {
      const r = await client.callTool({ name: 'get_icon', arguments: { name: 'star', style, format } })
      assert.ok(!r.isError, `${style} ${format}`)
      assert.ok(parse(r).code.length > 20, `${style} ${format}`)
    }
  })
  test('list_palettes: every palette maps onto the style variables', async () => {
    const r = parse(await client.callTool({ name: 'list_palettes', arguments: { name: 'heart', style: 'sticker' } }))
    assert.equal(r.name, 'heart')
    assert.ok(r.total >= 8, 'palettes for heart')
    assert.ok(r.variables.length >= 3)
    assert.ok(r.multiColourStyles.includes('retro'))
    for (const p of r.palettes) {
      assert.match(p.colors.c1, /^#[0-9a-f]{6}$/i)
      assert.ok(Object.keys(p.vars).length >= 3, p.id)
      assert.match(p.css, /^\.icon-heart-[\w-]+ \{ color: #/)
    }
    const tag = r.palettes[0].tags[0]
    const tagged = parse(await client.callTool({ name: 'list_palettes', arguments: { name: 'heart', tag } }))
    assert.ok(tagged.palettes.length && tagged.palettes.every(p => p.tags.includes(tag)))
    assert.equal((await client.callTool({ name: 'list_palettes', arguments: { name: 'heart', tag: 'nope' } })).isError, true)
  })
  test('get_icon applies a palette (every colour) and custom colours', async () => {
    const plain = parse(await client.callTool({ name: 'get_icon', arguments: { name: 'heart', style: 'retro' } }))
    assert.ok(plain.colors.palettes >= 8)
    assert.ok(plain.colors.variables.every(v => v.role && v.default))
    const id = plain.colors.suggestions[0].id
    const svg = parse(await client.callTool({ name: 'get_icon', arguments: { name: 'heart', style: 'retro', palette: id } }))
    assert.equal(svg.appliedPalette.id, id)
    assert.match(svg.code, /^<svg style="color: #[0-9a-f]{6}; --with-retro-/i)
    const flat = parse(await client.callTool({ name: 'get_icon', arguments: { name: 'heart', style: 'retro', palette: id, flat: true } }))
    assert.doesNotMatch(flat.code, /var\(|currentColor/)
    for (const hex of Object.values(svg.appliedPalette.vars)) assert.ok(flat.code.includes(hex), hex)
    const react = parse(await client.callTool({ name: 'get_icon', arguments: { name: 'heart', style: 'kawaii', format: 'react', palette: id } }))
    assert.match(react.code, new RegExp(`<HeartKawaii className="icon-heart-${id}" />`))
    assert.match(react.code, /--with-kawaii-fill-1: #/)
    const vue = parse(await client.callTool({ name: 'get_icon', arguments: { name: 'heart', style: 'sticker', format: 'vue', colors: { c1: '#00ff00', ink: 'navy', '--with-sticker-edge': '000' } } }))
    assert.match(vue.code, /<HeartSticker class="icon-heart-custom" \/>/)
    assert.match(vue.code, /<style>\n\.icon-heart-custom \{ color: navy; .*--with-sticker-edge: #000/)
    const svelte = parse(await client.callTool({ name: 'get_icon', arguments: { name: 'heart', style: 'glass', format: 'svelte', palette: id } }))
    assert.match(svelte.code, /:global\(\.icon-heart-/)
    const wc = parse(await client.callTool({ name: 'get_icon', arguments: { name: 'heart', style: 'pixel', format: 'web-component', palette: id } }))
    assert.match(wc.code, /<with-icon style="color: #/)
    const uri = parse(await client.callTool({ name: 'get_icon', arguments: { name: 'heart', style: 'sticker', format: 'data-uri', palette: id } }))
    assert.doesNotMatch(decodeURIComponent(uri.code), /var\(|currentColor/)
    const inked = parse(await client.callTool({ name: 'get_icon', arguments: { name: 'heart', style: 'sticker', palette: id, color: '#123456' } }))
    assert.equal(inked.appliedPalette.color, '#123456')
    const line = parse(await client.callTool({ name: 'get_icon', arguments: { name: 'heart', style: 'line', palette: id } }))
    assert.ok(line.notes && /one colour/.test(line.notes[0]))
    assert.equal((await client.callTool({ name: 'get_icon', arguments: { name: 'heart', style: 'retro', palette: 'nope-nope' } })).isError, true)
    assert.equal((await client.callTool({ name: 'get_icon', arguments: { name: 'heart', style: 'retro', colors: { c1: 'url(x)' } } })).isError, true)
    assert.equal((await client.callTool({ name: 'get_icon', arguments: { name: 'heart', style: 'retro', colors: { body: '#fff' } } })).isError, true)
  })
  test('get_icon: palette ids only when asked (or a palette style with no format); warnings for colours that do nothing', async () => {
    const code = parse(await client.callTool({ name: 'get_icon', arguments: { name: 'heart', style: 'retro', format: 'react' } }))
    assert.ok(code.colors.palettes > 0 && !code.colors.suggestions && /list_palettes/.test(code.colors.hint))
    const asked = parse(await client.callTool({ name: 'get_icon', arguments: { name: 'heart', style: 'retro', format: 'react', include_palettes: true } }))
    assert.equal(asked.colors.suggestions.length, asked.colors.palettes)
    const svg = parse(await client.callTool({ name: 'get_icon', arguments: { name: 'heart', style: 'retro' } }))
    assert.ok(svg.colors.suggestions.length > 0)
    const ok = parse(await client.callTool({ name: 'get_icon', arguments: { name: 'heart', style: 'retro', colors: { c1: '#e11d48' } } }))
    assert.equal(ok.warnings, undefined)
    const duo = parse(await client.callTool({ name: 'get_icon', arguments: { name: 'flower', style: 'duo', colors: { shine: '#ff0000' } } }))
    assert.ok(duo.warnings && /"shine" changes nothing on flower in the duo style: it is painted with ink/.test(duo.warnings[0]), JSON.stringify(duo.warnings))
    const line = parse(await client.callTool({ name: 'get_icon', arguments: { name: 'flower', style: 'line', colors: { c1: '#ff0000' } } }))
    // a one-colour style says so once (a note), not a second time as a per-role warning
    assert.equal(line.warnings, undefined)
    assert.ok(line.notes.some(n => /draws "flower" in one colour/.test(n) && /Multi-colour styles for this icon: /.test(n)), JSON.stringify(line.notes))
    // only the ink: nothing to say
    const ink = parse(await client.callTool({ name: 'get_icon', arguments: { name: 'flower', style: 'line', colors: { ink: '#ff0000' } } }))
    assert.equal(ink.notes, undefined)
    assert.equal(ink.warnings, undefined)
    // the role list never repeats a role
    const sticker = parse(await client.callTool({ name: 'get_icon', arguments: { name: 'bell', style: 'sticker', colors: { accent: '#ff0000' } } }))
    const roles = /painted with ([^.]*)\./.exec(sticker.warnings[0])[1].split(', ')
    assert.deepEqual(roles, [...new Set(roles)], sticker.warnings[0])
  })
  test('get_icon / list_palettes: mainRole is the role that paints the icon body', async () => {
    const g = parse(await client.callTool({ name: 'get_icon', arguments: { name: 'bell', style: 'sticker' } }))
    assert.equal(g.colors.mainRole, 'c1')   // bubblegum pink body (sticker paints its main body with c1)
    const p = parse(await client.callTool({ name: 'list_palettes', arguments: { name: 'bell', style: 'sticker', limit: 1 } }))
    assert.equal(p.mainRole, 'c1')
    assert.ok(p.mainRoleShare > 0.3 && p.mainRoleShare <= 1)
    assert.match(p.mainRoleNote, /c1 paints the main body of bell in sticker/)
    assert.equal(parse(await client.callTool({ name: 'list_palettes', arguments: { name: 'home', style: 'duo', limit: 1 } })).mainRole, 'c1')
    assert.equal(parse(await client.callTool({ name: 'list_palettes', arguments: { name: 'home', style: 'line', limit: 1 } })).mainRole, 'ink')
    assert.equal(parse(await client.callTool({ name: 'list_palettes', arguments: { name: 'home', limit: 1 } })).mainRole, undefined, 'needs a style')
  })
  test('animate_icon lists the alternates and lively presets', async () => {
    const r = parse(await client.callTool({ name: 'animate_icon', arguments: { name: 'bell' } }))
    assert.match(r.intent, /clapper/)
    assert.deepEqual(r.alternates.map(a => a.preset), ['shake', 'pop'])
    assert.ok(r.lively.includes('tada'))
  })
  test('recommend_styles: festivals, avatars, 3D, uses and the fallback', async () => {
    const call = args => client.callTool({ name: 'recommend_styles', arguments: args }).then(parse)
    const diwali = await call({ for: 'Diwali sale banner', icon: 'diya' })
    assert.equal(diwali.recommendations[0].style, 'rangoli')
    assert.equal(diwali.festivals[0].category, 'indian-festivals')
    assert.match(diwali.recommendations[0].webComponent, /name="diya" variant="rangoli"/)
    assert.equal(diwali.recommendations[0].files.svgAndNodes, '@withicons/holiday')
    assert.ok(diwali.recommendations[0].stylePalettes.length >= 6)
    assert.match(diwali.recommendations[0].zip, /downloads\/with-icons-rangoli\.zip$/)
    const kids = await call({ for: 'an avatar picker for a kids app' })
    assert.equal(kids.avatars.category, 'avatars')
    assert.ok(kids.recommendations.slice(0, 3).some(r => ['plush', 'kawaii'].includes(r.style)))
    assert.ok(kids.notes.some(n => /skin tone/.test(n)))
    const ai = await call({ for: 'animated 3D icons for an AI product landing page' })
    assert.equal(ai.recommendations[0].style, 'clay')
    assert.equal(ai.recommendations[0].motion3d, true)
    assert.equal((await call({ for: 'isometric server diagram' })).recommendations[0].style, 'soft3d')
    for (const [q, st] of [['Halloween party app', 'halloween'], ['Christmas email', 'christmas'], ['Diwali sale', 'rangoli'], ['Lunar New Year promo', 'lunar']]) assert.equal((await call({ for: q })).recommendations[0].style, st, q)
    const fest = await call({ use: 'festive' })
    assert.ok(fest.festivals.length >= 5 && fest.festivals.some(f => f.styles.includes('valentine')))
    assert.deepEqual((await call({ use: 'app' })).recommendations.slice(0, 2).map(r => r.style), ['line', 'duo'])
    const none = await call({ for: 'zzz' })
    assert.equal(none.matched, false)
    assert.ok(none.allUses.length >= 7 && none.groups.length >= 6)
    const duo = (await call({ for: 'duo icons for a dashboard' })).recommendations.find(r => r.style === 'duo')
    assert.deepEqual(duo.presets.map(p => p.id), ['accent', 'gradient'])
    assert.match(duo.presets[1].where, /site and studio only/)
  })
  test('animate_icon in a 3D style: wm-3d, style option and moves (soft3d 3-5)', async () => {
    const clay = parse(await client.callTool({ name: 'animate_icon', arguments: { name: 'rocket', style: 'clay', format: 'react' } }))
    assert.match(clay.code, /className="wm wm-loop wm-3d" data-wm="rocket"/)
    assert.equal(clay.motion3d, true)
    const soft3d = parse(await client.callTool({ name: 'animate_icon', arguments: { name: 'bell', style: 'soft3d', trigger: 'inview', format: 'react' } }))
    assert.match(soft3d.code, /style: 'soft3d'/)
    assert.ok(soft3d.moves.length >= 3 && soft3d.moves.length <= 5, JSON.stringify(soft3d.moves))
    const line = parse(await client.callTool({ name: 'animate_icon', arguments: { name: 'bell' } }))
    assert.equal(line.moves, undefined)
    assert.doesNotMatch(line.code, /wm-3d/)
  })
  test('list_styles: groups and uses', async () => {
    const r = parse(await client.callTool({ name: 'list_styles', arguments: {} }))
    assert.ok(r.groups.some(g => g.title === 'Holidays' && g.styles.includes('christmas')))
    assert.ok(r.uses.some(u => u.id === 'app'))
    assert.equal(r.styles.find(s => s.name === 'rangoli').group, 'Holidays')
  })
  test('list_styles: minSize and onDark hints', async () => {
    const styles = parse(await client.callTool({ name: 'list_styles', arguments: {} })).styles
    const by = Object.fromEntries(styles.map(s => [s.name, s]))
    for (const n of ['line', 'solid', 'duo']) assert.equal(by[n].minSize, 16, n)
    for (const n of ['gloss', 'sketch', 'glass', 'kawaii', 'sticker', 'pixel', 'retro']) assert.equal(by[n].minSize, 32, n)
    for (const n of ['luxe', 'bauhaus', 'skeuo', 'anime', 'gothic', 'pastel', 'coquette', 'plush']) assert.equal(by[n].minSize, 48, n)
    for (const s of styles) assert.ok(s.onDark && s.onDark.length > 20, s.name)
    assert.match(by.retro.onDark, /on-dark/)
  })
  test('resolve_icon: synonyms resolve by meaning; unknown words carry didYouMean', async () => {
    const fav = parse(await client.callTool({ name: 'resolve_icon', arguments: { name: 'favourites' } }))
    assert.equal(fav.status, 'synonym')
    assert.ok(fav.candidates.includes('star') && fav.candidates.includes('heart'))
    assert.match(fav.note, /Use the canonical name/)
    const ord = parse(await client.callTool({ name: 'resolve_icon', arguments: { name: 'orders' } }))
    assert.equal(ord.status, 'synonym')
    assert.equal(ord.name, 'receipt')
    const typo = parse(await client.callTool({ name: 'resolve_icon', arguments: { name: 'setings' } }))
    assert.equal(typo.status, 'unknown')
    assert.equal(typo.didYouMean, 'settings')
    const { tools } = await client.listTools()
    assert.match(tools.find(t => t.name === 'resolve_icon').description, /synonym/)
    assert.match(tools.find(t => t.name === 'search_icons').description, /didYouMean/)
  })
  test('get_icon reports motion for animated icons', async () => {
    const r = parse(await client.callTool({ name: 'get_icon', arguments: { name: 'bell' } }))
    assert.ok(r.motion && r.motion.loop && r.motion.hover)
  })
  test('export_icon: vector and code come back inline as text', async () => {
    const r = await client.callTool({ name: 'export_icon', arguments: { name: 'delete', style: 'solid', format: 'svg-flat,lottie' } })
    assert.ok(!r.isError, r.content[0].text)
    const s = parse(r)
    assert.equal(s.name, 'trash')
    assert.equal(s.count, 2)
    assert.match(s.command, /^npx withicons export trash --style solid --format svg-flat,lottie/)
    assert.equal(s.page, 'https://withicons.com/icons/trash.html')
    assert.ok(r.content.some(c => c.type === 'text' && /^--- trash-solid\.svg ---\n<svg /.test(c.text)))
    assert.ok(r.content.some(c => c.type === 'text' && /"layers"/.test(c.text)))
  })
  test('export_icon: animated GIF as MCP image content', R, async () => {
    const r = await client.callTool({ name: 'export_icon', arguments: { name: 'bell', format: 'gif', size: 64, background: '#ffffff' } })
    assert.ok(!r.isError, r.content[0].text)
    const s = parse(r)
    assert.equal(s.files[0].filename, 'bell-line-ring.gif')
    assert.equal(s.files[0].inline, 'image')
    const img = r.content.find(c => c.type === 'image')
    assert.equal(img.mimeType, 'image/gif')
    const gif = Buffer.from(img.data, 'base64')
    assert.equal(gif.toString('latin1', 0, 6), 'GIF89a')
    assert.ok(gif.includes(Buffer.from('NETSCAPE2.0')), 'loops')
    assert.equal(gif.length, s.files[0].bytes)
  })
  test('export_icon: out_dir writes the files (animated PowerPoint, APNG, swap)', R, async () => {
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'withicons-mcp-'))
    try {
      const r = await client.callTool({ name: 'export_icon', arguments: { name: 'play', format: 'pptx-animated,apng', motion: 'swap', to: 'pause', effect: 'morph', size: 96, out_dir: dir } })
      assert.ok(!r.isError, r.content[0].text)
      const s = parse(r)
      assert.equal(s.outDir, dir)
      assert.deepEqual(s.files.map(f => f.filename).sort(), ['play-line-animated.pptx', 'play-line-to-pause.apng.png'])
      for (const f of s.files) { assert.ok(fs.existsSync(f.path), f.path); assert.equal(fs.statSync(f.path).size, f.bytes) }
      assert.equal(r.content.length, 1, 'no inline copies when saved to disk')
      const pptx = fs.readFileSync(s.files.find(f => f.format === 'pptx-animated').path)
      assert.ok(pptx.includes(Buffer.from('ppt/media/image1.gif')))
      assert.ok(pptx.includes(Buffer.from('GIF89a')))
    } finally { fs.rmSync(dir, { recursive: true, force: true }) }
  })
  test('export_icon: names (several icons), filename templates, palettes missing on some icons', async () => {
    const r = await client.callTool({ name: 'export_icon', arguments: { names: ['home', 'settings'], format: 'svg,svg-flat', filename: '{name}-{format}' } })
    assert.ok(!r.isError, r.content[0].text)
    const s = parse(r)
    assert.deepEqual(s.names, ['home', 'settings'])
    assert.deepEqual(s.files.map(f => f.filename).sort(), ['home-svg-flat.svg', 'home-svg.svg', 'settings-svg-flat.svg', 'settings-svg.svg'])
    assert.match(s.command, /^npx withicons export home settings --format svg,svg-flat --name "\{name\}-\{format\}" --out \.$/)
    const one = parse(await client.callTool({ name: 'export_icon', arguments: { name: 'home', format: 'svg', filename: 'logo' } }))
    assert.equal(one.files[0].filename, 'logo.svg')
    const clash = await client.callTool({ name: 'export_icon', arguments: { names: ['home', 'settings'], format: 'svg', filename: 'logo' } })
    assert.ok(clash.isError)
    assert.equal(JSON.parse(clash.content[0].text).code, 'name_clash')
    const bad = await client.callTool({ name: 'export_icon', arguments: { name: 'home', filename: '../x' } })
    assert.ok(bad.isError)
    // a palette id one icon has and the other does not: borrowed colours + a warning, or strict_palette fails
    const h = parse(await client.callTool({ name: 'list_palettes', arguments: { name: 'heart' } }))
    const other = parse(await client.callTool({ name: 'list_palettes', arguments: { name: 'home' } }))
    const id = h.palettes.map(p => p.id).find(x => !other.palettes.some(p => p.id === x))
    if (id) {
      const mixed = parse(await client.callTool({ name: 'export_icon', arguments: { names: ['heart', 'home'], style: 'retro', format: 'svg-flat', palette: id } }))
      assert.equal(mixed.count, 2)
      assert.ok(mixed.warnings.some(w => w.includes(`home has no palette "${id}"`)), JSON.stringify(mixed.warnings))
      const strict = await client.callTool({ name: 'export_icon', arguments: { names: ['heart', 'home'], style: 'retro', format: 'svg-flat', palette: id, strict_palette: true } })
      assert.ok(strict.isError)
      assert.deepEqual(JSON.parse(strict.content[0].text).missing, ['home'])
    }
  })
  test('export_icon: names as a map icon -> file name; clashes refused', async () => {
    const r = await client.callTool({ name: 'export_icon', arguments: { names: { receipt: 'orders', heart: 'favourites' }, format: 'svg-flat' } })
    assert.ok(!r.isError, r.content[0].text)
    const s = parse(r)
    assert.deepEqual(s.names, ['receipt', 'heart'])
    assert.deepEqual(s.files.map(f => f.filename), ['orders.svg', 'favourites.svg'])
    assert.match(s.command, / --name-map "receipt=orders,heart=favourites" /)
    // {name} in a template is the mapped name; aliases work as keys
    const t = parse(await client.callTool({ name: 'export_icon', arguments: { names: { receipt: 'orders', delete: 'bin' }, format: 'png,svg-flat', filename: 'icon-{name}', size: 64 } }))
    assert.deepEqual(t.files.map(f => f.filename).sort(), ['icon-bin.png', 'icon-bin.svg', 'icon-orders.png', 'icon-orders.svg'])
    const clash = await client.callTool({ name: 'export_icon', arguments: { names: { receipt: 'same', heart: 'same' }, format: 'svg' } })
    assert.ok(clash.isError)
    assert.equal(JSON.parse(clash.content[0].text).code, 'name_clash')
    const bad = await client.callTool({ name: 'export_icon', arguments: { names: { receipt: '../x' }, format: 'svg' } })
    assert.ok(bad.isError)
    assert.equal(JSON.parse(bad.content[0].text).code, 'invalid_option')
  })
  test('export_icon: one colour note per command, never per icon', async () => {
    const s = parse(await client.callTool({ name: 'export_icon', arguments: { names: ['bell', 'bell-ring', 'home', 'cloud-off'], style: 'coquette', format: 'svg-flat', colors: { accent: '#ff0000' } } }))
    assert.deepEqual(s.notes.filter(n => /accent/.test(n)), ['colors.accent applies to: bell, bell-ring (2 others don\'t use it)'])
    assert.equal(s.warnings, undefined)
    const line = parse(await client.callTool({ name: 'export_icon', arguments: { names: ['bell', 'heart', 'home'], format: 'svg-flat', color: '#ff0000' } }))
    assert.ok(!line.notes.some(n => /one colour/.test(n)), 'only the ink set: no one-colour note')
    const c1 = parse(await client.callTool({ name: 'export_icon', arguments: { names: ['bell', 'heart', 'home'], format: 'svg-flat', colors: { c1: '#ff0000' } } }))
    assert.equal(c1.notes.filter(n => /one colour/.test(n)).length, 1)
    assert.match(c1.notes.find(n => /one colour/.test(n)), /^line draws bell, heart, home in one colour/)
  })
  test('export_icon: files carry no motion hooks; inline code keeps them', async () => {
    const s = await client.callTool({ name: 'export_icon', arguments: { name: 'bell', style: 'sticker', format: 'svg,svg-flat,data-uri,html' } })
    const text = f => s.content.find(c => c.type === 'text' && c.text.startsWith(`--- ${f} ---`)).text
    for (const f of ['bell-sticker-themable.svg', 'bell-sticker.svg', 'bell-sticker-data-uri.txt']) assert.ok(!/wm-/.test(text(f)), f)
    assert.match(text('bell-sticker.html'), /class="wm-shadow"/)
  })
  test('export_icon: stroke_width on outline styles, padding up to 0.6', async () => {
    const thin = parse(await client.callTool({ name: 'export_icon', arguments: { name: 'home', format: 'svg-flat', stroke_width: 1.25, padding: 0.5 } }))
    assert.equal(thin.made, true)
    assert.match(thin.command, / --padding 0.5 --stroke-width 1.25 /)
    const r = await client.callTool({ name: 'export_icon', arguments: { name: 'home', format: 'svg-flat', stroke_width: 1.25 } })
    assert.ok(r.content.some(c => c.type === 'text' && /stroke-width="1.25"/.test(c.text)))
    assert.ok((await client.callTool({ name: 'export_icon', arguments: { name: 'home', padding: 0.7 } })).isError)
    const { tools } = await client.listTools()
    assert.equal(tools.find(t => t.name === 'export_icon').inputSchema.properties.padding.maximum, 0.6)
  })
  test('export_icon: errors are tool errors with a code', async () => {
    const r = await client.callTool({ name: 'export_icon', arguments: { name: 'bell', format: 'webm' } })
    assert.ok(r.isError)
    const e = JSON.parse(r.content[0].text)
    assert.equal(e.code, 'browser_only')
    assert.match(e.error, /gif, apng or pptx-animated/)
    const u = await client.callTool({ name: 'export_icon', arguments: { name: 'nope-nope', format: 'gif' } })
    assert.ok(u.isError)
    assert.equal(JSON.parse(u.content[0].text).code, 'unknown_icon')
  })
  test('animate_icon points at export_icon for files', async () => {
    const r = parse(await client.callTool({ name: 'animate_icon', arguments: { name: 'bell', trigger: 'hover' } }))
    assert.equal(r.files.tool, 'export_icon')
    assert.deepEqual(r.files.example, { name: 'bell', style: 'line', format: 'gif', motion: 'hover', background: '#ffffff' })
  })
  test('resource icon://solid/home.svg', async () => {
    const r = await client.readResource({ uri: 'icon://solid/home.svg' })
    assert.match(r.contents[0].text, /^<svg/)
    const t = await client.listResourceTemplates()
    assert.ok(t.resourceTemplates.some(x => x.uriTemplate === 'icon://{style}/{name}.svg'))
  })
})

describe('Lambda handler (Function URL payload v2)', () => {
  let handler
  before(async () => { ({ handler } = await import(pathToFileURL(path.join(dist, 'lambda.mjs')).href)) })
  const ev = (method, rawPath, rawQueryString = '', body, headers = {}) => ({
    version: '2.0', routeKey: '$default', rawPath, rawQueryString,
    headers: { host: 'abc.lambda-url.us-east-1.on.aws', ...headers },
    requestContext: { domainName: 'abc.lambda-url.us-east-1.on.aws', http: { method, path: rawPath, protocol: 'HTTP/1.1', sourceIp: '1.2.3.4', userAgent: 'test' } },
    body: body == null ? undefined : JSON.stringify(body), isBase64Encoded: false,
  })
  const rpc = (id, method, params) => ev('POST', '/mcp', '', { jsonrpc: '2.0', id, method, params }, { 'content-type': 'application/json', accept: 'application/json, text/event-stream' })

  test('MCP initialize + tools/list + tools/call', async () => {
    const init = await handler(rpc(1, 'initialize', { protocolVersion: '2025-06-18', capabilities: {}, clientInfo: { name: 't', version: '1' } }))
    assert.equal(init.statusCode, 200)
    assert.equal(JSON.parse(init.body).result.serverInfo.name, 'withicons')
    const list = await handler(rpc(2, 'tools/list', {}))
    const tools = JSON.parse(list.body).result.tools
    assert.equal(tools.length, 9)
    // remote: no out_dir (nothing to write to), raster / animated formats answer with the command
    assert.ok(!tools.find(t => t.name === 'export_icon').inputSchema.properties.out_dir)
    const call = await handler(rpc(3, 'tools/call', { name: 'search_icons', arguments: { query: 'throw away' } }))
    const res = JSON.parse(call.body).result.structuredContent
    assert.equal(res.results[0].name, 'trash')
    assert.match(JSON.parse(call.body).result.content[0].text, /^1\. trash /m)
  })
  test('remote export_icon: vector inline, GIF / PowerPoint as the npx command', async () => {
    const call = async (id, args) => JSON.parse((await handler(rpc(id, 'tools/call', { name: 'export_icon', arguments: args }))).body).result
    const gif = await call(10, { name: 'bell', style: 'luxe', format: 'gif,pptx-animated', background: '#0f172a' })
    assert.ok(!gif.isError)
    const g = JSON.parse(gif.content[0].text)
    assert.equal(g.made, false)
    assert.equal(g.command, 'npx withicons export bell --style luxe --format gif,pptx-animated --background "#0f172a" --out .')
    assert.equal(g.page, 'https://withicons.com/icons/bell.html')
    const svg = await call(11, { name: 'bell', format: 'svg-flat' })
    assert.ok(svg.content.some(c => c.type === 'text' && /^--- bell-line\.svg ---/.test(c.text)))
  })
  test('MCP works without an Accept header; GET /mcp is 405', async () => {
    const r = await handler(ev('POST', '/mcp', '', { jsonrpc: '2.0', id: 1, method: 'tools/list', params: {} }, { 'content-type': 'application/json' }))
    assert.equal(r.statusCode, 200)
    assert.equal((await handler(ev('GET', '/mcp'))).statusCode, 405)
  })
  test('GET /api/search', async () => {
    const r = await handler(ev('GET', '/api/search', 'q=trash%20can&limit=3'))
    assert.equal(r.statusCode, 200)
    const b = JSON.parse(r.body)
    assert.equal(b.results[0].name, 'trash')
    assert.equal(b.results.length, 3)
    assert.equal(r.headers['access-control-allow-origin'], '*')
  })
  test('GET /api/recommend', async () => {
    const r = await handler(ev('GET', '/api/recommend', 'for=christmas%20email&limit=2'))
    assert.equal(r.statusCode, 200)
    assert.equal(JSON.parse(r.body).recommendations[0].style, 'christmas')
    assert.equal((await handler(ev('GET', '/api/recommend', 'use=nope'))).statusCode, 400)
  })
  test('GET /api/icon/<name>', async () => {
    const r = JSON.parse((await handler(ev('GET', '/api/icon/home', 'style=solid&format=react'))).body)
    assert.match(r.code, /from '@withicons\/react\/solid'/)
    const svg = await handler(ev('GET', '/api/icon/home.svg', 'style=line'))
    assert.equal(svg.headers['content-type'], 'image/svg+xml')
    assert.match(svg.body, /^<svg/)
    assert.equal((await handler(ev('GET', '/api/icon/nope-nope'))).statusCode, 404)
  })
  test('GET /api/motion[/<name>]', async () => {
    const list = JSON.parse((await handler(ev('GET', '/api/motion'))).body)
    assert.ok(list.presets.includes('spin'))
    assert.deepEqual(list.triggers, ['loop', 'hover', 'once', 'inview', 'swap'])
    const r = JSON.parse((await handler(ev('GET', '/api/motion/bell', 'trigger=hover&format=html'))).body)
    assert.match(r.code, /wm-hover/)
    const raw = await handler(ev('GET', '/api/motion/bell', 'raw=1'))
    assert.equal(raw.headers['content-type'], 'text/plain; charset=utf-8')
    assert.equal((await handler(ev('GET', '/api/motion/bell', 'trigger=wobble'))).statusCode, 400)
    assert.equal((await handler(ev('GET', '/api/motion/nope-nope'))).statusCode, 404)
  })
  test('GET /api/palettes/<name> and /api/icon/<name>?palette=', async () => {
    const r = await handler(ev('GET', '/api/palettes/heart', 'style=kawaii&limit=3'))
    assert.equal(r.statusCode, 200)
    const b = JSON.parse(r.body)
    assert.equal(b.palettes.length, 3)
    assert.ok(Object.keys(b.palettes[0].vars).length)
    const id = b.palettes[0].id
    const svg = await handler(ev('GET', '/api/icon/heart.svg', `style=kawaii&palette=${id}`))
    assert.equal(svg.headers['content-type'], 'image/svg+xml')
    assert.doesNotMatch(svg.body, /var\(|currentColor/)
    assert.ok(svg.body.includes(b.palettes[0].vars['--with-kawaii-fill-1']))
    const custom = await handler(ev('GET', '/api/icon/heart.svg', 'style=retro&c1=00ff00'))
    assert.match(custom.body, /#00ff00/)
    assert.equal((await handler(ev('GET', '/api/icon/heart', 'style=retro&palette=nope'))).statusCode, 400)
    assert.equal((await handler(ev('GET', '/api/palettes/nope-nope'))).statusCode, 404)
    assert.equal((await handler(ev('GET', '/api/icon/%E0%A4%A'))).statusCode, 400)
  })
  test('no route ever answers 403', async () => {
    const paths = [['GET', '/'], ['GET', '/api'], ['GET', '/api/search'], ['GET', '/api/icon/x'], ['DELETE', '/mcp'], ['PUT', '/api/search'], ['GET', '/api/palettes/heart', 'tag=bogus'], ['GET', '/mcp'], ['POST', '/mcp']]
    for (const [m, p, q] of paths) assert.notEqual((await handler(ev(m, p, q || ''))).statusCode, 403, `${m} ${p}`)
    const bad = await handler({ ...ev('POST', '/mcp', '', null, { 'content-type': 'application/json' }), body: 'not json' })
    assert.ok(bad.statusCode >= 400 && bad.statusCode !== 403, String(bad.statusCode))
  })
  test('OPTIONS preflight, health, 404', async () => {
    assert.equal((await handler(ev('OPTIONS', '/mcp'))).statusCode, 204)
    assert.ok(JSON.parse((await handler(ev('GET', '/'))).body).icons >= 300)
    assert.equal((await handler(ev('GET', '/wat'))).statusCode, 404)
  })
})
