// @withicons/classes: the files a page links must exist, match each other and stay small.
// dist/ is generated by forge/lib/emit-classes.mjs (node forge/build.mjs classes --no-site).
import { test } from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import vm from 'node:vm'
import { fileURLToPath, pathToFileURL } from 'node:url'

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..')
const dist = path.join(root, 'dist')
const has = f => fs.existsSync(path.join(dist, f))
const size = f => fs.statSync(path.join(dist, f)).size
const read = f => fs.readFileSync(path.join(dist, f), 'utf8')
const skip = !has('with-loader.js') && 'dist/ not built (node forge/build.mjs classes --no-site)'
const meta = skip ? null : (await import(pathToFileURL(path.join(dist, 'data/meta.js')).href)).default
const styles = skip ? [] : JSON.parse(/var STYLE_NAMES = (\[[^\]]*\])/.exec(read('with-loader.js'))[1])

test('every style file, every per-icon file, base, all, loader, runtime', { skip }, () => {
  assert.ok(styles.length >= 20 && styles[0] === 'line')
  for (const f of ['with-base.css', 'with-all.css', 'with-loader.js', 'with-icons.js', 'with-icons.d.ts', 'demo.html']) assert.ok(has(f), f)
  for (const s of styles) {
    assert.ok(has(`with-${s}.css`), `with-${s}.css`)
    for (const n of meta.names) assert.ok(has(`${s}/${n}.css`), `${s}/${n}.css`)
  }
  for (let i = 0; i < 16; i++) assert.ok(has(`data/alias/${i}.js`), `data/alias/${i}.js`)
  // with-all.css only @imports the style files (one 30 MB file would exceed what a CDN serves)
  const all = read('with-all.css')
  for (const s of styles) assert.ok(all.includes(`@import url("with-${s}.css")`))
  assert.ok(size('with-all.css') < 4096)
  assert.ok(size('with-loader.js') < 24 * 1024, 'with-loader.js stays a few KB: ' + size('with-loader.js'))
})

test('a per-icon file holds exactly the rule of its style file', { skip }, () => {
  for (const s of ['line', 'solid', 'kawaii', 'gothic'].filter(x => styles.includes(x))) {
    const sheet = read(`with-${s}.css`)
    for (const n of ['home', 'heart', 'bell']) {
      const rule = read(`${s}/${n}.css`).trim()
      assert.ok(rule.length > 40 && sheet.includes(rule), `${s}/${n}.css is the rule in with-${s}.css`)
    }
  }
  // the base rules are the head of every style file
  const base = read('with-base.css').split('\n').slice(1).join('\n').trim()
  assert.ok(read('with-line.css').includes(base))
})

test('no file a CDN would refuse (jsDelivr: 20 MB per file, 150 MB per package)', { skip }, () => {
  const walk = d => fs.readdirSync(d, { withFileTypes: true }).flatMap(e => e.isDirectory() ? walk(path.join(d, e.name)) : [path.join(d, e.name)])
  const files = walk(dist)
  assert.deepEqual(files.filter(f => fs.statSync(f).size > 20 * 1024 * 1024), [])
  const total = files.reduce((a, f) => a + fs.statSync(f).size, 0)
  assert.ok(total < 120 * 1024 * 1024, `dist is ${(total / 1048576).toFixed(1)} MB`)
})

test('package.json: short subpaths, CSS side effects, the bare CDN URL is the loader', { skip }, () => {
  const pkg = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'))
  assert.equal(pkg.name, '@withicons/classes')
  assert.equal(pkg.exports['./*'], './dist/*')
  assert.ok(pkg.sideEffects.includes('*.css'))
  assert.equal(pkg.jsdelivr, './dist/with-loader.js')
  assert.ok(fs.readFileSync(path.join(root, 'README.md'), 'utf8').includes('@withicons/classes@latest/dist/with-loader.js'))
})

// the loader in a minimal fake DOM: it must link the base rules once and exactly one file per icon and style shown
test('with-loader.js links only the icons on the page', { skip }, async () => {
  const links = [], styleTags = []
  const el = cls => { const list = cls.split(' '); list.contains = c => list.includes(c); return { nodeType: 1, classList: list, closest: () => null } }
  const page = [el('with with-home'), el('with with-heart with-solid'), el('with with-search with-duo with-2x with-spin'),
    el('with with-home'), el('not-an-icon'), el('with with-bell with-kawaii with-fw')]
  const document = {
    readyState: 'complete', baseURI: 'https://example.com/',
    currentScript: { src: 'https://cdn.jsdelivr.net/npm/@withicons/classes@1.0.0/dist/with-loader.js', getAttribute: () => null },
    getElementById: () => null,
    createElement: tag => ({ tag, attrs: {}, setAttribute(k, v) { this.attrs[k] = v } }),
    querySelectorAll: () => page.filter(e => e.classList.contains('with')),
    head: { appendChild: l => links.push(l), insertBefore: s => styleTags.push(s), firstChild: null },
  }
  document.documentElement = document.head
  const window = {}
  vm.runInNewContext(read('with-loader.js'), { window, document, console, Promise, URL, setTimeout })
  await new Promise(r => setTimeout(r, 10))
  assert.equal(styleTags.length, 1, 'base rules injected once')
  assert.ok(styleTags[0].textContent.includes('.with{'))
  const base = 'https://cdn.jsdelivr.net/npm/@withicons/classes@1.0.0/dist/'
  assert.deepEqual(links.map(l => l.href).sort(), ['kawaii/bell.css', 'line/home.css', 'duo/search.css', 'solid/heart.css'].map(f => base + f).sort())
  for (const l of links) assert.ok(has(l.href.slice(base.length)), l.href)
  assert.ok(window.WithIconsLoader && typeof window.WithIconsLoader.scan === 'function')
})
