// Shared test setup: make sure dist/ exists (it is generated by forge/lib/emit-motion.mjs, gitignored).
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

export const here = path.dirname(fileURLToPath(import.meta.url))
export const pkgDir = path.join(here, '..')
export const dist = path.join(pkgDir, 'dist')
export const repo = path.join(pkgDir, '..', '..')
export const emitter = path.join(repo, 'forge', 'lib', 'emit-motion.mjs')
export const inRepo = fs.existsSync(emitter)

if (!fs.existsSync(path.join(dist, 'index.js')) || !fs.existsSync(path.join(dist, 'motion.css'))) {
  if (!inRepo) throw new Error('dist/ missing and the generator is not available')
  const m = await import(pathToFileURL(emitter).href)
  await m.default()
}
export const read = f => fs.readFileSync(path.join(dist, f), 'utf8')
export const load = f => import(pathToFileURL(path.join(dist, f)).href)
