// Real queries a non-technical user (or an AI agent) would type, with the icon that must come back.
// [query, expected icon (or list of acceptable icons), top N it must appear in]
export const CASES = [
  // exact names and as-you-type prefixes
  ['home', 'home', 1],
  ['settings', 'settings', 1],
  ['search', 'search', 1],
  ['calendar', 'calendar', 1],
  ['hom', 'home', 1],
  ['sett', 'settings', 1],
  ['calen', 'calendar', 1],
  ['shopping', ['shopping-cart', 'shopping-bag', 'shopping-basket'], 1], // 2026-10: shopping-basket joined the set
  ['magnif', 'search', 3],
  ['thermo', 'thermometer', 1],

  // case, separators, camel/snake/kebab
  ['ArrowRight', 'arrow-right', 1],
  ['arrow_right', 'arrow-right', 1],
  ['ARROW RIGHT', 'arrow-right', 1],
  ['shoppingCart', 'shopping-cart', 1],
  ['credit-card', 'credit-card', 1],
  ['Café', 'coffee', 3],

  // plurals, -ing, -ed, -er
  ['folders', 'folder', 1],
  ['users', 'users', 1],
  ['deleting', 'trash', 1],
  ['deleted', 'trash', 3],
  ['locked', 'lock', 1],
  ['printing', 'printer', 1],
  ['downloading', 'download', 1],
  ['uploaded', 'upload', 1],
  ['messages', ['messages', 'message-square', 'message-circle'], 1],
  ['charts', ['chart-bar', 'chart-line', 'chart-pie', 'chart-area', 'chart-scatter', 'chart-candlestick', 'chart-column-stacked', 'chart-funnel'], 1],
  ['batteries', 'battery', 1],
  ['bookmarks', ['bookmark', 'bookmark-plus'], 1], // 2026-10: bookmark-plus joined the set

  // typos
  ['settigns', 'settings', 1],
  ['calender', 'calendar', 1],
  ['hosue', 'home', 1],
  ['serch', 'search', 1],
  ['notificaton', 'bell', 3],
  ['umbrela', 'umbrella', 1],
  ['keybord', 'keyboard', 1],
  ['pasword', ['lock', 'key'], 3],
  ['camra', 'camera', 1],
  ['calculater', 'calculator', 1],
  ['trophey', 'trophy', 1],
  ['microphne', 'microphone', 1],
  ['scisors', 'scissors', 1],
  ['thermometre', 'thermometer', 1],
  ['bluetoth', 'bluetooth', 1],
  ['fingreprint', 'fingerprint', 1],
  ['hourglas', 'hourglass', 1],
  ['lightbulp', 'lightbulb', 1],
  ['dashbord', 'layout-dashboard', 1],

  // synonyms and aliases
  ['delete', 'trash', 1],
  ['bin', 'trash', 1],
  ['garbage', 'trash', 1],
  ['house', 'home', 1],
  ['gear', 'settings', 1],
  ['cog', 'settings', 1],
  ['magnifying glass', 'search', 1],
  ['envelope', 'mail', 1],
  ['email', 'mail', 1],
  ['avatar', ['user', 'user-circle'], 2],
  ['person', 'user', 2],
  ['team', 'users', 1],
  ['padlock', 'lock', 1],
  ['tick', 'check', 1],
  ['checkmark', 'check', 1],
  ['cross', ['close', 'x-circle'], 2],
  ['hamburger menu', 'menu', 1],
  ['three dots', ['more-horizontal', 'more-vertical'], 2],
  ['kebab menu', 'more-vertical', 1],
  ['speech bubble', ['message-circle', 'message-square'], 2],
  ['funnel', 'filter', 1],
  ['cloud upload', 'cloud-upload', 1],
  ['idea', 'lightbulb', 1],
  ['cash', ['banknote', 'dollar-sign', 'wallet'], 2],
  ['robot', 'bot', 1],
  ['loading spinner', 'loader', 1],
  ['paper plane', 'send', 1],
  ['floppy disk', 'save', 1],
  ['pin location', 'map-pin', 1],
  ['bar graph', 'chart-bar', 1],
  ['pie chart', 'chart-pie', 1],
  ['lightning bolt', 'zap', 2],
  ['speaker', ['speaker', 'volume'], 1], // 2026-10: a real speaker icon now exists
  ['mute', 'volume-off', 2],
  ['visible', 'eye', 1],
  ['hidden password', 'eye-off', 2],
  ['thumbs up', 'thumbs-up', 1],
  ['qr', 'qr-code', 1],
  ['wifi', 'wifi', 1],
  ['no internet', 'wifi-off', 2],

  // phrases
  ['trash can', 'trash', 1],
  ['recycle bin', 'trash', 1],
  ['throw away', 'trash', 1],
  ['shopping cart', 'shopping-cart', 1],
  ['credit card', 'credit-card', 1],
  ['log out', 'log-out', 1],
  ['sign in', 'log-in', 1],
  ['add user', 'user-plus', 1],
  ['remove user', ['user-minus', 'user-x'], 2],
  ['new folder', 'folder-plus', 1],
  ['open folder', 'folder-open', 1],
  ['open book', 'book-open', 1],
  ['zoom in', 'zoom-in', 1],
  ['alarm clock', 'alarm-clock', 1],
  ['video call', 'video-call', 1],
  ['phone call', 'phone-call', 1],
  ['arrow pointing up', 'arrow-up', 1],
  ['up arrow', 'arrow-up', 1],
  ['dark mode', 'moon', 1],
  ['light mode', 'sun', 2],
  ['git branch', 'git-branch', 1],
  ['pull request', 'git-pull-request', 1],

  // natural language
  ['money', ['dollar-sign', 'banknote', 'coins', 'wallet'], 1],
  ['profile', 'user', 1],
  ['my account', 'user', 2],
  ['preferences', ['settings', 'sliders'], 2],
  ['buy', ['shopping-cart', 'shopping-bag'], 2],
  ['checkout', ['shopping-cart', 'credit-card'], 2],
  ['pay', ['credit-card', 'wallet', 'dollar-sign'], 3],
  ['write', ['pencil', 'edit'], 2],
  ['chat', ['message-circle', 'message-square', 'messages'], 2],
  ['photo', ['image', 'camera'], 2],
  ['movie', ['film', 'video-camera'], 2],
  ['song', 'music-note', 1],
  ['schedule meeting', ['calendar', 'calendar-plus', 'calendar-days', 'calendar-check'], 3],
  ['warning', 'alert-triangle', 1],
  ['error', ['alert-circle', 'alert-triangle', 'x-circle'], 2],
  ['help', 'help-circle', 1],
  ['secure', ['lock', 'shield', 'shield-check'], 2],
  ['notification', 'bell', 1],
  ['reminder', ['bell', 'alarm-clock'], 2],
  ['close window', 'close', 2],
  ['add new item', ['plus', 'plus-circle'], 2],
  ['done', 'check', 2],
  ['reload page', 'refresh', 1],
  ['go back', ['arrow-left', 'undo', 'chevron-left'], 2],
  ['statistics', ['chart-bar', 'chart-line', 'chart-pie', 'activity'], 2],
  ['school', ['school', 'graduation-cap'], 1], // 2026-10: a school icon joined the set
  ['programming', ['code', 'terminal'], 2],
  ['travel', ['luggage', 'passport', 'plane', 'globe', 'map'], 2], // 2026-10: luggage and passport joined the set
  ['internet', 'globe', 2],
  ['doctor', ['stethoscope', 'heart-pulse', 'pill'], 2], // 2026-10: stethoscope joined the set
  ['birthday', ['cake', 'gift'], 1], // 2026-10: cake joined the set
  ['winner', 'trophy', 2],
  ['delivery', 'truck', 1],
  ['weather', ['cloud-sun', 'cloud', 'sun'], 3],
  ['night', 'moon', 1],
  ['ai assistant', ['bot', 'sparkles'], 2],
  ['an icon for deleting things', 'trash', 1],
  ['i need a picture of a house', 'home', 1],
  ['something to show money', ['dollar-sign', 'banknote', 'coins', 'wallet'], 2],
  ['coffee cup', 'coffee', 1],
  ['red heart', 'heart', 1],
  ['solid home icon', 'home', 1],
  ['home button', 'home', 1],
  ['play button', 'play', 1],
]

// Harder set: typos that are NOT in the vocabulary (forces real fuzzy matching), unusual phrasing, multi-word intent.
export const HARD = [
  ['settinsg', 'settings', 1],
  ['calnedar', 'calendar', 1],
  ['shopign cart', 'shopping-cart', 1],
  ['downlaod', 'download', 1],
  ['uplaod file', ['upload', 'cloud-upload'], 2],
  ['notifcations', 'bell', 2],
  ['envelop', 'mail', 1],
  ['scissor', 'scissors', 1],
  ['printr', 'printer', 1],
  ['clipbaord', 'clipboard', 1],
  ['databse', 'database', 1],
  ['termnial', 'terminal', 1],
  ['languge', 'language', 1],
  ['passwrd', ['lock', 'key'], 3],
  ['favourite', ['star', 'heart'], 2],
  ['favorites', ['star', 'heart', 'bookmark'], 2],
  ['colour picker', 'palette', 2],
  ['take a photo', 'camera', 1],
  ['send a message', ['send', 'message-circle', 'message-square'], 2],
  ['write a note', ['sticky-note', 'pencil', 'edit'], 3],
  ['turn off', 'power', 2],
  ['switch on', ['toggle', 'power'], 2],
  ['volume up', 'volume', 1],
  ['go to next song', 'skip-forward', 2],
  ['previous track', 'skip-back', 1],
  ['speed up', 'fast-forward', 3],
  ['full screen', 'maximize', 1],
  ['exit full screen', 'minimize', 2],
  ['drag and drop', ['drag-handle', 'move'], 2],
  ['copy to clipboard', ['copy', 'clipboard'], 2],
  ['open in new tab', 'external-link', 1],
  ['attach file', 'paperclip', 1],
  ['user settings', ['user', 'settings', 'user-circle', 'user-cog'], 3],
  ['bank', ['landmark', 'piggy-bank'], 1], // 2026-10: piggy-bank joined the set
  ['receipt', 'receipt', 1],
  ['invoice', 'receipt', 1],
  ['rainy day', 'cloud-rain', 1],
  ['snowing', 'cloud-snow', 2],
  ['thunderstorm', 'cloud-lightning', 1],
  ['windy', 'wind', 1],
  ['temperature', 'thermometer', 1],
  ['eco friendly', 'leaf', 1],
  ['startup launch', 'rocket', 1],
  ['tea', 'coffee', 2],
  ['package delivery', ['package', 'truck'], 2],
  ['to do list', 'list-checks', 2],
  ['numbered list', 'list-ordered', 1],
  ['bullet list', 'list', 1],
  ['text bold', 'bold', 1],
  ['heart rate', 'heart-pulse', 1],
  ['medicine', 'pill', 1],
  ['crown king', 'crown', 1],
  ['smiley face', 'smile', 1],
  ['magic wand', 'wand', 1],
  ['gamepad controller', 'gamepad', 1],
  ['headphones music', 'headphones', 1],
  ['customer support', ['headset', 'help-circle'], 2],
  ['fingerprint scan', 'fingerprint', 1],
  ['id badge', ['id-card', 'badge-check'], 2],
  ['verified', 'badge-check', 2],
]

// Misspellings far from the vocabulary: dropped/doubled letters, keyboard slips, phonetic spellings,
// missing or extra spaces. Served by the similarity layer (n-gram, phonetic, keyboard-weighted edits).
export const MISSPELL = [
  // dropped / swapped / wrong vowels
  ['calandar', 'calendar', 1],
  ['calander', 'calendar', 1],
  ['seting', 'settings', 1],
  ['setings', 'settings', 1],
  ['setttings', 'settings', 1],
  ['tresh', 'trash', 3],
  ['trsh', 'trash', 3],
  ['delte', 'trash', 3],
  ['hart', 'heart', 3],
  ['hous', 'home', 3],
  ['magnifing glass', 'search', 3],
  ['notifcation', 'bell', 3],
  ['shoping cart', 'shopping-cart', 1],
  ['dowload', 'download', 1],
  ['dwnload', 'download', 1],
  ['uplod', 'upload', 3],
  ['favourit', ['star', 'heart', 'bookmark'], 3],
  ['comment buble', ['message-circle', 'message-square', 'messages'], 3],
  ['lighbulb', 'lightbulb', 1],
  ['envolope', 'mail', 3],
  ['pictre', ['image', 'file-image', 'camera'], 3],
  ['wifii', 'wifi', 1],
  ['thermometr', 'thermometer', 1],
  ['grafh', ['chart-bar', 'chart-line', 'chart-area', 'chart-pie'], 3],
  ['cofee', 'coffee', 1],
  ['rocet', 'rocket', 1],
  ['trofy', 'trophy', 1],
  ['bokmark', 'bookmark', 1],
  ['walet', 'wallet', 1],
  ['sheild', 'shield', 1],
  ['shild', 'shield', 3],
  ['hamer', 'hammer', 1],
  ['pallete', 'palette', 1],
  ['pensil', 'pencil', 1],
  ['erazer', 'eraser', 1],
  ['triangel', 'triangle', 1],
  ['hexagone', 'hexagon', 1],
  ['shuffel', 'shuffle', 1],
  ['volumn', 'volume', 1],
  ['compas', 'compass', 1],
  ['recipt', ['receipt', 'receipt-text'], 1],
  ['reciept', 'receipt', 1],
  ['tempreture', 'thermometer', 3],
  ['brifcase', 'briefcase', 1],
  ['dolar', 'dollar-sign', 1],
  ['microfone', 'microphone', 1],
  ['headfones', 'headphones', 1],
  ['smartfone', 'smartphone', 1],
  ['puzzel', 'puzzle-piece', 1],
  ['anker', 'anchor', 3],
  ['wrentch', 'wrench', 1],
  ['fingerprnt', 'fingerprint', 1],
  ['clipbord', ['clipboard', 'clipboard-list'], 1], // 2026-10: clipboard-list joined the set
  ['databaze', 'database', 1],
  ['languaje', 'language', 1],
  ['gaje', 'gauge', 3],
  // keyboard-adjacent slips
  ['sesrch', 'search', 1],
  ['homr', 'home', 1],
  ['seyyings', 'settings', 1],
  ['downlosd', 'download', 1],
  ['cslendar', 'calendar', 1],
  ['ksy', 'key', 3],
  // phonetic spellings
  ['fone', 'phone', 3],
  ['nite', 'moon', 3],
  ['kalender', 'calendar', 1],
  ['skedule', ['calendar', 'calendar-days', 'alarm-clock', 'clock'], 3],
  ['foto', ['image', 'camera'], 3],
  ['kamera', 'camera', 1],
  ['sizzors', 'scissors', 3],
  ['rench', 'wrench', 3],
  ['brane', 'brain', 3],
  ['sirkle', 'circle', 3],
  ['skware', 'square', 3],
  ['kloud', 'cloud', 1],
  ['trofee', 'trophy', 3],
  ['lok', 'lock', 3],
  // heavy damage to long words (character n-gram similarity)
  ['hrgglass', 'hourglass', 1],
  ['pperclp', 'paperclip', 1],
  ['mimize', 'minimize', 1],
  ['barcoea', 'barcode', 1],
  ['micopne', 'microphone', 1],
  ['fogerprit', 'fingerprint', 1],
  ['heaadphooos', 'headphones', 1],
  ['scsoors', 'scissors', 1],
  ['notifcashun', 'bell', 3],
  ['graduashun', 'graduation-cap', 1],
  // missing or extra spaces / hyphens
  ['creditcard', 'credit-card', 1],
  ['shopingcart', 'shopping-cart', 1],
  ['alarmclok', 'alarm-clock', 1],
  ['thumbsupp', 'thumbs-up', 1],
  ['key board', 'keyboard', 1],
  ['data base', 'database', 1],
  ['head phones', 'headphones', 1],
  ['hour glass', 'hourglass', 1],
  ['snow flake', 'snowflake', 1],
  ['finger print', 'fingerprint', 1],
  ['paper clip', 'paperclip', 1],
  ['light bulb', 'lightbulb', 1],
  ['bar code', 'barcode', 1],
  ['credit crad', 'credit-card', 1],
  ['thumbs-upp', 'thumbs-up', 1],
  ['lightbulbidea', 'lightbulb', 3],
  ['redheart', 'heart', 1],
  ['shoppng bagg', 'shopping-bag', 1],
  ['trashcan', 'trash', 1],
]
