// Facts about the most-searched open-source icon libraries (same rules as libraries.mjs: official sources only,
// checked on CHECKED, hedged numbers, names verified against each library's published icon data).

export const OPEN_LIBS = [
  /* ───────────────────────── Font Awesome ───────────────────────── */
  {
    slug: 'font-awesome', name: 'Font Awesome', kind: 'open', color: 'line', mark: 'Fa', url: 'https://fontawesome.com', searchQ: 'magnifying glass',
    known: 'the web’s most widely used icon toolkit: easy <code>&lt;i&gt;</code> tag classes, brand logos, a free set of over 2,000 icons and a huge Pro catalogue with many families and styles.',
    hub: { license: 'CC BY 4.0 icons (Free)', price: 'Free; Pro paid', count: 'over 2,000 free', styles: '3 free (solid, regular, brands); many in Pro', classes: 'Yes (fa-*)', ai: 'Agent skills, docs llms.txt' },
    facts: {
      license: ['Font Awesome Free: icons CC BY 4.0, fonts SIL OFL 1.1, code MIT. Pro is a commercial licence', [1]],
      price: ['Free plan; paid Pro plans billed yearly or monthly (see the plans page for current prices)', [2]],
      count: ['Over 2,000 free icons (2,163 in the official API for version 7.3.1); Pro adds many more icons and styles', [3]],
      styles: ['Free: Solid, Regular (a subset) and Brands. Pro adds Light, Thin, Duotone, Sharp and more families', [3, 4]],
      frameworks: ['Official React, Vue, Angular and Svelte packages, plus SVG + JS and web fonts', [5]],
      classes: ['Yes: <code>&lt;i class="fa-solid fa-house"&gt;&lt;/i&gt;</code>', [4]],
      selfhost: ['Yes: download or npm (<code>@fortawesome/fontawesome-free</code>); Kits are optional', [5]],
      design: ['Official Figma plugin (Pro icons need a paid plan)', [6]],
      ai: ['Official AI agent tools (skills and a CLI, “early days”) and an llms.txt for the docs; no official MCP server found', [7, 8]],
      attribution: ['Technically yes (CC BY 4.0), but the licence says the comments already in the files are enough', [1]],
    },
    sources: [
      ['Font Awesome Free LICENSE.txt (GitHub)', 'https://github.com/FortAwesome/Font-Awesome/blob/7.x/LICENSE.txt'],
      ['Font Awesome plans', 'https://fontawesome.com/plans'],
      ['Font Awesome API (icon counts, styles)', 'https://api.fontawesome.com'],
      ['Docs: how to add icons', 'https://docs.fontawesome.com/web/add-icons/how-to'],
      ['npm: @fortawesome/fontawesome-free', 'https://www.npmjs.com/package/@fortawesome/fontawesome-free'],
      ['Docs: Figma plugin', 'https://docs.fontawesome.com/desktop/add-icons/figma-plugin'],
      ['Docs: AI agent tools', 'https://docs.fontawesome.com/web/use-with/ai-agent-tools'],
      ['Docs llms.txt', 'https://docs.fontawesome.com/llms.txt'],
    ],
    them: [
      'You need brand logos (GitHub, Slack, Visa…) or one of thousands of niche icons.',
      'Your team already knows the <code>fa-</code> names and you have a Pro plan you’re happy with.',
      'You want many weights and families (Light, Thin, Sharp, Duotone) and are fine paying for Pro.',
    ],
    us: [
      'You want the Font Awesome way of working (<code>&lt;i class="…"&gt;</code>) under a plain MIT licence, with nothing behind a paywall.',
      'You want expressive styles for free: Duo, Gloss, Engrave, Blueprint and Sketch next to Line and Solid.',
      'You want a smaller, tidy set (300 icons) that covers everyday interfaces, slides and docs.',
    ],
    migrate: {
      mode: 'class',
      intro: 'Same idea, different names: one stylesheet, then <code>&lt;i&gt;</code> tags. Replace <code>fa-solid fa-</code> with <code>with with-</code>, add <code>with-solid</code> where you used solid, and fix the names that differ (<code>house</code> → <code>home</code>, <code>xmark</code> → <code>close</code>). Older Font Awesome 4/5 names such as <code>fa-times</code> and <code>fa-cog</code> are understood by the converter too.',
      map: [['fa-house', 'home'], ['fa-magnifying-glass', 'search'], ['fa-trash', 'trash'], ['fa-trash-can', 'trash'], ['fa-gear', 'settings'], ['fa-user', 'user'], ['fa-envelope', 'mail'], ['fa-xmark', 'close'], ['fa-check', 'check'], ['fa-plus', 'plus'], ['fa-bars', 'menu'], ['fa-pen-to-square', 'edit'], ['fa-pen', 'pencil'], ['fa-download', 'download'], ['fa-upload', 'upload'], ['fa-heart', 'heart'], ['fa-star', 'star'], ['fa-bell', 'bell'], ['fa-calendar', 'calendar'], ['fa-calendar-days', 'calendar-days'], ['fa-lock', 'lock'], ['fa-arrow-right', 'arrow-right'], ['fa-chevron-down', 'chevron-down'], ['fa-share-nodes', 'share'], ['fa-copy', 'copy'], ['fa-arrow-up-right-from-square', 'external-link'], ['fa-eye', 'eye'], ['fa-filter', 'filter'], ['fa-circle-info', 'info-circle'], ['fa-triangle-exclamation', 'alert-triangle'], ['fa-cart-shopping', 'shopping-cart'], ['fa-image', 'image'], ['fa-phone', 'phone']],
      extra: { home: 'home', search: 'search', cog: 'settings', times: 'close', close: 'close', edit: 'edit', 'shopping-cart': 'shopping-cart', 'info-circle': 'info-circle', 'exclamation-triangle': 'alert-triangle', 'external-link': 'external-link', 'external-link-alt': 'external-link', 'trash-alt': 'trash', 'calendar-alt': 'calendar-days', navicon: 'menu', 'share-alt': 'share', 'sign-in': 'log-in', 'sign-out': 'log-out', 'sign-in-alt': 'log-in', 'sign-out-alt': 'log-out' },
      prefixes: ['fa-'],
      tokens: { fa: '', fas: 'style:solid', far: '', fal: '', fat: '', fad: 'style:duo', fab: '', 'fa-solid': 'style:solid', 'fa-regular': '', 'fa-light': '', 'fa-thin': '', 'fa-duotone': 'style:duo', 'fa-brands': '', 'fa-sharp': '', 'fa-classic': '', 'fa-xs': 'with-xs', 'fa-sm': 'with-sm', 'fa-lg': 'with-lg', 'fa-xl': 'with-lg', 'fa-2x': 'with-2x', 'fa-3x': 'with-3x', 'fa-4x': 'with-4x', 'fa-5x': 'with-5x', 'fa-fw': 'with-fw', 'fa-spin': 'with-spin', 'fa-pulse': 'with-pulse', 'fa-spin-pulse': 'with-pulse', 'fa-rotate-90': 'with-rotate-90', 'fa-rotate-180': 'with-rotate-180', 'fa-rotate-270': 'with-rotate-270', 'fa-flip-horizontal': 'with-flip-h', 'fa-flip-vertical': 'with-flip-v', 'fa-flip-both': 'with-flip-both' },
      before: ['html', '<link rel="stylesheet" href="…/fontawesome/css/all.min.css">\n\n<i class="fa-solid fa-house"></i>\n<i class="fa-regular fa-heart"></i>\n<i class="fa-solid fa-gear fa-spin"></i>\n<i class="fa-solid fa-xmark fa-2x"></i>'],
      after: ['html', '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@withicons/web/dist/classes/with-all.css">\n\n<i class="with with-home with-solid"></i>\n<i class="with with-heart"></i>\n<i class="with with-settings with-solid with-spin"></i>\n<i class="with with-close with-solid with-2x"></i>'],
      sample: '<i class="fa-solid fa-house"></i>\n<i class="fa-regular fa-heart"></i>\n<i class="fa-solid fa-gear fa-spin"></i>\n<i class="fa fa-times fa-2x"></i>\n<button><i class="fa-solid fa-cart-shopping"></i> Checkout</button>',
      styleNote: 'Font Awesome <b>Regular</b> → our <b>Line</b> (no style class); <b>Solid</b> → <b>with-solid</b>; <b>Duotone</b> → <b>with-duo</b>. Brand logos aren’t part of with icons.',
    },
    faq: [
      ['Is with icons a drop-in replacement for Font Awesome?', 'Not a drop-in: the class pattern is the same but many names differ, and with icons has 300 icons and no brand logos. For everyday interface icons the switch takes minutes with the name map and converter on this page.'],
      ['Can I use with icons and Font Awesome on the same page?', 'Yes. The class names don’t clash (<code>with-</code> vs <code>fa-</code>), so you can move over one screen at a time.'],
    ],
  },

  /* ───────────────────────── Material Symbols ───────────────────────── */
  {
    slug: 'material-symbols', name: 'Material Symbols', also: 'Material Icons', kind: 'open', color: 'blueprint', mark: 'Ms', url: 'https://fonts.google.com/icons', searchQ: 'favorite',
    known: 'Google’s Material Design icons: over 2,500 symbols in a free variable font with fill, weight, grade and optical-size axes, a natural fit for Material and Android-style interfaces.',
    hub: { license: 'Apache-2.0', price: 'Free', count: 'over 2,500', styles: '3 (outlined, rounded, sharp) + variable axes', classes: 'Ligatures (material-symbols-*)', ai: 'Google Design MCP (icons)' },
    facts: {
      license: ['Apache License 2.0', [1, 3]],
      price: ['Free', [1]],
      count: ['Over 2,500 (“a collection of over 2,500 icons”)', [1]],
      styles: ['Outlined, Rounded and Sharp, with variable Fill, Weight (100–700), Grade and Optical size axes', [1]],
      frameworks: ['A web font plus SVG and PNG downloads from Google; the popular npm packages are community-made', [1, 4]],
      classes: ['Font ligatures: <code>&lt;span class="material-symbols-outlined"&gt;home&lt;/span&gt;</code>', [1]],
      selfhost: ['Yes: font files in the official GitHub repo, or download SVG/PNG', [3]],
      design: ['Download SVG or PNG from Google Fonts', [5]],
      ai: ['Google’s Design MCP can find icons and defaults to Material Symbols', [6]],
      attribution: ['Not required (“appreciated but not required”)', [3]],
    },
    sources: [
      ['Google Fonts: Material Symbols guide', 'https://developers.google.com/fonts/docs/material_symbols'],
      ['Google Fonts: Material Icons guide (legacy)', 'https://developers.google.com/fonts/docs/material_icons'],
      ['google/material-design-icons (GitHub)', 'https://github.com/google/material-design-icons'],
      ['npm: material-symbols (community package)', 'https://www.npmjs.com/package/material-symbols'],
      ['Google Fonts icons browser', 'https://fonts.google.com/icons'],
      ['Google Design MCP overview', 'https://developers.google.com/design-mcp/overview'],
      ['Material Symbols Outlined codepoints (names)', 'https://github.com/google/material-design-icons/blob/master/variablefont/MaterialSymbolsOutlined%5BFILL,GRAD,opsz,wght%5D.codepoints'],
    ],
    them: [
      'Your app follows Material Design or Android conventions.',
      'You want one variable font where fill, weight and size are adjustable axes.',
      'You need breadth: over 2,500 symbols, with consistent Google-made coverage.',
    ],
    us: [
      'You want a look that isn’t tied to Google’s design language, including Duo, Gloss, Engrave, Blueprint and Sketch.',
      'You want official packages for React, Vue, Svelte, Angular and Solid from the same team that draws the icons.',
      'You want icons ready for slides and docs: copy as PNG or SVG in any colour, no font setup.',
    ],
    migrate: {
      mode: 'ligature',
      intro: 'Material uses a font ligature (the icon name is the text inside the tag). with icons uses a class instead. Replace each <code>&lt;span class="material-symbols-outlined"&gt;name&lt;/span&gt;</code> with <code>&lt;i class="with with-name"&gt;&lt;/i&gt;</code>. Legacy <b>Material Icons</b> (<code>material-icons</code>, no longer updated by Google) works the same way.',
      map: [['home', 'home'], ['search', 'search'], ['delete', 'trash'], ['settings', 'settings'], ['person', 'user'], ['mail', 'mail'], ['close', 'close'], ['check', 'check'], ['add', 'plus'], ['menu', 'menu'], ['edit', 'edit'], ['download', 'download'], ['upload', 'upload'], ['favorite', 'heart'], ['star', 'star'], ['notifications', 'bell'], ['calendar_month', 'calendar'], ['lock', 'lock'], ['arrow_forward', 'arrow-right'], ['keyboard_arrow_down', 'chevron-down'], ['expand_more', 'chevron-down'], ['share', 'share'], ['content_copy', 'copy'], ['open_in_new', 'external-link'], ['visibility', 'eye'], ['filter_list', 'filter'], ['info', 'info-circle'], ['warning', 'alert-triangle'], ['shopping_cart', 'shopping-cart'], ['image', 'image'], ['call', 'phone']],
      before: ['html', '<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined">\n\n<span class="material-symbols-outlined">home</span>\n<span class="material-symbols-outlined">favorite</span>\n<span class="material-symbols-outlined">delete</span>'],
      after: ['html', '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@withicons/web/dist/classes/with-line.css">\n\n<i class="with with-home"></i>\n<i class="with with-heart"></i>\n<i class="with with-trash"></i>'],
      sample: '<span class="material-symbols-outlined">home</span>\n<span class="material-symbols-outlined">favorite</span>\n<span class="material-symbols-outlined">delete</span>\n<span class="material-icons">shopping_cart</span>',
      styleNote: 'Material <b>Outlined</b> → our <b>Line</b>; <b>Fill 1</b> or legacy filled <code>material-icons</code> → <b>with-solid</b>. Rounded is closest to Line (round caps and joins).',
    },
    faq: [
      ['What’s the difference between Material Icons and Material Symbols?', 'Material Symbols is Google’s current set (since 2022) with variable-font axes; the older Material Icons set is no longer updated, according to Google’s GitHub repository. Both use the same ligature names, and both map to with icons the same way.'],
    ],
  },

  /* ───────────────────────── Heroicons ───────────────────────── */
  {
    slug: 'heroicons', name: 'Heroicons', kind: 'open', color: 'duo', mark: 'He', url: 'https://heroicons.com', searchQ: 'cog',
    known: 'hand-crafted SVG icons from the makers of Tailwind CSS: a small, polished set of 316 icons in outline, solid, mini and micro sizes.',
    hub: { license: 'MIT', price: 'Free', count: '316', styles: '4 (outline, solid, mini, micro)', classes: 'No (SVG / components)', ai: 'None official found' },
    facts: {
      license: ['MIT', [2]],
      price: ['Free', [1]],
      count: ['316 (“316 icons”)', [1]],
      styles: ['Outline (24 px, 1.5 stroke), Solid (24 px), Mini (20 px) and Micro (16 px)', [1, 2]],
      frameworks: ['React (<code>@heroicons/react</code>) and Vue (<code>@heroicons/vue</code>); plain SVG for everything else', [2]],
      classes: ['No icon font or classes; copy the SVG or use the components', [2]],
      selfhost: ['Yes: copy SVGs from the site or the repo, or use npm', [2]],
      design: ['Official Figma community file', [3]],
      ai: ['No official MCP server or llms.txt found', []],
      attribution: ['No (keep the MIT notice when redistributing the code)', [2]],
    },
    sources: [
      ['Heroicons website', 'https://heroicons.com'],
      ['Heroicons README (GitHub)', 'https://github.com/tailwindlabs/heroicons'],
      ['Heroicons Figma file', 'https://www.figma.com/community/file/1143911270904274171'],
      ['Heroicons 24/outline SVGs (names)', 'https://github.com/tailwindlabs/heroicons/tree/master/optimized/24/outline'],
    ],
    them: [
      'You build with Tailwind CSS and want icons that match Tailwind UI exactly.',
      'You want four hand-tuned sizes (24, 20 and 16 px) for very small UI.',
      'You only need React or Vue components and a small, focused set.',
    ],
    us: [
      'You want the same tidy feel plus five more looks: Duo, Gloss, Engrave, Blueprint and Sketch.',
      'You want packages for Svelte, Angular, Solid and a web component, or plain <code>&lt;i&gt;</code> classes.',
      'You want icons for slides and docs too, with copy as PNG in any colour.',
    ],
    migrate: {
      mode: 'component',
      intro: 'Heroicons components end in <code>Icon</code> and the style is in the import path. with icons components drop the suffix (both <code>Home</code> and <code>HomeIcon</code> are exported) and use <code>@withicons/react/solid</code> for solid.',
      importRe: "import\\s*\\{([^}]*)\\}\\s*from\\s*['\"](@heroicons/(?:react|vue)/[0-9]+/(?:outline|solid))['\"]",
      stripRe: 'Icon$', solidPkg: '/solid',
      map: [['home / HomeIcon', 'home'], ['magnifying-glass / MagnifyingGlassIcon', 'search'], ['trash / TrashIcon', 'trash'], ['cog-6-tooth / Cog6ToothIcon', 'settings'], ['user / UserIcon', 'user'], ['envelope / EnvelopeIcon', 'mail'], ['x-mark / XMarkIcon', 'close'], ['check / CheckIcon', 'check'], ['plus / PlusIcon', 'plus'], ['bars-3 / Bars3Icon', 'menu'], ['pencil-square / PencilSquareIcon', 'edit'], ['pencil / PencilIcon', 'pencil'], ['arrow-down-tray / ArrowDownTrayIcon', 'download'], ['arrow-up-tray / ArrowUpTrayIcon', 'upload'], ['heart / HeartIcon', 'heart'], ['star / StarIcon', 'star'], ['bell / BellIcon', 'bell'], ['calendar / CalendarIcon', 'calendar'], ['lock-closed / LockClosedIcon', 'lock'], ['arrow-right / ArrowRightIcon', 'arrow-right'], ['chevron-down / ChevronDownIcon', 'chevron-down'], ['share / ShareIcon', 'share'], ['document-duplicate / DocumentDuplicateIcon', 'copy'], ['arrow-top-right-on-square / ArrowTopRightOnSquareIcon', 'external-link'], ['eye / EyeIcon', 'eye'], ['funnel / FunnelIcon', 'filter'], ['information-circle / InformationCircleIcon', 'info-circle'], ['exclamation-triangle / ExclamationTriangleIcon', 'alert-triangle'], ['shopping-cart / ShoppingCartIcon', 'shopping-cart'], ['photo / PhotoIcon', 'image'], ['phone / PhoneIcon', 'phone']],
      before: ['jsx', "import { HomeIcon, Cog6ToothIcon } from '@heroicons/react/24/outline'\nimport { HeartIcon } from '@heroicons/react/24/solid'\n\n<HomeIcon className=\"size-6\" />\n<Cog6ToothIcon className=\"size-6\" />\n<HeartIcon className=\"size-6 text-rose-500\" />"],
      after: ['jsx', "import { Home, Settings } from '@withicons/react'\nimport { Heart } from '@withicons/react/solid'\n\n<Home className=\"size-6\" />\n<Settings className=\"size-6\" />\n<Heart className=\"size-6 text-rose-500\" />"],
      sample: "import { HomeIcon, Cog6ToothIcon, XMarkIcon } from '@heroicons/react/24/outline'\nimport { HeartIcon } from '@heroicons/react/24/solid'\n\nexport function Bar() {\n  return <nav><HomeIcon className=\"size-6\" /><Cog6ToothIcon className=\"size-6\" /><XMarkIcon /><HeartIcon /></nav>\n}",
      styleNote: 'Heroicons <b>Outline</b> → our <b>Line</b>; <b>Solid</b>, <b>Mini</b> and <b>Micro</b> → our <b>Solid</b>. Tailwind <code>size-*</code> and <code>text-*</code> classes keep working because our icons use <code>currentColor</code>.',
    },
    faq: [
      ['Do with icons work with Tailwind CSS like Heroicons?', 'Yes. Icons use currentColor and accept className, so <code>size-6</code> and <code>text-rose-500</code> work the same way.'],
    ],
  },

  /* ───────────────────────── Lucide ───────────────────────── */
  {
    slug: 'lucide', name: 'Lucide', kind: 'open', color: 'sketch', mark: 'Lu', url: 'https://lucide.dev', searchQ: 'funnel',
    known: 'a community-built, consistent stroke icon set (a fork of Feather) with over 1,600 icons and official packages for almost every framework; popular with shadcn/ui.',
    hub: { license: 'ISC', price: 'Free', count: 'over 1,600', styles: '1 (stroke, adjustable)', classes: 'Icon font (not for heavy production)', ai: 'llms.txt' },
    facts: {
      license: ['ISC; icons that came from Feather are also MIT', [3]],
      price: ['Free', [1]],
      count: ['Over 1,600 (“1600+” in the README; the site search listed 1,857 when checked)', [2, 1]],
      styles: ['One stroke style on a 24 × 24 canvas; size, colour and stroke width are adjustable', [4]],
      frameworks: ['Official packages for React, Vue, Svelte, Solid, Angular, Preact, Astro, React Native and vanilla JS', [5]],
      classes: ['An icon font via <code>lucide-static</code> (<code>&lt;i class="icon-house"&gt;</code>), which the docs don’t recommend for high-traffic production', [6]],
      selfhost: ['Yes: npm, <code>lucide-static</code> (SVGs, sprite, font) or download', [5]],
      design: ['Figma plugin linked from the official README', [2]],
      ai: ['Official llms.txt; no official MCP server found', [7]],
      attribution: ['No (keep the licence notice when redistributing the code)', [3]],
    },
    sources: [
      ['Lucide website', 'https://lucide.dev'],
      ['Lucide README (GitHub)', 'https://github.com/lucide-icons/lucide'],
      ['Lucide licence', 'https://lucide.dev/license'],
      ['Lucide icon design guide', 'https://lucide.dev/contribute/icons/specification'],
      ['Lucide packages', 'https://lucide.dev/packages'],
      ['Lucide static icon font', 'https://lucide.dev/guide/static/font'],
      ['Lucide llms.txt', 'https://lucide.dev/llms.txt'],
      ['Lucide icons folder (names and aliases)', 'https://github.com/lucide-icons/lucide/tree/main/icons'],
    ],
    them: [
      'You need a big stroke set (over 1,600 icons) with first-party packages for nearly every framework.',
      'You use shadcn/ui, where Lucide is the default.',
      'You want a single, adjustable outline style and a very active community.',
    ],
    us: [
      'You want more than one look: Solid, Duo and four expressive styles share the same names and grid.',
      'You want plain <code>&lt;i&gt;</code> classes that are meant for production, with no JavaScript.',
      'You also need icons for slides and docs, with copy and download in any colour.',
    ],
    migrate: {
      mode: 'component',
      intro: 'Both export one component per icon. Change the import source, then rename the few icons that differ (<code>House</code> → <code>Home</code>, <code>X</code> → <code>Close</code>, <code>Funnel</code> → <code>Filter</code>). Props like <code>size</code>, <code>color</code>, <code>strokeWidth</code> and <code>absoluteStrokeWidth</code> keep their names.',
      importRe: "import\\s*\\{([^}]*)\\}\\s*from\\s*['\"](lucide-react|lucide-solid|lucide-preact|@lucide/[a-z-]+|lucide-vue-next|lucide-svelte)['\"]",
      stripRe: 'Icon$',
      map: [['house', 'home'], ['search', 'search'], ['trash', 'trash'], ['trash-2', 'trash'], ['settings', 'settings'], ['user', 'user'], ['mail', 'mail'], ['x', 'close'], ['check', 'check'], ['plus', 'plus'], ['menu', 'menu'], ['square-pen', 'edit'], ['pencil', 'pencil'], ['download', 'download'], ['upload', 'upload'], ['heart', 'heart'], ['star', 'star'], ['bell', 'bell'], ['calendar', 'calendar'], ['lock', 'lock'], ['arrow-right', 'arrow-right'], ['chevron-down', 'chevron-down'], ['share-2', 'share'], ['copy', 'copy'], ['external-link', 'external-link'], ['eye', 'eye'], ['funnel', 'filter'], ['info', 'info-circle'], ['triangle-alert', 'alert-triangle'], ['shopping-cart', 'shopping-cart'], ['image', 'image'], ['phone', 'phone']],
      before: ['jsx', "import { House, Search, X, Funnel } from 'lucide-react'\n\n<House />\n<Search size={20} strokeWidth={1.5} />\n<X className=\"text-red-500\" />\n<Funnel />"],
      after: ['jsx', "import { Home, Search, Close, Filter } from '@withicons/react'\n\n<Home />\n<Search size={20} strokeWidth={1.5} />\n<Close className=\"text-red-500\" />\n<Filter />"],
      sample: "import { House, Search, Trash2, X, Funnel } from 'lucide-react'\n\nexport function Bar() {\n  return <nav><House /><Search size={20} /><Trash2 /><X /><Funnel /></nav>\n}",
      styleNote: 'Lucide’s stroke style → our <b>Line</b> (default import). Want filled or tinted? Import from <code>@withicons/react/solid</code> or <code>/duo</code>.',
    },
    faq: [
      ['Is with icons a fork of Lucide or Feather?', 'No. with icons is drawn from scratch on its own 24 × 24 skeletons, then rendered in 7 styles. It shares the same kind of API (one component per icon, size/color/strokeWidth props), which makes switching easy.'],
    ],
  },

  /* ───────────────────────── Feather ───────────────────────── */
  {
    slug: 'feather', name: 'Feather', also: 'Feather Icons', kind: 'open', color: 'engrave', mark: 'Fe', url: 'https://feathericons.com', searchQ: 'alert triangle',
    known: 'the original minimal 24 px stroke icon set: 287 simple, beautiful icons that inspired many later libraries.',
    hub: { license: 'MIT', price: 'Free', count: '287', styles: '1 (stroke)', classes: 'No (data-feather + JS)', ai: 'None official found' },
    facts: {
      license: ['MIT', [2]],
      price: ['Free', [1]],
      count: ['287 (“Search 287 icons”)', [1]],
      styles: ['One stroke style on a 24 × 24 grid, 2 px stroke', [1]],
      frameworks: ['Vanilla JS (<code>feather-icons</code>) and React via <code>react-feather</code>; other framework packages are community-made', [5, 6]],
      classes: ['No icon font: <code>&lt;i data-feather="home"&gt;&lt;/i&gt;</code> plus <code>feather.replace()</code>, or the SVG sprite', [5]],
      selfhost: ['Yes: npm or download the SVGs', [5]],
      design: ['Figma component library', [5]],
      ai: ['No official MCP server or llms.txt found', []],
      attribution: ['No (keep the MIT notice when redistributing the code)', [2]],
    },
    sources: [
      ['Feather website', 'https://feathericons.com'],
      ['Feather licence (GitHub)', 'https://github.com/feathericons/feather/blob/main/LICENSE'],
      ['Feather releases (GitHub)', 'https://github.com/feathericons/feather/releases'],
      ['Feather repository data (GitHub API)', 'https://api.github.com/repos/feathericons/feather'],
      ['Feather README', 'https://github.com/feathericons/feather#readme'],
      ['npm: react-feather', 'https://www.npmjs.com/package/react-feather'],
      ['Feather icons folder (names)', 'https://github.com/feathericons/feather/tree/main/icons'],
    ],
    them: [
      'You love its minimal, timeless look and 287 icons cover what you need.',
      'You want a tiny, stable dependency that rarely changes. The latest release is v4.29.2 (May 2024).',
      'Your project already uses <code>data-feather</code> and works fine.',
    ],
    us: [
      'You want a set that’s actively growing, with the same clean outline look as Line.',
      'You want filled, tinted and expressive styles with the same names.',
      'You want first-party packages for React, Vue, Svelte, Angular and Solid, plus CSS classes with no JavaScript.',
    ],
    migrate: {
      mode: 'feather',
      intro: 'Feather swaps <code>&lt;i data-feather="…"&gt;</code> for SVG with JavaScript. with icons can do it with CSS alone: replace each tag with <code>&lt;i class="with with-…"&gt;</code> and drop <code>feather.replace()</code>. Most names are identical.',
      map: [['home', 'home'], ['search', 'search'], ['trash-2', 'trash'], ['settings', 'settings'], ['user', 'user'], ['mail', 'mail'], ['x', 'close'], ['check', 'check'], ['plus', 'plus'], ['menu', 'menu'], ['edit', 'edit'], ['edit-2', 'pencil'], ['download', 'download'], ['upload', 'upload'], ['heart', 'heart'], ['star', 'star'], ['bell', 'bell'], ['calendar', 'calendar'], ['lock', 'lock'], ['arrow-right', 'arrow-right'], ['chevron-down', 'chevron-down'], ['share-2', 'share'], ['copy', 'copy'], ['external-link', 'external-link'], ['eye', 'eye'], ['filter', 'filter'], ['info', 'info-circle'], ['alert-triangle', 'alert-triangle'], ['shopping-cart', 'shopping-cart'], ['image', 'image'], ['phone', 'phone']],
      before: ['html', '<script src="…/feather.min.js"></script>\n\n<i data-feather="home"></i>\n<i data-feather="x"></i>\n<i data-feather="trash-2"></i>\n<script>feather.replace()</script>'],
      after: ['html', '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@withicons/web/dist/classes/with-line.css">\n\n<i class="with with-home"></i>\n<i class="with with-close"></i>\n<i class="with with-trash"></i>'],
      sample: '<i data-feather="home"></i>\n<i data-feather="x"></i>\n<i data-feather="trash-2"></i>\n<i data-feather="share-2"></i>\n<i data-feather="info"></i>',
      styleNote: 'Feather’s stroke style → our <b>Line</b>. Our Line stroke is 1.75 by default (Feather uses 2); set <code>strokeWidth={2}</code> in the components to match exactly.',
    },
    faq: [
      ['Is Feather still maintained?', 'Feather still works and is not archived. Its latest release is v4.29.2 (May 2024) and the last commit we saw was in March 2025, so new icons arrive rarely. Many teams moved to Lucide, a Feather fork, or to sets like with icons.'],
    ],
  },

  /* ───────────────────────── Phosphor ───────────────────────── */
  {
    slug: 'phosphor', name: 'Phosphor', also: 'Phosphor Icons', kind: 'open', color: 'gloss', mark: 'Ph', url: 'https://phosphoricons.com', searchQ: 'gear',
    known: 'a flexible family of about 1,500 icons in six weights (thin, light, regular, bold, fill, duotone), with packages for web, mobile and desktop.',
    hub: { license: 'MIT', price: 'Free (donations)', count: 'about 1,500 × 6 weights', styles: '6 weights', classes: 'Yes (ph ph-*)', ai: 'None official found' },
    facts: {
      license: ['MIT', [2]],
      price: ['Free; optional donations', [6]],
      count: ['About 1,500 icons in each of 6 weights (1,512 per weight in <code>@phosphor-icons/core</code> 2.1.1, over 9,000 SVGs)', [5, 4]],
      styles: ['Six weights: Thin, Light, Regular, Bold, Fill and Duotone', [1]],
      frameworks: ['React, Vue, web components, a web font, React Native, Flutter, Swift, Elm and Android', [1, 7]],
      classes: ['Yes: <code>&lt;i class="ph ph-house"&gt;&lt;/i&gt;</code>; weights via <code>ph-bold</code>, <code>ph-fill</code>…', [3]],
      selfhost: ['Yes: npm (<code>@phosphor-icons/web</code>, <code>@phosphor-icons/core</code>) or CDN', [3]],
      design: ['Official Figma plugin and file; Sketch and Penpot plugins', [1]],
      ai: ['No official MCP server or llms.txt found', []],
      attribution: ['No (keep the MIT notice when redistributing the code)', [2]],
    },
    sources: [
      ['Phosphor homepage README (GitHub)', 'https://github.com/phosphor-icons/homepage#readme'],
      ['Phosphor licence', 'https://raw.githubusercontent.com/phosphor-icons/homepage/master/LICENSE'],
      ['@phosphor-icons/web README', 'https://github.com/phosphor-icons/web#readme'],
      ['@phosphor-icons/react README', 'https://github.com/phosphor-icons/react#readme'],
      ['@phosphor-icons/core 2.1.1 (names and counts)', 'https://unpkg.com/@phosphor-icons/core@2.1.1/'],
      ['Phosphor website', 'https://phosphoricons.com'],
      ['Phosphor on GitHub', 'https://github.com/phosphor-icons'],
    ],
    them: [
      'You want six weights of the same icon, from hairline Thin to Bold and Duotone.',
      'You build for mobile and desktop too (React Native, Flutter, Swift).',
      'You need about 1,500 icons, five times our 300.',
    ],
    us: [
      'You want styles with more character: Gloss, Engrave, Blueprint and Sketch, not just weights.',
      'You want Svelte, Angular and Solid packages and an MCP server for AI tools.',
      'You also make slides and docs: copy as PNG or SVG in any colour, straight from the site.',
    ],
    migrate: {
      mode: 'class',
      intro: 'Phosphor’s web font uses <code>ph ph-name</code> plus a weight class; with icons uses <code>with with-name</code> plus a style class. Fix the names that differ (<code>house</code> → <code>home</code>, <code>gear</code> → <code>settings</code>, <code>list</code> → <code>menu</code>).',
      map: [['house', 'home'], ['magnifying-glass', 'search'], ['trash', 'trash'], ['gear', 'settings'], ['user', 'user'], ['envelope', 'mail'], ['x', 'close'], ['check', 'check'], ['plus', 'plus'], ['list', 'menu'], ['pencil-simple', 'pencil'], ['download-simple', 'download'], ['upload-simple', 'upload'], ['heart', 'heart'], ['star', 'star'], ['bell', 'bell'], ['calendar', 'calendar'], ['lock', 'lock'], ['arrow-right', 'arrow-right'], ['caret-down', 'chevron-down'], ['share-network', 'share'], ['copy', 'copy'], ['arrow-square-out', 'external-link'], ['eye', 'eye'], ['funnel', 'filter'], ['info', 'info-circle'], ['warning', 'alert-triangle'], ['shopping-cart', 'shopping-cart'], ['image', 'image'], ['phone', 'phone']],
      prefixes: ['ph-'],
      tokens: { ph: '', 'ph-thin': '', 'ph-light': '', 'ph-regular': '', 'ph-bold': '', 'ph-fill': 'style:solid', 'ph-duotone': 'style:duo' },
      before: ['html', '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@phosphor-icons/web@<VERSION>/src/regular/style.css">\n\n<i class="ph ph-house"></i>\n<i class="ph-fill ph-heart"></i>\n<i class="ph-duotone ph-gear"></i>'],
      after: ['html', '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@withicons/web/dist/classes/with-all.css">\n\n<i class="with with-home"></i>\n<i class="with with-heart with-solid"></i>\n<i class="with with-settings with-duo"></i>'],
      sample: '<i class="ph ph-house"></i>\n<i class="ph-fill ph-heart"></i>\n<i class="ph-duotone ph-gear"></i>\n<i class="ph ph-list"></i>\n<i class="ph-bold ph-magnifying-glass"></i>',
      styleNote: 'Phosphor <b>Regular</b>, <b>Light</b>, <b>Thin</b> and <b>Bold</b> → our <b>Line</b> (adjust <code>strokeWidth</code> in the components); <b>Fill</b> → <b>with-solid</b>; <b>Duotone</b> → <b>with-duo</b>.',
    },
    faq: [
      ['Does with icons have a duotone style like Phosphor?', 'Yes: Duo is an outline over a soft tinted fill. With the optional runtime script you can set the tint colour separately (<code>--with-duo</code>).'],
    ],
  },

  /* ───────────────────────── Bootstrap Icons ───────────────────────── */
  {
    slug: 'bootstrap-icons', name: 'Bootstrap Icons', kind: 'open', color: 'duo', mark: 'Bi', url: 'https://icons.getbootstrap.com', searchQ: 'telephone',
    known: 'Bootstrap’s official icon library: over 2,000 polished icons on a 16 px grid with an easy web font, usable with or without Bootstrap.',
    hub: { license: 'MIT', price: 'Free', count: 'over 2,000', styles: 'Outline + fill variants', classes: 'Yes (bi bi-*)', ai: 'None official found' },
    facts: {
      license: ['MIT', [3]],
      price: ['Free', [1]],
      count: ['Over 2,000 (“over 2,000 icons”; 2,078 in v1.13.1)', [1, 5]],
      styles: ['One look, with separate outline and <code>-fill</code> versions of many icons; 16 × 16 grid', [2]],
      frameworks: ['No official framework components; SVGs, a sprite and a web font that work in any project', [2]],
      classes: ['Yes: <code>&lt;i class="bi bi-house"&gt;&lt;/i&gt;</code>', [1]],
      selfhost: ['Yes: npm, Composer or download from GitHub releases', [2]],
      design: ['Official Figma file', [2]],
      ai: ['No official MCP server or llms.txt found', []],
      attribution: ['No (keep the MIT notice when redistributing the code)', [3]],
    },
    sources: [
      ['Bootstrap Icons website', 'https://icons.getbootstrap.com'],
      ['Bootstrap Icons README (GitHub)', 'https://github.com/twbs/icons#readme'],
      ['Bootstrap Icons licence', 'https://github.com/twbs/icons/blob/main/LICENSE'],
      ['Bootstrap Icons releases', 'https://github.com/twbs/icons/releases'],
      ['bootstrap-icons.json v1.13.1 (names)', 'https://unpkg.com/bootstrap-icons@1.13.1/font/bootstrap-icons.json'],
    ],
    them: [
      'Your site is built on Bootstrap and you want icons that match it exactly.',
      'You need over 2,000 icons, including many outline/fill pairs.',
      'You want a dependable, simple web font with no build step.',
    ],
    us: [
      'You want official components for React, Vue, Svelte, Angular and Solid.',
      'You want 24 px icons with more styles: Duo, Gloss, Engrave, Blueprint and Sketch.',
      'You want AI assistants to find icons for you through llms.txt, a skill or MCP.',
    ],
    migrate: {
      mode: 'class',
      intro: 'Both use a base class plus a name class, so the change is mostly <code>bi bi-</code> → <code>with with-</code>. Bootstrap marks filled icons with a <code>-fill</code> suffix; with icons uses <code>with-solid</code>.',
      map: [['bi-house', 'home'], ['bi-search', 'search'], ['bi-trash', 'trash'], ['bi-gear', 'settings'], ['bi-person', 'user'], ['bi-envelope', 'mail'], ['bi-x', 'close'], ['bi-x-lg', 'close'], ['bi-check', 'check'], ['bi-plus', 'plus'], ['bi-list', 'menu'], ['bi-pencil', 'pencil'], ['bi-download', 'download'], ['bi-upload', 'upload'], ['bi-heart', 'heart'], ['bi-star', 'star'], ['bi-bell', 'bell'], ['bi-calendar', 'calendar'], ['bi-lock', 'lock'], ['bi-arrow-right', 'arrow-right'], ['bi-chevron-down', 'chevron-down'], ['bi-share', 'share'], ['bi-copy', 'copy'], ['bi-box-arrow-up-right', 'external-link'], ['bi-eye', 'eye'], ['bi-funnel', 'filter'], ['bi-info-circle', 'info-circle'], ['bi-exclamation-triangle', 'alert-triangle'], ['bi-cart', 'shopping-cart'], ['bi-image', 'image'], ['bi-telephone', 'phone']],
      prefixes: ['bi-'], suffixes: [['-fill', 'solid']],
      tokens: { bi: '' },
      before: ['html', '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css">\n\n<i class="bi bi-house"></i>\n<i class="bi bi-heart-fill"></i>\n<i class="bi bi-gear"></i>'],
      after: ['html', '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@withicons/web/dist/classes/with-all.css">\n\n<i class="with with-home"></i>\n<i class="with with-heart with-solid"></i>\n<i class="with with-settings"></i>'],
      sample: '<i class="bi bi-house"></i>\n<i class="bi bi-heart-fill"></i>\n<i class="bi bi-gear"></i>\n<i class="bi bi-person-fill"></i>\n<i class="bi bi-telephone"></i>',
      styleNote: 'Bootstrap outline icons → our <b>Line</b>; <code>-fill</code> icons → <b>with-solid</b>. Icons size with the font, just like Bootstrap’s.',
    },
    faq: [
      ['Can I use with icons in a Bootstrap project?', 'Yes. The <code>&lt;i class="with with-…"&gt;</code> classes don’t depend on any framework and sit happily next to Bootstrap’s CSS.'],
    ],
  },

  /* ───────────────────────── Tabler Icons ───────────────────────── */
  {
    slug: 'tabler', name: 'Tabler Icons', kind: 'open', color: 'solid', mark: 'Ti', url: 'https://tabler.io/icons', searchQ: 'photo',
    known: 'the largest free MIT stroke set: over 6,000 icons in outline and filled styles on a 24 × 24 grid, with packages for almost every framework.',
    hub: { license: 'MIT', price: 'Free; optional paid bundles', count: 'over 6,000', styles: '2 (outline, filled)', classes: 'Yes (ti ti-*)', ai: 'None official found' },
    facts: {
      license: ['MIT', [3]],
      price: ['Icons free; optional one-time paid bundles ($9 compiled files, $69 with templates and illustrations, as listed)', [1]],
      count: ['Over 6,000 (“over 6200”; 6,220 on the site when checked)', [2, 1]],
      styles: ['Outline and Filled, on a 24 × 24 grid with a 2 px stroke', [1]],
      frameworks: ['React, Vue, Svelte, Solid, Preact, Angular, React Native and Astro packages; web font, sprite, PNG and PDF', [2]],
      classes: ['Yes, with the web font: <code>&lt;i class="ti ti-home"&gt;&lt;/i&gt;</code>', [2]],
      selfhost: ['Yes: npm (<code>@tabler/icons</code>, <code>@tabler/icons-webfont</code>) or download', [2]],
      design: ['Official Figma plugin', [1]],
      ai: ['No official MCP server or llms.txt found (community MCP servers exist)', []],
      attribution: ['No (keep the MIT notice when redistributing the code)', [3]],
    },
    sources: [
      ['Tabler Icons website', 'https://tabler.io/icons'],
      ['Tabler Icons README (GitHub)', 'https://github.com/tabler/tabler-icons#readme'],
      ['Tabler Icons licence', 'https://github.com/tabler/tabler-icons/blob/main/LICENSE'],
      ['Tabler Icons releases', 'https://github.com/tabler/tabler-icons/releases'],
      ['@tabler/icons 3.48.0 icons.json (names)', 'https://unpkg.com/@tabler/icons@3.48.0/icons.json'],
    ],
    them: [
      'You want the biggest free MIT stroke set: over 6,000 icons, very actively maintained.',
      'You need a niche icon that a 300-icon set won’t have.',
      'You want packages for nearly every framework, plus PNG and PDF exports.',
    ],
    us: [
      'You want a curated 300 that’s easy to browse, where every icon has a reason to exist.',
      'You want five extra looks with the same names: Duo, Gloss, Engrave, Blueprint and Sketch.',
      'You want an MCP server and agent skill so AI tools pick the right icon.',
    ],
    migrate: {
      mode: 'class',
      intro: 'Tabler’s web font uses <code>ti ti-name</code>; with icons uses <code>with with-name</code>. Many names are identical (<code>home</code>, <code>search</code>, <code>settings</code>); fix the few that differ, like <code>x</code> → <code>close</code> and <code>photo</code> → <code>image</code>.',
      map: [['ti-home', 'home'], ['ti-search', 'search'], ['ti-trash', 'trash'], ['ti-settings', 'settings'], ['ti-user', 'user'], ['ti-mail', 'mail'], ['ti-x', 'close'], ['ti-check', 'check'], ['ti-plus', 'plus'], ['ti-menu-2', 'menu'], ['ti-edit', 'edit'], ['ti-pencil', 'pencil'], ['ti-download', 'download'], ['ti-upload', 'upload'], ['ti-heart', 'heart'], ['ti-star', 'star'], ['ti-bell', 'bell'], ['ti-calendar', 'calendar'], ['ti-lock', 'lock'], ['ti-arrow-right', 'arrow-right'], ['ti-chevron-down', 'chevron-down'], ['ti-share', 'share'], ['ti-copy', 'copy'], ['ti-external-link', 'external-link'], ['ti-eye', 'eye'], ['ti-filter', 'filter'], ['ti-info-circle', 'info-circle'], ['ti-alert-triangle', 'alert-triangle'], ['ti-shopping-cart', 'shopping-cart'], ['ti-photo', 'image'], ['ti-phone', 'phone']],
      prefixes: ['ti-'], suffixes: [['-filled', 'solid']],
      tokens: { ti: '' },
      before: ['html', '<link rel="stylesheet" href="…/@tabler/icons-webfont/dist/tabler-icons.min.css">\n\n<i class="ti ti-home"></i>\n<i class="ti ti-x"></i>\n<i class="ti ti-photo"></i>'],
      after: ['html', '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@withicons/web/dist/classes/with-line.css">\n\n<i class="with with-home"></i>\n<i class="with with-close"></i>\n<i class="with with-image"></i>'],
      sample: '<i class="ti ti-home"></i>\n<i class="ti ti-x"></i>\n<i class="ti ti-photo"></i>\n<i class="ti ti-heart-filled"></i>\n<i class="ti ti-menu-2"></i>',
      styleNote: 'Tabler <b>outline</b> → our <b>Line</b>; <code>-filled</code> → <b>with-solid</b>. Tabler strokes are 2 px; ours default to 1.75 and can be changed in the components.',
    },
    faq: [
      ['Tabler has 6,000+ icons. Why pick a set with 300?', 'Because a smaller set is quicker to search and every icon is drawn in 7 matching styles. If you need a rare icon, Tabler is a great choice, and the two can be used side by side.'],
    ],
  },
]
