// Emits @withicons/mcp (MCP server: stdio bin + AWS Lambda handler + JSON API) and the unscoped `withicons` CLI.
//   packages/mcp/dist/data/{meta,search-index,svg-<style>}.json   icon data (read from disk by stdio/lib)
//   packages/mcp/dist/stdio.mjs     bin `withicons-mcp`  (bundled: MCP SDK + zod + search engine; no runtime deps)
//   packages/mcp/dist/lib.mjs       library used by the CLI (search, get, snippets)
//   packages/mcp/dist/lambda.mjs    `handler` for a Lambda Function URL — ONE self-contained file, data inlined
//   packages/cli/dist/cli.mjs       bin `withicons`
// Bundling needs esbuild from packages/mcp/node_modules (cd packages/mcp && npm install). Without it the data
// and package files are still written and the previous bundles are kept.
import fs from 'fs'
import path from 'path'
import { createRequire } from 'module'
import { fileURLToPath, pathToFileURL } from 'url'
import { basePkg, writePkg } from './emit-core.mjs'

export const after = ['search']
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..')

// skills/with-icons/** -> packages/cli/src/skill-data.mjs (strings), so `withicons init` / `withicons skill` work offline
export function writeSkillData(root = ROOT) {
  const dir = path.join(root, 'skills', 'with-icons'), cliSrc = path.join(root, 'packages', 'cli', 'src')
  if (!fs.existsSync(path.join(dir, 'SKILL.md')) || !fs.existsSync(cliSrc)) return
  const files = {}
  const walk = rel => {
    for (const e of fs.readdirSync(path.join(dir, rel), { withFileTypes: true }).sort((a, b) => a.name < b.name ? -1 : 1)) {
      const r = rel ? `${rel}/${e.name}` : e.name
      if (e.isDirectory()) walk(r)
      else if (/\.md$/.test(e.name)) files[r] = fs.readFileSync(path.join(dir, r), 'utf8').replace(/\r\n/g, '\n')
    }
  }
  walk('')
  fs.writeFileSync(path.join(cliSrc, 'skill-data.mjs'),
    `// Generated by forge/lib/emit-mcp.mjs from skills/with-icons/ — do not edit.\nexport const SKILL_FILES = ${JSON.stringify(files, null, 1)}\n`)
}

export async function bundle({ root = ROOT, version = '0.1.0', styles } = {}) {
  writeSkillData(root)
  const mcpDir = path.join(root, 'packages', 'mcp')
  const req = createRequire(path.join(mcpDir, 'package.json'))
  let esbuild
  try { esbuild = req('esbuild') } catch { return 'bundles skipped (no esbuild: cd packages/mcp && npm install)' }
  if (styles) {
    fs.writeFileSync(path.join(mcpDir, 'src', 'data-inline.mjs'),
      `// Generated by forge/lib/emit-mcp.mjs — data inlined into dist/lambda.mjs so the function is one self-contained file.\n` +
      `import meta from '../dist/data/meta.json'\nimport index from '../dist/data/search-index.json'\n` +
      styles.map((s, i) => `import s${i} from '../dist/data/svg-${s}.json'\n`).join('') +
      `\nconst svgs = { ${styles.map((s, i) => `${JSON.stringify(s)}: s${i}`).join(', ')} }\n` +
      `export function loadData() {\n  return { meta, index, svg: style => svgs[style] || {} }\n}\n`)
  }
  const dataPlugin = file => ({
    name: 'data', setup(b) { b.onResolve({ filter: /^#data$/ }, () => ({ path: path.join(mcpDir, 'src', file) })) },
  })
  const common = {
    bundle: true, platform: 'node', format: 'esm', target: 'node18', logLevel: 'silent', legalComments: 'none',
    define: { __VERSION__: JSON.stringify(version) },
    banner: { js: `import { createRequire as __cr } from 'node:module'; const require = __cr(import.meta.url);` },
  }
  const out = []
  const run = async (entry, outfile, data, extra = {}) => {
    const r = await esbuild.build({ ...common, ...extra, entryPoints: [path.join(mcpDir, 'src', entry)], outfile, plugins: [dataPlugin(data)], metafile: true })
    out.push(`${path.basename(outfile)} ${(fs.statSync(outfile).size / 1024).toFixed(0)} KB`)
    return r
  }
  await run('stdio.mjs', path.join(mcpDir, 'dist', 'stdio.mjs'), 'data-fs.mjs', { minify: true, banner: { js: `#!/usr/bin/env node\n${common.banner.js}` } })
  await run('lib.mjs', path.join(mcpDir, 'dist', 'lib.mjs'), 'data-fs.mjs')
  await run('lambda.mjs', path.join(mcpDir, 'dist', 'lambda.mjs'), 'data-inline.mjs', { minify: true })
  const cliDir = path.join(root, 'packages', 'cli')
  if (fs.existsSync(path.join(cliDir, 'src', 'cli.mjs'))) {
    await esbuild.build({ ...common, entryPoints: [path.join(cliDir, 'src', 'cli.mjs')], outfile: path.join(cliDir, 'dist', 'cli.mjs'), external: ['@withicons/mcp', '@withicons/mcp/*'], banner: { js: '#!/usr/bin/env node' } })
    out.push(`cli.mjs ${(fs.statSync(path.join(cliDir, 'dist', 'cli.mjs')).size / 1024).toFixed(0)} KB`)
  }
  return out.join(', ')
}

const readme = (root, pkg, version) => {
  const f = path.join(root, 'packages', pkg, 'README.src.md')
  return fs.existsSync(f) ? fs.readFileSync(f, 'utf8').split('{{version}}').join(version) : `# ${pkg}\n`
}

export default async function emit(ctx) {
  const root = ctx.root || ROOT
  const version = ctx.version || '0.1.0'
  const P = 'packages/mcp/dist/data'
  // meta + search index + per-style SVG maps
  const idxFile = path.join(root, 'packages', 'search', 'dist', 'index.json')
  if (!fs.existsSync(idxFile)) throw new Error('packages/search/dist/index.json missing (emit-search must run first)')
  const index = fs.readFileSync(idxFile, 'utf8')
  const cats = new Map()
  for (const ic of ctx.icons) cats.set(ic.category, (cats.get(ic.category) || 0) + 1)
  const meta = {
    version,
    styles: ctx.styles.map(s => ({ name: s.name, title: s.title, kind: s.kind, description: s.description })),
    categories: [...cats].sort((a, b) => a[0] < b[0] ? -1 : 1).map(([name, count]) => ({ name, count })),
    icons: ctx.icons.map(ic => ({ name: ic.name, category: ic.category, description: ic.description, aliases: ic.aliases, tags: ic.tags })),
  }
  ctx.write(`${P}/meta.json`, JSON.stringify(meta))
  ctx.write(`${P}/search-index.json`, index)
  let svgBytes = 0
  for (const s of ctx.styles) {
    const map = {}
    for (const ic of ctx.icons) if (ic.render[s.name]) map[ic.name] = ic.render[s.name].svg
    const txt = JSON.stringify(map)
    svgBytes += txt.length
    ctx.write(`${P}/svg-${s.name}.json`, txt)
  }

  // package.json files (bundled -> no runtime dependencies)
  const mcpPkg = {
    ...basePkg(ctx, '@withicons/mcp', 'MCP server for with icons: search 300 icons x 7 styles in plain English and get paste-ready SVG, React, Vue, Svelte, Angular, Solid, web-component or class code. stdio (npx) and AWS Lambda.',
      ['mcp', 'model-context-protocol', 'mcp-server', 'ai', 'claude', 'cursor', 'icon-search']),
    type: 'module',
    bin: { 'withicons-mcp': 'dist/stdio.mjs' },
    main: './dist/lib.mjs',
    exports: {
      '.': './dist/lib.mjs',
      './lib': './dist/lib.mjs',
      './stdio': './dist/stdio.mjs',
      './lambda': './dist/lambda.mjs',
      './data/*': './dist/data/*',
      './package.json': './package.json',
    },
    files: ['dist', 'README.md', 'LICENSE'],
    publishConfig: { access: 'public' },
    engines: { node: '>=18' },
    imports: { '#data': './src/data-fs.mjs' },
    scripts: { build: 'node ../../forge/lib/emit-mcp.mjs', test: 'node --test test/*.test.mjs' },
    devDependencies: { '@modelcontextprotocol/sdk': '^1.31.0', esbuild: '^0.28.2', zod: '^4.6.5' },
  }
  // keep whatever versions were actually installed
  try {
    const cur = JSON.parse(fs.readFileSync(path.join(root, 'packages', 'mcp', 'package.json'), 'utf8'))
    if (cur.devDependencies) mcpPkg.devDependencies = cur.devDependencies
  } catch {}
  writePkg(ctx, 'mcp', mcpPkg, readme(root, 'mcp', version))

  const cliPkg = {
    ...basePkg(ctx, 'withicons', 'with icons from the terminal: search 300 icons x 7 styles in plain English, print SVG or framework code, get import lines, and add the with icons skill + MCP server to Claude Code, Codex, Cursor, OpenCode or VS Code in one command. `npx withicons init`.',
      ['cli', 'icon-search', 'mcp']),
    type: 'module',
    bin: { withicons: 'dist/cli.mjs' },
    files: ['dist', 'README.md', 'LICENSE'],
    engines: { node: '>=18' },
    dependencies: { '@withicons/mcp': version },
    scripts: { test: 'node --test test/*.test.mjs' },
  }
  cliPkg.repository.directory = 'packages/cli'
  writePkg(ctx, 'cli', cliPkg, readme(root, 'cli', version))

  const b = await bundle({ root, version, styles: ctx.styles.map(s => s.name) })
  return `data ${(svgBytes / 1024 / 1024).toFixed(1)} MB svg + meta; ${b}`
}

// standalone: node forge/lib/emit-mcp.mjs  -> re-bundles only (data must already exist)
if (process.argv[1] && pathToFileURL(path.resolve(process.argv[1])).href === import.meta.url) {
  const meta = JSON.parse(fs.readFileSync(path.join(ROOT, 'packages', 'mcp', 'dist', 'data', 'meta.json'), 'utf8'))
  console.log(await bundle({ root: ROOT, version: meta.version, styles: meta.styles.map(s => s.name) }))
}
