// Emits @withicons/mcp (MCP server: stdio bin + AWS Lambda handler + JSON API) and the unscoped `withicons` CLI.
//   packages/mcp/dist/data/{meta,search-index,svg-<style>}.json   icon data (read from disk by stdio/lib)
//   packages/mcp/dist/stdio.mjs     bin `withicons-mcp`  (bundled: MCP SDK + zod + search engine; no runtime deps)
//   packages/mcp/dist/lib.mjs       library used by the CLI (search, get, snippets)
//   packages/mcp/dist/lambda.mjs    `handler` for a Lambda Function URL: code + small data inlined (~1.8 MB); the per-style SVG maps and
//                                   the palettes are read from ./data/ by byte range on demand (scripts/deploy.mjs zips lambda.mjs + those files)
//   packages/cli/dist/cli.mjs       bin `withicons` (bundles site/js/export/*.js for `withicons export`; @resvg/resvg-js stays
//                                   an external, optional dependency loaded only for PNG-based and animated formats)
//   The export engine (packages/cli/src/export.mjs + @withicons/motion's frame code) is in stdio.mjs and lambda.mjs too, for
//   the export_icon tool; the Lambda never loads resvg (remote export_icon makes vector / code / Lottie files only).
// Bundling needs esbuild from packages/mcp/node_modules (cd packages/mcp && npm install). Without it the data
// and package files are still written and the previous bundles are kept.
import fs from 'fs'
import path from 'path'
import { createRequire } from 'module'
import { fileURLToPath, pathToFileURL } from 'url'
import { basePkg, writePkg, countText, totalText, cdnPkg } from './emit-core.mjs'
import { fill } from './emit-search.mjs'

// search writes the index we ship; motion (when present) writes the animation specs we expose;
// palettes writes the per-icon colour palettes (packages/core/dist/palettes) we expose
export const after = ['search', 'motion', 'palettes']
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..')

// skills/with-icons/** -> packages/cli/src/skill-data.mjs (strings), so `withicons init` / `withicons skill` work offline
export function writeSkillData(root = ROOT) {
  const dir = path.join(root, 'skills', 'with-icons'), cliSrc = path.join(root, 'packages', 'cli', 'src')
  if (!fs.existsSync(path.join(dir, 'SKILL.md')) || !fs.existsSync(cliSrc)) return
  const files = {}
  const walk = rel => {
    for (const e of fs.readdirSync(path.join(dir, rel), { withFileTypes: true }).sort((a, b) => a.name < b.name ? -1 : 1)) {
      const r = rel ? `${rel}/${e.name}` : e.name
      if (e.isDirectory()) walk(r)
      else if (/\.md$/.test(e.name)) files[r] = fs.readFileSync(path.join(dir, r), 'utf8').replace(/\r\n/g, '\n')
    }
  }
  walk('')
  fs.writeFileSync(path.join(cliSrc, 'skill-data.mjs'),
    `// Generated by forge/lib/emit-mcp.mjs from skills/with-icons/ — do not edit.\nexport const SKILL_FILES = ${JSON.stringify(files, null, 1)}\n`)
}

export async function bundle({ root = ROOT, version = '0.1.0', styles } = {}) {
  writeSkillData(root)
  const mcpDir = path.join(root, 'packages', 'mcp')
  const req = createRequire(path.join(mcpDir, 'package.json'))
  let esbuild
  try { esbuild = req('esbuild') } catch { return 'bundles skipped (no esbuild: cd packages/mcp && npm install)' }
  if (styles) {
    fs.writeFileSync(path.join(mcpDir, 'src', 'data-inline.mjs'), [
      '// Generated by forge/lib/emit-mcp.mjs — the data layer of dist/lambda.mjs (the API Lambda; scripts/deploy.mjs zips it).',
      '// Small data (meta, search index, motion specs) is inlined as JSON strings (JSON.parse is faster than parsing a JS object',
      '// literal). The big data stays OUT of the bundle, so a cold start compiles ~1.8 MB of JS instead of ~33 MB: each style\'s',
      '// SVG map (data/svg-<style>.json) and the palettes (data/palettes.json) sit next to lambda.mjs in the zip (mcp/data/).',
      '// One icon\'s SVG (or palette list) is read on demand at a byte range precomputed at build time, so answering for one icon',
      '// never parses a 1-4 MB file; values are cached. A file without ranges falls back to one whole-file read + parse.',
      "import fs from 'node:fs'",
      "import metaRaw from '../dist/data/meta.json?text'",
      "import indexRaw from '../dist/data/search-index.json?text'",
      "import motionRaw from '../dist/data/motion.json?text'",
      "import { multiRaw, rangesRaw } from '#lambda-index'",
      '',
      'const STYLES = new Set(' + JSON.stringify(styles) + ')',
      "const url = f => new URL('./data/' + f, import.meta.url)",
      "const read = f => JSON.parse(fs.readFileSync(url(f), 'utf8'))",
      'const svgs = {}',
      'let palettes = null, multi = null, ranges = null',
      '// { <icon>: value } read lazily from one file: spec = "start,length,..." in meta.icons order (-1 = no value for that icon)',
      'function lazyMap(f, spec, names) {',
      "  const nums = spec.split(',').map(Number), map = {}, file = url(f)",
      '  let fd = null',
      '  names.forEach((name, i) => {',
      '    const start = nums[2 * i], len = nums[2 * i + 1]',
      '    if (start < 0) return',
      '    let v',
      '    Object.defineProperty(map, name, { enumerable: true, get() {',
      "      if (v === undefined) { if (fd === null) fd = fs.openSync(file, 'r'); const b = Buffer.allocUnsafe(len); fs.readSync(fd, b, 0, len, start); v = JSON.parse(b.toString('utf8')) }",
      '      return v',
      '    } })',
      '  })',
      '  return map',
      '}',
      'export function loadData() {',
      '  const meta = JSON.parse(metaRaw), names = meta.icons.map(i => i.name)',
      '  const R = () => ranges || (ranges = JSON.parse(rangesRaw))',
      '  return {',
      '    meta, index: JSON.parse(indexRaw), motion: JSON.parse(motionRaw),',
      "    svg: style => svgs[style] || (svgs[style] = !STYLES.has(style) ? {} : R().svg[style] ? lazyMap('svg-' + style + '.json', R().svg[style], names) : read('svg-' + style + '.json')),",
      "    palettes: () => palettes || (palettes = R().palettes ? { ...R().palettes.head, icons: lazyMap('palettes.json', R().palettes.icons, names) } : read('palettes.json')),",
      '    // name -> styles whose SVG uses a --with-* colour variable (precomputed at build: no need to read all 20 style files)',
      '    multiColour: name => { const m = multi || (multi = JSON.parse(multiRaw)); return Object.hasOwn(m, name) ? [...m[name]] : [] },',
      '  }',
      '}',
      ''].join('\n'))
  }
  // '#lambda-index' (Lambda bundle only), from dist/data/{meta,palettes,svg-*}.json:
  //   multiRaw   JSON { <icon>: [styles whose SVG uses a --with-* variable] } in style order (the test lib.mjs multiColourStyles() runs)
  //   rangesRaw  JSON { svg: { <style>: "start,length,..." }, palettes: { head: { roles, roleLabels, tags }, icons: "start,length,..." } }:
  //              byte range of each icon's value in svg-<style>.json / palettes.json, in meta.icons order (-1,0 = none). A file
  //              is left out (whole-file fallback) unless every range parses back to exactly the value it stands for.
  const lambdaIndex = () => {
    const dataDir = path.join(mcpDir, 'dist', 'data')
    const names = JSON.parse(fs.readFileSync(path.join(dataDir, 'meta.json'), 'utf8')).icons.map(i => i.name)
    // the files are JSON.stringify(...) output; walk an object serialized at byte base the same way to find each value's bytes
    const rangeSpec = (buf, map, base) => {
      const at = new Map()
      let pos = base + 1
      for (const [k, v] of Object.entries(map)) {
        const start = pos + Buffer.byteLength(JSON.stringify(k)) + 1, len = Buffer.byteLength(JSON.stringify(v))
        at.set(k, [start, len]); pos = start + len + 1
      }
      const same = k => { const [s, l] = at.get(k); try { return JSON.stringify(JSON.parse(buf.subarray(s, s + l).toString('utf8'))) === JSON.stringify(map[k]) } catch { return false } }
      return Object.keys(map).every(same) ? names.map(n => (Object.hasOwn(map, n) ? at.get(n) : [-1, 0]).join(',')).join(',') : null
    }
    const multi = {}, ranges = { svg: {} }
    for (const st of styles || []) {
      const f = path.join(dataDir, 'svg-' + st + '.json')
      if (!fs.existsSync(f)) continue
      const buf = fs.readFileSync(f), map = JSON.parse(buf.toString('utf8'))
      for (const [name, svg] of Object.entries(map)) if (/var\(\s*--with-/.test(svg)) (multi[name] ||= []).push(st)
      const spec = rangeSpec(buf, map, 0)
      if (spec) ranges.svg[st] = spec
    }
    const pf = path.join(dataDir, 'palettes.json')
    if (fs.existsSync(pf)) {
      const buf = fs.readFileSync(pf), j = JSON.parse(buf.toString('utf8'))
      const keys = Object.keys(j)
      // icons is the last key: {"roles":…,"roleLabels":…,"tags":…,"icons":{…}}
      if (keys[keys.length - 1] === 'icons' && j.icons && typeof j.icons === 'object') {
        const spec = rangeSpec(buf, j.icons, buf.length - 1 - Buffer.byteLength(JSON.stringify(j.icons)))
        const { icons, ...head } = j
        if (spec) ranges.palettes = { head, icons: spec }
      }
    }
    return 'export const multiRaw = ' + JSON.stringify(JSON.stringify(multi)) + '\nexport const rangesRaw = ' + JSON.stringify(JSON.stringify(ranges)) + '\n'
  }
  const dataPlugin = file => ({
    name: 'data', setup(b) {
      b.onResolve({ filter: /^#data$/ }, () => ({ path: path.join(mcpDir, 'src', file) }))
      b.onResolve({ filter: /^#lambda-index$/ }, () => ({ path: 'lambda-index', namespace: 'lambda-index' }))
      b.onLoad({ filter: /.*/, namespace: 'lambda-index' }, () => ({ contents: lambdaIndex(), loader: 'js' }))
      // "<file>.json?text" -> export default "<file contents as one string>"
      b.onResolve({ filter: /\.json\?text$/ }, a => ({ path: path.resolve(a.resolveDir, a.path.slice(0, -5)), namespace: 'json-text' }))
      b.onLoad({ filter: /.*/, namespace: 'json-text' }, a => ({ contents: `export default ${JSON.stringify(fs.readFileSync(a.path, 'utf8'))}`, loader: 'js' }))
    },
  })
  // @withicons/motion's export.js reaches its 500-icon spec table (icons.js) only through motionFor(name); the exporters
  // always pass the spec, so the bundles get an empty table instead of ~220 KB of duplicate data
  const noSpecTable = {
    name: 'motion-no-spec-table', setup(b) {
      b.onResolve({ filter: /^\.\/icons\.js$/ }, a => /[\\/]motion[\\/]dist$/.test(a.resolveDir) ? { path: 'motion-icons-stub', namespace: 'stub' } : undefined)
      b.onLoad({ filter: /.*/, namespace: 'stub' }, () => ({ contents: 'export default {}', loader: 'js' }))
    },
  }
  const common = {
    bundle: true, platform: 'node', format: 'esm', target: 'node18', logLevel: 'silent', legalComments: 'none',
    define: { __VERSION__: JSON.stringify(version) },
    banner: { js: `import { createRequire as __cr } from 'node:module'; const require = __cr(import.meta.url);` },
  }
  const out = []
  const run = async (entry, outfile, data, extra = {}) => {
    const r = await esbuild.build({ ...common, external: ['@resvg/resvg-js'], ...extra, entryPoints: [path.join(mcpDir, 'src', entry)], outfile, plugins: [dataPlugin(data), noSpecTable], metafile: true })
    out.push(`${path.basename(outfile)} ${(fs.statSync(outfile).size / 1024).toFixed(0)} KB`)
    return r
  }
  await run('stdio.mjs', path.join(mcpDir, 'dist', 'stdio.mjs'), 'data-fs.mjs', { minify: true, banner: { js: `#!/usr/bin/env node\n${common.banner.js}` } })
  await run('lib.mjs', path.join(mcpDir, 'dist', 'lib.mjs'), 'data-fs.mjs')
  await run('lambda.mjs', path.join(mcpDir, 'dist', 'lambda.mjs'), 'data-inline.mjs', { minify: true })
  fs.copyFileSync(path.join(mcpDir, 'src', 'lib.d.ts'), path.join(mcpDir, 'dist', 'lib.d.ts'))
  const cliDir = path.join(root, 'packages', 'cli')
  if (fs.existsSync(path.join(cliDir, 'src', 'cli.mjs'))) {
    await esbuild.build({ ...common, entryPoints: [path.join(cliDir, 'src', 'cli.mjs')], outfile: path.join(cliDir, 'dist', 'cli.mjs'), external: ['@withicons/mcp', '@withicons/mcp/*', '@resvg/resvg-js'], plugins: [noSpecTable], banner: { js: '#!/usr/bin/env node' } })
    out.push(`cli.mjs ${(fs.statSync(path.join(cliDir, 'dist', 'cli.mjs')).size / 1024).toFixed(0)} KB`)
  }
  return out.join(', ')
}

const readme = (root, pkg, vars) => {
  // The template lives in src/, not the package root: npm always packs README* files whatever `files` says.
  const f = path.join(root, 'packages', pkg, 'src', 'readme.template.md')
  return fs.existsSync(f) ? fill(fs.readFileSync(f, 'utf8'), vars) : `# ${pkg}\n`
}

// Animation specs for the MCP server, HTTP API and CLI. Source of truth: @withicons/motion's generated
// dist/icons.js (forge/lib/emit-motion.mjs); falls back to the hand-authored forge/motion/*.json, then to nothing.
export async function motionData(root, iconNames) {
  const known = new Set(iconNames)
  const mdir = path.join(root, 'packages', 'motion')
  let icons = null, presets = null, effects = null, source = 'none'
  const dist = path.join(mdir, 'dist')
  try {
    if (fs.existsSync(path.join(dist, 'icons.js'))) {
      const m = await import(pathToFileURL(path.join(dist, 'icons.js')).href + `?t=${fs.statSync(path.join(dist, 'icons.js')).mtimeMs}`)
      const v = m.default || m.icons || m.MOTION || null
      if (v && typeof v === 'object') { icons = v; source = '@withicons/motion' }
    }
  } catch (e) { console.log(`  emit-mcp: packages/motion/dist/icons.js unreadable (${String(e.message).split('\n')[0]}), using forge/motion`) }
  try {
    // the closed vocabularies live in a DOM-free data module
    if (fs.existsSync(path.join(dist, 'meta.js'))) {
      const m = await import(pathToFileURL(path.join(dist, 'meta.js')).href + `?t=${fs.statSync(path.join(dist, 'meta.js')).mtimeMs}`)
      if (Array.isArray(m.PRESETS) && m.PRESETS.length) presets = [...m.PRESETS]
      if (Array.isArray(m.EFFECTS) && m.EFFECTS.length) effects = [...m.EFFECTS]
    }
  } catch { /* fall back to lib defaults */ }
  if (!icons) {
    const dir = path.join(root, 'forge', 'motion')
    if (fs.existsSync(dir)) {
      icons = {}
      for (const f of fs.readdirSync(dir).filter(f => f.endsWith('.json')).sort()) {
        try { const j = JSON.parse(fs.readFileSync(path.join(dir, f), 'utf8')); if (j && j.loop && j.hover) icons[f.slice(0, -5)] = j } catch { /* invalid spec: check-motion reports it */ }
      }
      source = Object.keys(icons).length ? 'forge/motion' : 'none'
    }
  }
  const out = {}
  for (const k of Object.keys(icons || {}).sort()) {
    if (!known.has(k)) continue
    const { name, ...spec } = icons[k] || {}
    out[k] = spec
  }
  // import paths follow the motion package's exports map when it exists
  let css = ['@withicons/motion/motion.css', '@withicons/motion/icons.css']
  try {
    const ex = JSON.parse(fs.readFileSync(path.join(mdir, 'package.json'), 'utf8')).exports || {}
    if (ex['./motion.css'] && ex['./icons.css']) css = ['@withicons/motion/motion.css', '@withicons/motion/icons.css']
  } catch { /* package not generated yet */ }
  // CDN: the presets + one small file per animated icon (dist/icons/<name>.css), not the all-icons icons.css
  const cdn = ['https://cdn.jsdelivr.net/npm/@withicons/motion@latest/dist/motion.css'], cdnIcon = 'https://cdn.jsdelivr.net/npm/@withicons/motion@latest/dist/icons/<name>.css'
  return { source, presets, effects, css, cdn, cdnIcon, icons: out }
}

// Per-icon colour palettes for the MCP server, HTTP API and CLI. Source: @withicons/core's generated dist/palettes/**
// (forge/lib/emit-palettes.mjs, from the hand-picked forge/palettes/<name>.json). Compact on disk:
//   { roles, roleLabels, tags, icons: { <name>: { auto, p: [[id, name, tags, [hex x roles]], ...] } } }
export function palettesData(root, iconNames) {
  const dir = path.join(root, 'packages', 'core', 'dist', 'palettes')
  const out = { roles: [], roleLabels: {}, tags: [], icons: {} }
  const idx = path.join(dir, 'index.json')
  if (!fs.existsSync(idx)) return out
  try {
    const j = JSON.parse(fs.readFileSync(idx, 'utf8'))
    out.roles = j.roles || []; out.roleLabels = j.roleLabels || {}; out.tags = j.tags || []
  } catch { return out }
  for (const name of iconNames) {
    const f = path.join(dir, name + '.json')
    if (!fs.existsSync(f)) continue
    try {
      const j = JSON.parse(fs.readFileSync(f, 'utf8'))
      const p = (j.palettes || []).filter(x => x && x.id && x.colors).map(x => [x.id, x.name || x.id, x.tags || [], out.roles.map(r => x.colors[r] || '')])
      if (p.length) out.icons[name] = { auto: !!j.auto, p }
    } catch { /* half-written file: skipped */ }
  }
  return out
}

export default async function emit(ctx) {
  const root = ctx.root || ROOT
  const version = ctx.version || '0.1.0'
  const P = 'packages/mcp/dist/data'
  // meta + search index + per-style SVG maps
  const idxFile = path.join(root, 'packages', 'search', 'dist', 'index.json')
  if (!fs.existsSync(idxFile)) throw new Error('packages/search/dist/index.json missing (emit-search must run first)')
  const index = fs.readFileSync(idxFile, 'utf8')
  const cats = new Map()
  for (const ic of ctx.icons) cats.set(ic.category, (cats.get(ic.category) || 0) + 1)
  const meta = {
    version,
    // static: the package with the style's standalone files when it is not @withicons/static (static-plus)
    styles: ctx.styles.map(s => ({ name: s.name, title: s.title, kind: s.kind, description: s.description, ...(s.palette ? { palette: true, vars: s.vars || {} } : {}), ...(cdnPkg(s.name, 'static') !== 'static' ? { static: cdnPkg(s.name, 'static') } : {}) })),
    categories: [...cats].sort((a, b) => a[0] < b[0] ? -1 : 1).map(([name, count]) => ({ name, count })),
    icons: ctx.icons.map(ic => ({ name: ic.name, category: ic.category, description: ic.description, aliases: ic.aliases, tags: ic.tags })),
  }
  ctx.write(`${P}/meta.json`, JSON.stringify(meta))
  ctx.write(`${P}/search-index.json`, index)
  const motion = await motionData(root, ctx.icons.map(i => i.name))
  ctx.write(`${P}/motion.json`, JSON.stringify(motion))
  const palettes = palettesData(root, ctx.icons.map(i => i.name))
  ctx.write(`${P}/palettes.json`, JSON.stringify(palettes))
  let svgBytes = 0
  for (const s of ctx.styles) {
    const map = {}
    for (const ic of ctx.icons) if (ic.render[s.name]) map[ic.name] = ic.render[s.name].svg
    const txt = JSON.stringify(map)
    svgBytes += txt.length
    ctx.write(`${P}/svg-${s.name}.json`, txt)
  }

  const rv = { version, icons: ctx.icons.length, styles: ctx.styles.length, styleList: ctx.styles.map(s => s.name).join(', '), total: totalText(ctx), animated: Object.keys(motion.icons).length, paletteIcons: Object.keys(palettes.icons).length }
  // package.json files (bundled -> no runtime dependencies)
  const mcpPkg = {
    ...basePkg(ctx, '@withicons/mcp', `MCP server for with icons: search ${countText(ctx)} in plain English and get paste-ready SVG, React, Vue, Svelte, Angular, Solid, web-component or class code, every icon's colour palettes for the multi-colour styles, animation code (@withicons/motion), and files (SVG, PNG, PDF, PowerPoint, Lottie, animated GIF / APNG / PowerPoint for slides). stdio (npx), plus a hosted server at https://withicons.com/mcp.`,
      ['mcp', 'model-context-protocol', 'mcp-server', 'ai', 'claude', 'cursor', 'icon-search', 'svg-icons', 'animated-icons', 'icon-animation',
        'multicolor-icons', 'color-palettes', 'animated-gif', 'powerpoint', ...ctx.styles.map(s => `${s.name}-icons`)]),
    type: 'module',
    bin: { 'withicons-mcp': 'dist/stdio.mjs' },
    main: './dist/lib.mjs',
    types: './dist/lib.d.ts',
    exports: {
      '.': { types: './dist/lib.d.ts', default: './dist/lib.mjs' },
      './lib': { types: './dist/lib.d.ts', default: './dist/lib.mjs' },
      './stdio': './dist/stdio.mjs',
      './data/*': './dist/data/*',
      './package.json': './package.json',
    },
    // dist/lambda.mjs (the site's API; reads dist/data/svg-*.json at run time) is deployed by scripts/deploy.mjs, not shipped on npm
    files: ['dist', '!dist/lambda.mjs', 'README.md', 'LICENSE'],
    // the bin runs code on import; the library does not
    sideEffects: ['./dist/stdio.mjs'],
    publishConfig: { access: 'public' },
    engines: { node: '>=18' },
    // PNG / animated files from export_icon (stdio); everything else works without it
    optionalDependencies: { '@resvg/resvg-js': '^2.6.2' },
    scripts: { build: 'node ../../forge/lib/emit-mcp.mjs', test: 'node --test test/*.test.mjs' },
    devDependencies: { '@modelcontextprotocol/sdk': '^1.31.0', esbuild: '^0.28.2', zod: '^4.6.5' },
  }
  // keep whatever versions were actually installed
  try {
    const cur = JSON.parse(fs.readFileSync(path.join(root, 'packages', 'mcp', 'package.json'), 'utf8'))
    if (cur.devDependencies) mcpPkg.devDependencies = cur.devDependencies
  } catch {}
  writePkg(ctx, 'mcp', mcpPkg, readme(root, 'mcp', rv))

  const cliPkg = {
    ...basePkg(ctx, 'withicons', `with icons from the terminal: search ${countText(ctx)} in plain English, print SVG, framework or animation code, export files (SVG, PDF, EPS, PNG, ICO, favicon pack, Android, iOS, React, Vue, Svelte, PowerPoint, Word, Lottie, animated GIF / APNG / SVG / PowerPoint) for apps, slides and CI, and add the with icons skill + MCP server to Claude Code, Codex, Cursor, OpenCode or VS Code in one command: npx withicons init.`,
      ['cli', 'icon-search', 'mcp', 'icon-export', 'favicon', 'lottie', 'svg-to-png', 'vectordrawable', 'animated-gif', 'apng', 'powerpoint']),
    type: 'module',
    bin: { withicons: 'dist/cli.mjs' },
    files: ['dist', 'README.md', 'LICENSE'],
    engines: { node: '>=18' },
    dependencies: { '@withicons/mcp': version },
    // PNG rendering for `withicons export --format png|png-set|ico|favicon-pack|pptx|pptx-sheet|docx|gif|apng|pptx-animated`; every other
    // command and format works without it (prebuilt native binaries: skipped quietly where none exists)
    optionalDependencies: { '@resvg/resvg-js': '^2.6.2' },
    scripts: { test: 'node --test test/*.test.mjs' },
  }
  cliPkg.repository.directory = 'packages/cli'
  writePkg(ctx, 'cli', cliPkg, readme(root, 'cli', rv))

  const b = await bundle({ root, version, styles: ctx.styles.map(s => s.name) })
  const np = Object.values(palettes.icons).reduce((n, x) => n + x.p.length, 0)
  return `data ${(svgBytes / 1024 / 1024).toFixed(1)} MB svg + meta; motion: ${Object.keys(motion.icons).length} icons from ${motion.source}; palettes: ${np} for ${Object.keys(palettes.icons).length} icons; ${b}`
}

// standalone: node forge/lib/emit-mcp.mjs  -> re-bundles only (data must already exist)
if (process.argv[1] && pathToFileURL(path.resolve(process.argv[1])).href === import.meta.url) {
  const meta = JSON.parse(fs.readFileSync(path.join(ROOT, 'packages', 'mcp', 'dist', 'data', 'meta.json'), 'utf8'))
  const mf = path.join(ROOT, 'packages', 'mcp', 'dist', 'data', 'motion.json')
  if (!fs.existsSync(mf)) fs.writeFileSync(mf, JSON.stringify(await motionData(ROOT, meta.icons.map(i => i.name))))
  // palettes are cheap to refresh from @withicons/core's dist
  fs.writeFileSync(path.join(ROOT, 'packages', 'mcp', 'dist', 'data', 'palettes.json'), JSON.stringify(palettesData(ROOT, meta.icons.map(i => i.name))))
  console.log(await bundle({ root: ROOT, version: meta.version, styles: meta.styles.map(s => s.name) }))
}
