// Shared test setup: dist/ is generated by forge/lib/emit-dynamic.mjs (gitignored); build it when missing.
import fs from 'node:fs'
import path from 'node:path'
import { spawnSync } from 'node:child_process'
import { fileURLToPath, pathToFileURL } from 'node:url'

export const here = path.dirname(fileURLToPath(import.meta.url))
export const pkgDir = path.join(here, '..')
export const dist = path.join(pkgDir, 'dist')
export const repo = path.join(pkgDir, '..', '..')
const emitter = path.join(repo, 'forge', 'lib', 'emit-dynamic.mjs')

// node --test runs files in parallel processes: one builds (holding a lock file), the others wait for it
const ready = () => fs.existsSync(path.join(dist, 'index.js')) && fs.existsSync(path.join(dist, 'cdn', 'dynamic.js'))
if (!ready()) {
  if (!fs.existsSync(emitter)) throw new Error('dist/ missing and the generator is not available')
  const lock = path.join(pkgDir, '.build.lock')
  let fd = null
  try { fd = fs.openSync(lock, 'wx') } catch { /* someone else is building */ }
  if (fd !== null) {
    try {
      const r = spawnSync(process.execPath, [emitter, '--no-site', '--quiet'], { cwd: repo, encoding: 'utf8' })
      if (r.status) throw new Error('emit-dynamic failed: ' + (r.stderr || r.stdout))
    } finally { fs.closeSync(fd); fs.rmSync(lock, { force: true }) }
  } else {
    const t = Date.now()
    while (fs.existsSync(lock) && Date.now() - t < 600000) await new Promise(r => setTimeout(r, 250))
    if (!ready()) throw new Error('dist/ was not built')
  }
}
export const read = f => fs.readFileSync(path.join(dist, f), 'utf8')
export const load = f => import(pathToFileURL(path.join(dist, f)).href)
export const exists = f => fs.existsSync(path.join(dist, f))

// A small well-formedness check for the SVG we emit (self-closed children only, or <g>/<defs> groups).
export function svgProblems(svg) {
  const out = []
  if (!/^<svg [^>]*xmlns="http:\/\/www\.w3\.org\/2000\/svg"/.test(svg)) out.push('does not start with <svg xmlns>')
  if (!svg.endsWith('</svg>')) out.push('does not end with </svg>')
  if (/\b(NaN|undefined|Infinity|\[object Object\])\b/.test(svg)) out.push('NaN/undefined/Infinity/object in output')
  if (/="[^"]*</.test(svg)) out.push('unescaped < in an attribute')
  const stack = []
  for (const m of svg.matchAll(/<(\/?)([a-zA-Z][\w:-]*)((?:\s+[\w:-]+="[^"]*")*)\s*(\/?)>/g)) {
    const [, close, tag, , self] = m
    if (close) { if (stack.pop() !== tag) { out.push(`mismatched </${tag}>`); break } }
    else if (!self) stack.push(tag)
  }
  if (stack.length) out.push('unclosed: ' + stack.join(','))
  const stripped = svg.replace(/<(\/?)([a-zA-Z][\w:-]*)((?:\s+[\w:-]+="[^"]*")*)\s*(\/?)>/g, '')
  if (stripped.trim()) out.push('stray text: ' + stripped.trim().slice(0, 40))
  const draw = (svg.match(/<(path|circle|rect|ellipse|polygon|polyline|line|use)\b/g) || []).length
  if (!draw) out.push('nothing drawn')
  return out
}
