// @withicons/web from a CDN: what a page downloads must be only what it shows.
// dist/ is generated by forge/lib/emit-web.mjs (node forge/build.mjs web --no-site). The icon classes are @withicons/classes.
import { test } from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

const dist = path.join(path.dirname(fileURLToPath(import.meta.url)), '..', 'dist')
const has = f => fs.existsSync(path.join(dist, f))
const size = f => fs.statSync(path.join(dist, f)).size
const skip = !has('cdn.js') && 'dist/ not built (node forge/build.mjs web --no-site)'
const meta = skip ? null : (await import(pathToFileURL(path.join(dist, 'data/meta.js')).href)).default
const styles = skip ? [] : (await import(pathToFileURL(path.join(dist, 'cdn.js')).href)).styleNames

test('one file per icon and style, small entry, no file a CDN would refuse', { skip }, () => {
  for (const s of styles) for (const n of meta.names) assert.ok(has(`icons/${s}/${n}.js`), `icons/${s}/${n}.js`)
  assert.ok(size('cdn.js') < 32 * 1024, 'cdn.js stays a few KB: ' + size('cdn.js'))
  assert.ok(size('full.js') < 64 * 1024, 'full.js imports the chunks instead of inlining 27 MB')
  // jsDelivr serves files up to 20 MB
  const walk = d => fs.readdirSync(d, { withFileTypes: true }).flatMap(e => e.isDirectory() ? walk(path.join(d, e.name)) : [path.join(d, e.name)])
  const big = walk(dist).filter(f => fs.statSync(f).size > 20 * 1024 * 1024)
  assert.deepEqual(big, [])
})

test('cdn.js renders from per-icon files; aliases use a small shard; typos suggest', { skip }, async () => {
  const cdn = await import(pathToFileURL(path.join(dist, 'cdn.js')).href)
  const full = await import(pathToFileURL(path.join(dist, 'full.js')).href)
  for (const v of ['line', 'luxe']) assert.equal(await cdn.loadSvg('home', { variant: v }), full.svg('home', { variant: v }))
  const alias = Object.keys(meta.aliases).find(a => meta.aliases[a].length === 1)
  assert.equal(await cdn.loadSvg(alias), full.svg(meta.aliases[alias][0]))
  await assert.rejects(cdn.loadSvg('hoem'), e => e.code === 'WITH_UNKNOWN_ICON' && e.suggestions.includes('home'))
})

test('index.js: chunks when bundled or in Node, per-icon files after setIconBase()', { skip }, async () => {
  const idx = await import(pathToFileURL(path.join(dist, 'index.js')).href + '?t=1')
  const full = await import(pathToFileURL(path.join(dist, 'full.js')).href)
  assert.equal(await idx.loadSvg('search', { variant: 'duo' }), full.svg('search', { variant: 'duo' }))
  idx.setIconBase(pathToFileURL(dist).href)
  assert.equal(await idx.loadSvg('heart', { variant: 'gothic' }), full.svg('heart', { variant: 'gothic' }))
  const src = fs.readFileSync(path.join(dist, 'index.js'), 'utf8')
  assert.match(src, /webpackIgnore: true/, 'the computed per-icon import is invisible to bundlers')
})

test('no icon classes here: they ship as @withicons/classes', { skip }, () => {
  assert.ok(!has('classes'), 'dist/classes belongs to packages/classes')
})
