// Generated by forge/lib/emit-mcp.mjs — data inlined into dist/lambda.mjs so the function is one self-contained file.
// SVG maps are inlined as JSON *strings* and parsed per style on first use: a fast cold start even with every style inlined.
// Palettes (one string too) are parsed on the first palette request.
import meta from '../dist/data/meta.json'
import index from '../dist/data/search-index.json'
import motion from '../dist/data/motion.json'
import palettesRaw from '../dist/data/palettes.json?text'
import s0 from '../dist/data/svg-line.json?text'
import s1 from '../dist/data/svg-solid.json?text'
import s2 from '../dist/data/svg-duo.json?text'
import s3 from '../dist/data/svg-gloss.json?text'
import s4 from '../dist/data/svg-engrave.json?text'
import s5 from '../dist/data/svg-blueprint.json?text'
import s6 from '../dist/data/svg-sketch.json?text'
import s7 from '../dist/data/svg-glass.json?text'
import s8 from '../dist/data/svg-kawaii.json?text'
import s9 from '../dist/data/svg-sticker.json?text'
import s10 from '../dist/data/svg-pixel.json?text'
import s11 from '../dist/data/svg-retro.json?text'
import s12 from '../dist/data/svg-luxe.json?text'
import s13 from '../dist/data/svg-bauhaus.json?text'
import s14 from '../dist/data/svg-skeuo.json?text'
import s15 from '../dist/data/svg-anime.json?text'
import s16 from '../dist/data/svg-gothic.json?text'
import s17 from '../dist/data/svg-pastel.json?text'
import s18 from '../dist/data/svg-coquette.json?text'
import s19 from '../dist/data/svg-plush.json?text'

const raw = { "line": s0, "solid": s1, "duo": s2, "gloss": s3, "engrave": s4, "blueprint": s5, "sketch": s6, "glass": s7, "kawaii": s8, "sticker": s9, "pixel": s10, "retro": s11, "luxe": s12, "bauhaus": s13, "skeuo": s14, "anime": s15, "gothic": s16, "pastel": s17, "coquette": s18, "plush": s19 }
const svgs = {}
let palettes = null
export function loadData() {
  return {
    meta, index, motion,
    svg: style => svgs[style] || (svgs[style] = raw[style] ? JSON.parse(raw[style]) : {}),
    palettes: () => palettes || (palettes = JSON.parse(palettesRaw)),
  }
}
