// Generated by forge/lib/emit-mcp.mjs — the data layer of dist/lambda.mjs (the API Lambda; scripts/deploy.mjs zips it).
// Small data (meta, search index, motion specs) is inlined as JSON strings (JSON.parse is faster than parsing a JS object
// literal). The big data stays OUT of the bundle, so a cold start compiles ~1.8 MB of JS instead of ~33 MB: each style's
// SVG map (data/svg-<style>.json) and the palettes (data/palettes.json) sit next to lambda.mjs in the zip (mcp/data/).
// One icon's SVG (or palette list) is read on demand at a byte range precomputed at build time, so answering for one icon
// never parses a 1-4 MB file; values are cached. A file without ranges falls back to one whole-file read + parse.
import fs from 'node:fs'
import metaRaw from '../dist/data/meta.json?text'
import indexRaw from '../dist/data/search-index.json?text'
import motionRaw from '../dist/data/motion.json?text'
import { multiRaw, rangesRaw } from '#lambda-index'

const STYLES = new Set(["line","solid","duo","gloss","engrave","blueprint","sketch","glass","kawaii","sticker","pixel","retro","luxe","bauhaus","skeuo","anime","gothic","pastel","coquette","plush","clay","bento","suite","dock","liquid","chrome","soft3d","brutal","utsav","rangoli","halloween","christmas","lunar","valentine"])
const url = f => new URL('./data/' + f, import.meta.url)
const read = f => JSON.parse(fs.readFileSync(url(f), 'utf8'))
const svgs = {}
let palettes = null, multi = null, ranges = null
// { <icon>: value } read lazily from one file: spec = "start,length,..." in meta.icons order (-1 = no value for that icon)
function lazyMap(f, spec, names) {
  const nums = spec.split(',').map(Number), map = {}, file = url(f)
  let fd = null
  names.forEach((name, i) => {
    const start = nums[2 * i], len = nums[2 * i + 1]
    if (start < 0) return
    let v
    Object.defineProperty(map, name, { enumerable: true, get() {
      if (v === undefined) { if (fd === null) fd = fs.openSync(file, 'r'); const b = Buffer.allocUnsafe(len); fs.readSync(fd, b, 0, len, start); v = JSON.parse(b.toString('utf8')) }
      return v
    } })
  })
  return map
}
export function loadData() {
  const meta = JSON.parse(metaRaw), names = meta.icons.map(i => i.name)
  const R = () => ranges || (ranges = JSON.parse(rangesRaw))
  return {
    meta, index: JSON.parse(indexRaw), motion: JSON.parse(motionRaw),
    svg: style => svgs[style] || (svgs[style] = !STYLES.has(style) ? {} : R().svg[style] ? lazyMap('svg-' + style + '.json', R().svg[style], names) : read('svg-' + style + '.json')),
    palettes: () => palettes || (palettes = R().palettes ? { ...R().palettes.head, icons: lazyMap('palettes.json', R().palettes.icons, names) } : read('palettes.json')),
    // name -> styles whose SVG uses a --with-* colour variable (precomputed at build: no need to read all 20 style files)
    multiColour: name => { const m = multi || (multi = JSON.parse(multiRaw)); return Object.hasOwn(m, name) ? [...m[name]] : [] },
  }
}
