#!/usr/bin/env node
// Regenerates the agent-skill name list and the website copy of the skill.
//   skills/with-icons/reference/icons.md    <- forge/icons/*.json (name, category, aliases)
//   skills/with-icons/reference/styles.md   <- the block between <!-- palettes:start/end --> (palette variables, from
//                                              packages/core/dist/styles.json written by the build)
//   skills/with-icons/reference/motion.md   <- the block between <!-- motion:start/end --> (animated icons, from forge/motion/*.json)
//   skills/with-icons/reference/live.md     <- the block between <!-- live:start/end --> (live icons + params, from forge/dynamic/*.mjs)
//   site/skill/SKILL.md                     <- skills/with-icons/SKILL.md (relative links -> GitHub URLs)
// Run after adding/renaming icons or editing aliases (scripts/deploy.mjs runs it after the build).
//   node scripts/skill-sync.mjs [--check]   --check: exit 1 if any file is out of date (CI)
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'
import { styleRank } from '../forge/lib/emit-core.mjs'

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const SKILL = path.join(ROOT, 'skills', 'with-icons')
const GH = 'https://github.com/withevergrow/withicons/blob/main/skills/with-icons/'
const check = process.argv.includes('--check')
const read = f => (fs.existsSync(f) ? fs.readFileSync(f, 'utf8').replace(/\r\n/g, '\n') : null)

const dir = path.join(ROOT, 'forge', 'icons')
const icons = fs.readdirSync(dir).filter(f => f.endsWith('.json')).sort()
  .map(f => ({ name: f.slice(0, -5), ...JSON.parse(fs.readFileSync(path.join(dir, f), 'utf8')) }))
const manifest = JSON.parse(fs.readFileSync(path.join(ROOT, 'forge', 'manifest.json'), 'utf8'))
const order = [...(manifest.categories || [])]
for (const i of icons) if (i.category && !order.includes(i.category)) order.push(i.category)
const pascal = n => n.split('-').map(w => w[0].toUpperCase() + w.slice(1)).join('')

// styles: the build's metadata when present, else the renderer files (in the same order as the build)
const rank = styleRank
const builtStyles = (() => { try { return JSON.parse(read(path.join(ROOT, 'packages', 'core', 'dist', 'styles.json'))) } catch { return null } })()
const styles = builtStyles || fs.readdirSync(path.join(ROOT, 'forge', 'styles')).filter(f => f.endsWith('.mjs') && !f.startsWith('_'))
  .map(f => ({ name: f.slice(0, -4) })).sort((a, b) => rank(a.name) - rank(b.name) || (a.name < b.name ? -1 : 1))

let md = `# with icons: all ${icons.length} icon names\n\n` +
  `Generated by \`scripts/skill-sync.mjs\` from \`forge/icons/*.json\`. Do not edit by hand.\n` +
  `Use the **name** (kebab-case) in name-based APIs and the **component** in imports. Aliases resolve in name-based APIs\n` +
  `and search only, and are never exports. Every icon exists in all ${styles.length} styles (${styles.map(s => s.name).join(', ')}).\n\n`
for (const cat of order) {
  const list = icons.filter(i => i.category === cat)
  if (!list.length) continue
  md += `## ${cat} (${list.length})\n\n| name | component | aliases |\n|---|---|---|\n`
  for (const i of list) md += `| \`${i.name}\` | \`${pascal(i.name)}\` | ${(i.aliases || []).slice(0, 8).join(', ')} |\n`
  md += '\n'
}

// generated blocks inside hand-written reference files
const block = (text, key, body) => {
  const a = `<!-- ${key}:start -->`, b = `<!-- ${key}:end -->`
  const i = text.indexOf(a), j = text.indexOf(b)
  return i >= 0 && j > i ? text.slice(0, i + a.length) + '\n' + body + text.slice(j) : text
}
const pal = (builtStyles || []).filter(s => s.palette)
const palBody = pal.length
  ? `| style | CSS variables (default) |\n|---|---|\n` +
    pal.map(s => `| \`${s.name}\` | ${Object.entries(s.vars || {}).filter(([, v]) => v !== 'currentColor').map(([k, v]) => `\`${k}\` ${v}`).join(', ')} |`).join('\n') + '\n'
  : `_Run \`node forge/build.mjs\` to list the palette variables._\n`
const motionDir = path.join(ROOT, 'forge', 'motion')
const specs = fs.existsSync(motionDir) ? fs.readdirSync(motionDir).filter(f => f.endsWith('.json')).sort().map(f => {
  try { return { name: f.slice(0, -5), ...JSON.parse(fs.readFileSync(path.join(motionDir, f), 'utf8')) } } catch { return null }
}).filter(s => s && s.loop && s.hover) : []
const motionBody = `${specs.length} icons have a tuned animation (any icon can use any preset).\n\n| icon | loop | hover | swaps to | what it says |\n|---|---|---|---|---|\n` +
  specs.map(s => `| \`${s.name}\` | ${s.loop.preset} | ${s.hover.preset} | ${(s.swap || []).map(x => `\`${x.to}\``).join(', ')} | ${String(s.intent || '').replace(/\|/g, '/')} |`).join('\n') + '\n'

// live icons (@withicons/dynamic): name, what it shows, params (attribute, range or options, default)
const liveDir = path.join(ROOT, 'forge', 'dynamic')
const lives = []
if (fs.existsSync(liveDir)) for (const f of fs.readdirSync(liveDir).filter(f => f.endsWith('.mjs') && !f.startsWith('_')).sort()) {
  try { const g = (await import(pathToFileURL(path.join(liveDir, f)).href)).default; if (g && g.name && g.params) lives.push(g) }
  catch (e) { console.warn(`live icon ${f}: ${e.message}`) }
}
const cell = t => String(t == null ? '' : t).replace(/\s*—\s*/g, ': ').replace(/\|/g, '/').replace(/\s*\n\s*/g, ' ')
const kebab = k => k.replace(/[A-Z]/g, c => '-' + c.toLowerCase())
const paramText = (k, p) => {
  const t = p.type
  const range = t === 'int' || t === 'number' ? `${p.min} to ${p.max}${p.step ? `, step ${p.step}` : ''}`
    : t === 'enum' ? (p.options || []).join(' / ')
    : t === 'level' ? '0 to 1 (or "80%")'
    : t === 'text' ? `text, up to ${p.maxLength}${p.case === 'upper' ? ', uppercased' : ''}`
    : t === 'time' ? '"HH:MM"' : t === 'bool' ? 'true / false' : t
  // a param called `label` clashes with the accessible-name attribute: param-label on the element, params={{ label }} on LiveIcon
  const attr = k === 'label' ? 'param-label' : kebab(k)
  return `\`${attr}\` ${range} (${JSON.stringify(p.default)})${p.label ? ': ' + cell(p.label) : ''}`
}
const liveBody = `${lives.length} live icons. Params are kebab-case attributes on \`<with-live-icon>\` (as listed) and camelCase props on ` +
  `\`LiveIcon\` / keys for \`render()\`; the default is in brackets.\n\n| name | what it shows | params |\n|---|---|---|\n` +
  lives.map(g => `| \`${g.name}\` | ${cell(g.description || g.title)} | ${Object.entries(g.params).map(([k, p]) => paramText(k, p)).join('<br>')} |`).join('\n') + '\n'

// keep the counts in the hand-written skill text true: "500 icons", "12 styles", "6,000 icons"
const total = (icons.length * styles.length).toLocaleString('en-US')
const counts = text => text
  .replace(/\b\d,\d{3}(?= (?:icons|SVGs)\b)/g, total)
  .replace(/\b\d{3}(?= (?:MIT-licensed |open-source |canonical )?(?:icons|names|skeletons)\b)/g, String(icons.length))
  .replace(/\b(?:\d{1,2}|seven|twelve)(?= (?:visual )?styles\b)/g, String(styles.length))
  .replace(/(?<=in all )\d{1,2}(?= styles)/g, String(styles.length))

const stylesFile = path.join(SKILL, 'reference', 'styles.md'), motionFile = path.join(SKILL, 'reference', 'motion.md')
const liveFile = path.join(SKILL, 'reference', 'live.md')
const skill = counts(read(path.join(SKILL, 'SKILL.md')))
const siteCopy = skill.replace(/\]\((reference\/[^)]+)\)/g, (_, p) => `](${GH}${p})`)

const outputs = [[path.join(SKILL, 'SKILL.md'), skill], [path.join(SKILL, 'reference', 'icons.md'), md], [path.join(ROOT, 'site', 'skill', 'SKILL.md'), siteCopy]]
for (const f of ['search.md', 'frameworks.md', 'files.md', 'chat.md']) { const p = path.join(SKILL, 'reference', f); if (read(p)) outputs.push([p, counts(read(p))]) }
if (read(stylesFile)) outputs.push([stylesFile, block(counts(read(stylesFile)), 'palettes', palBody)])
if (read(motionFile)) outputs.push([motionFile, block(counts(read(motionFile)), 'motion', motionBody)])
if (read(liveFile)) outputs.push([liveFile, block(counts(read(liveFile)), 'live', liveBody)])
let stale = 0
for (const [file, text] of outputs) {
  const cur = read(file)
  if (cur === text) continue
  stale++
  if (check) console.log(`out of date: ${path.relative(ROOT, file)}`)
  else { fs.mkdirSync(path.dirname(file), { recursive: true }); fs.writeFileSync(file, text); console.log(`wrote ${path.relative(ROOT, file)}`) }
}
if (check && stale) { console.log('run: node scripts/skill-sync.mjs'); process.exit(1) }
if (!stale) console.log('skill files up to date')
