#!/usr/bin/env node
// Regenerates the agent-skill name list and the website copy of the skill.
//   skills/with-icons/reference/icons.md   <- forge/icons/*.json (name, category, aliases)
//   site/skill/SKILL.md                     <- skills/with-icons/SKILL.md (relative links -> GitHub URLs)
// Run after adding/renaming icons or editing aliases (scripts/deploy.mjs runs it after the build).
//   node scripts/skill-sync.mjs [--check]   --check: exit 1 if either file is out of date (CI)
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const SKILL = path.join(ROOT, 'skills', 'with-icons')
const GH = 'https://github.com/withevergrow/withicons/blob/main/skills/with-icons/'
const check = process.argv.includes('--check')

const dir = path.join(ROOT, 'forge', 'icons')
const icons = fs.readdirSync(dir).filter(f => f.endsWith('.json')).sort()
  .map(f => JSON.parse(fs.readFileSync(path.join(dir, f), 'utf8')))
const manifest = JSON.parse(fs.readFileSync(path.join(ROOT, 'forge', 'manifest.json'), 'utf8'))
const order = manifest.categories || [...new Set(icons.map(i => i.category))].sort()
const pascal = n => n.split('-').map(w => w[0].toUpperCase() + w.slice(1)).join('')

let md = `# with icons: all ${icons.length} icon names\n\n` +
  `Generated by \`scripts/skill-sync.mjs\` from \`forge/icons/*.json\`. Do not edit by hand.\n` +
  `Use the **name** (kebab-case) in name-based APIs and the **component** in imports. Aliases resolve in name-based APIs\n` +
  `and search only, and are never exports. Every icon exists in all 7 styles.\n\n`
for (const cat of order) {
  const list = icons.filter(i => i.category === cat)
  if (!list.length) continue
  md += `## ${cat} (${list.length})\n\n| name | component | aliases |\n|---|---|---|\n`
  for (const i of list) md += `| \`${i.name}\` | \`${pascal(i.name)}\` | ${(i.aliases || []).slice(0, 8).join(', ')} |\n`
  md += '\n'
}
const other = icons.filter(i => !order.includes(i.category))
if (other.length) md += `## other\n\n${other.map(i => `\`${i.name}\``).join(', ')}\n`

const skill = fs.readFileSync(path.join(SKILL, 'SKILL.md'), 'utf8')
const siteCopy = skill.replace(/\]\((reference\/[^)]+)\)/g, (_, p) => `](${GH}${p})`)

const outputs = [[path.join(SKILL, 'reference', 'icons.md'), md], [path.join(ROOT, 'site', 'skill', 'SKILL.md'), siteCopy]]
let stale = 0
for (const [file, text] of outputs) {
  const cur = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : null
  if (cur === text) continue
  stale++
  if (check) console.log(`out of date: ${path.relative(ROOT, file)}`)
  else { fs.mkdirSync(path.dirname(file), { recursive: true }); fs.writeFileSync(file, text); console.log(`wrote ${path.relative(ROOT, file)}`) }
}
if (check && stale) { console.log('run: node scripts/skill-sync.mjs'); process.exit(1) }
if (!stale) console.log('skill files up to date')
