// Guide content. Plain language first. UI labels in <b class="ui">, menu paths via P().
export const P = (...xs) => `<span class="ui-path">${xs.map(x => `<b>${x}</b>`).join('<i aria-hidden="true">›</i>')}</span>`
export const UI = x => `<b class="ui">${x}</b>`
export const K = (...ks) => ks.map(k => `<kbd>${k}</kbd>`).join('+')

// Shared first step: get the icon from the library.
const pickStep = (fmt, size, icon = 'home', extra = '') => ({
  t: 'Pick your icon and download it',
  d: `Open <a href="../icons.html">the icon library</a> and search for what you need, for example “${icon.replace(/-/g, ' ')}”. Click the icon, choose a colour, then click ${UI('Download ' + fmt)}${size ? ` and pick <b>${size}</b>` : ''}. ${extra}`,
  ui: { k: 'pick', fmt, size, icon },
})

export const GUIDES = [
  {
    slug: 'google-slides', app: 'Google Slides', group: 'slides', color: 'line', icon: 'monitor', time: 2,
    title: 'How to add icons to Google Slides',
    desc: 'Add free icons to Google Slides in four steps: download a transparent PNG, insert it, resize it and change its colour. Simple instructions with pictures.',
    short: `Download the icon as a <b>PNG at 512 px</b>, then in Slides choose ${P('Insert', 'Image', 'Upload from computer')}.`,
    format: { best: 'PNG', size: '512 px', why: 'Google Slides doesn’t accept SVG files, so use a PNG. 512 px stays sharp even when the icon fills half a slide. Going full-screen? Pick 1024 px.' },
    app_ui: 'slides',
    steps: [
      pickStep('PNG', '512 px', 'lightbulb', 'Our PNGs have a see-through background, so they sit nicely on any slide colour.'),
      { t: 'Insert it into your slide', d: `In Google Slides, click the slide you want, then open ${P('Insert', 'Image', 'Upload from computer')}. Choose the PNG you just downloaded.`, ui: { k: 'menu', bar: ['File', 'Edit', 'View', 'Insert', 'Format'], path: ['Insert', 'Image', 'Upload from computer'] } },
      { t: 'Or just drag it in', d: 'Faster: drag the file from your Downloads folder straight onto the slide. It lands where you drop it.', ui: { k: 'drop', file: 'lightbulb.png', icon: 'lightbulb' } },
      { t: 'Resize it', d: `Click the icon and drag a <b>corner</b> handle, not a side one, so it keeps its shape. For exact sizes use ${P('Format options', 'Size & Rotation')}.`, ui: { k: 'resize', icon: 'lightbulb' } },
      { t: 'Line it up', d: 'Drag it into place. Slides shows red guide lines when the icon is centred or lined up with other things on the slide.', ui: { k: 'done', icon: 'lightbulb' } },
    ],
    recolor: `The easy way: pick the colour on with icons <em>before</em> you download. Already in Slides? Select the icon and open ${P('Format options', 'Recolor')} for a few tinted versions that match your theme.`,
    resize: 'Always drag a corner handle. A 512 px PNG looks sharp up to about half a slide wide; use 1024 px for anything bigger.',
    trouble: [
      ['I can’t upload an SVG file.', 'Google Slides only takes images like PNG, JPG and GIF. Download the PNG version instead.'],
      ['The icon looks blurry.', 'It was stretched past its size. Delete it and download a bigger PNG (1024 px).'],
      ['There’s a white box behind the icon.', 'You probably used a screenshot or a JPG. Our PNG downloads are see-through; download the PNG again.'],
      ['My icon is black on a dark slide.', 'Download it again in white (or any light colour) from the colour picker in the library.'],
    ],
    related: ['powerpoint', 'keynote', 'canva'],
  },
  {
    slug: 'powerpoint', app: 'PowerPoint', group: 'slides', color: 'solid', icon: 'chart-bar', time: 2,
    title: 'How to add icons to PowerPoint',
    desc: 'Put free SVG icons in PowerPoint, change their colour with Graphics Fill and resize them without blur. Step-by-step for Windows, Mac and the web.',
    short: `Download the icon as an <b>SVG</b>, then choose ${P('Insert', 'Pictures', 'This Device')}. Recolour it with ${UI('Graphics Fill')}.`,
    format: { best: 'SVG', size: 'any size', why: 'PowerPoint in Microsoft 365, 2019 and newer understands SVG. It stays razor sharp at any size and you can recolour it inside PowerPoint. Using PowerPoint 2016 or older? Use a 512 px PNG.' },
    app_ui: 'slides',
    steps: [
      pickStep('SVG', '', 'rocket'),
      { t: 'Insert the picture', d: `In PowerPoint, go to ${P('Insert', 'Pictures', 'This Device')} on Windows, or ${P('Insert', 'Pictures', 'Picture from File')} on a Mac. Pick the SVG and click ${UI('Insert')}.`, ui: { k: 'menu', bar: ['File', 'Home', 'Insert', 'Design', 'View'], path: ['Insert', 'Pictures', 'This Device'] } },
      { t: 'Change its colour', d: `With the icon selected, open the ${UI('Graphics Format')} tab and choose ${UI('Graphics Fill')}. If a line icon doesn’t change, try ${UI('Graphics Outline')} too.`, ui: { k: 'recolor', icon: 'rocket', label: 'Graphics Fill' } },
      { t: 'Resize it', d: `Drag a corner handle, or type an exact Height in the ${UI('Graphics Format')} tab. An SVG never goes blurry, however big you make it.`, ui: { k: 'resize', icon: 'rocket' } },
      { t: 'Done — reuse it', d: 'Copy and paste the icon to other slides. It keeps its colour and size.', ui: { k: 'done', icon: 'rocket' } },
    ],
    recolor: `Select the icon, then ${P('Graphics Format', 'Graphics Fill')}. For full control, choose ${UI('Convert to Shape')} on the same tab: the icon becomes normal shapes you can colour piece by piece with ${UI('Shape Fill')} and ${UI('Shape Outline')}.`,
    resize: `Drag a corner handle. To match sizes across slides, type the same Height and Width in the ${UI('Graphics Format')} tab.`,
    trouble: [
      ['PowerPoint won’t open the SVG.', 'Older versions (2016 and before) can’t read SVG. Download a 512 px PNG instead.'],
      ['The colour won’t change.', `Try ${UI('Graphics Outline')} as well as ${UI('Graphics Fill')}, or use ${UI('Convert to Shape')} and colour the shapes.`],
      ['The lines look thin when the icon is huge.', 'That’s normal for line icons. Try the Solid style for big, bold icons on title slides.'],
      ['I want the same icon in many colours.', 'Insert it once, then copy and paste it and change the fill of each copy.'],
    ],
    related: ['google-slides', 'keynote', 'word-google-docs'],
  },
  {
    slug: 'keynote', app: 'Keynote', group: 'slides', color: 'duo', icon: 'tv', time: 2,
    title: 'How to add icons to Keynote',
    desc: 'Add free icons to Apple Keynote: download a PNG or SVG, drag it onto your slide, resize it and pick the right colour. Simple steps for Mac and iPad.',
    short: 'Download a <b>PNG at 1024 px</b> in the colour you want and drag it onto your slide.',
    format: { best: 'PNG', size: '1024 px', why: 'A big transparent PNG works in every version of Keynote, on Mac and iPad. Newer versions of Keynote can also place SVG files, which stay sharp at any size, so try the SVG first if you’re up to date.' },
    app_ui: 'slides',
    steps: [
      pickStep('PNG', '1024 px', 'trophy', 'Pick the colour now: changing the colour of a PNG inside Keynote is fiddly.'),
      { t: 'Drag it onto the slide', d: 'Drag the file from Finder (or the Downloads stack in your Dock) onto your slide.', ui: { k: 'drop', file: 'trophy.png', icon: 'trophy' } },
      { t: 'Or use the menu', d: `On a Mac you can also use ${P('Insert', 'Choose…')} in the menu bar and pick the file.`, ui: { k: 'menu', bar: ['Keynote', 'File', 'Edit', 'Insert', 'Format'], path: ['Insert', 'Choose…'] } },
      { t: 'Resize and place it', d: `Drag a corner handle. For an exact size, open the ${UI('Format')} sidebar, go to ${UI('Arrange')} and type a width; keep ${UI('Constrain proportions')} ticked.`, ui: { k: 'resize', icon: 'trophy' } },
      { t: 'Present!', d: 'Keynote’s yellow guides help you centre it. Add a Build In animation if you want the icon to pop in.', ui: { k: 'done', icon: 'trophy' } },
    ],
    recolor: 'Pick the colour on with icons before downloading; it’s the quickest and cleanest way. Need a new colour later? Just download the icon again in that colour and drag it over the old one.',
    resize: `Drag a corner handle, or set the width in ${P('Format', 'Arrange')}. A 1024 px PNG stays crisp even when it fills the slide.`,
    trouble: [
      ['The icon has a white background.', 'Make sure you downloaded the PNG, not a screenshot. Our PNGs are see-through.'],
      ['It looks a little soft on a big screen.', 'Download it again at 1024 px, or try the SVG if your Keynote accepts it.'],
      ['I need a white icon for a dark theme.', 'Choose white in the library’s colour picker before you download.'],
    ],
    related: ['powerpoint', 'google-slides', 'canva'],
  },
  {
    slug: 'canva', app: 'Canva', group: 'design', color: 'gloss', icon: 'palette', time: 2,
    title: 'How to add icons to Canva',
    desc: 'Upload free SVG icons to Canva, change their colour right in the editor and resize them without blur. Easy steps with pictures.',
    short: `Download an <b>SVG</b>, then in Canva open ${P('Uploads', 'Upload files')}. Click the icon to add it and change its colour from the toolbar.`,
    format: { best: 'SVG', size: 'any size', why: 'Canva accepts SVG uploads and lets you change their colour inside Canva. SVGs stay sharp on posters and print too.' },
    app_ui: 'design',
    steps: [
      pickStep('SVG', '', 'heart'),
      { t: 'Upload it to Canva', d: `In the Canva editor, click ${UI('Uploads')} in the left panel, then ${UI('Upload files')}, and choose the SVG.`, ui: { k: 'side', tab: 'Uploads', button: 'Upload files' } },
      { t: 'Add it to your design', d: 'Click the uploaded icon (or drag it onto the page). It appears in the middle of your design.', ui: { k: 'place', icon: 'heart' } },
      { t: 'Change the colour', d: 'With the icon selected, click the coloured square in the toolbar at the top and pick any colour, including your Brand Kit colours.', ui: { k: 'recolor', icon: 'heart', label: 'Colour' } },
      { t: 'Resize and place it', d: 'Drag a corner handle to resize. Canva shows pink guide lines to help you line it up.', ui: { k: 'resize', icon: 'heart' } },
    ],
    recolor: 'Select the icon and click the colour square in the top toolbar. If there’s no colour square, you uploaded a PNG; upload the SVG instead.',
    resize: 'Drag a corner. Because it’s an SVG, it stays sharp at any size, even on a printed poster.',
    trouble: [
      ['There’s no colour option.', 'That happens with PNG files. Upload the SVG version to recolour inside Canva.'],
      ['The upload failed.', 'Try again, or download a 1024 px PNG in the colour you want and upload that.'],
      ['The icon looks too thin on a poster.', 'Switch to the Solid or Gloss style for bold, eye-catching shapes.'],
    ],
    related: ['figma', 'google-slides', 'email-signatures'],
  },
  {
    slug: 'figma', app: 'Figma', group: 'design', color: 'engrave', icon: 'pen-tool', time: 1,
    title: 'How to use icons in Figma',
    desc: 'Paste free icons into Figma as editable vectors, recolour strokes and fills, and scale them the right way. Quick steps for designers.',
    short: `Click ${UI('Copy SVG')} on any icon, then press ${K('Ctrl', 'V')} (${K('⌘', 'V')} on Mac) on your Figma canvas. It pastes as an editable vector.`,
    format: { best: 'SVG', size: 'copy & paste', why: 'Figma turns pasted SVG code into real vector layers, so there’s nothing to download. You can also drag an .svg file in.' },
    app_ui: 'design',
    steps: [
      { t: 'Copy the icon', d: `Open <a href="../icons.html">the library</a>, click an icon and press ${UI('Copy SVG')}.`, ui: { k: 'pick', fmt: 'Copy SVG', icon: 'sparkles' } },
      { t: 'Paste it into Figma', d: `Click your canvas or a frame and press ${K('Ctrl', 'V')} (${K('⌘', 'V')} on Mac). The icon arrives as a vector group, 24 × 24.`, ui: { k: 'paste', icon: 'sparkles' } },
      { t: 'Recolour it', d: `Select the vector layers inside the group. In the right panel, change the ${UI('Stroke')} colour for Line icons, or the ${UI('Fill')} colour for Solid ones.`, ui: { k: 'recolor', icon: 'sparkles', label: 'Stroke' } },
      { t: 'Scale it the right way', d: `Press ${K('K')} for the Scale tool and drag a corner. This scales the line thickness too, so the icon keeps its look at 48 or 96 px.`, ui: { k: 'resize', icon: 'sparkles' } },
      { t: 'Make it a component', d: `Turn the icon into a component (${K('Ctrl', 'Alt', 'K')} / ${K('⌘', '⌥', 'K')}) so you can reuse it everywhere and swap it later.`, ui: { k: 'done', icon: 'sparkles' } },
    ],
    recolor: `Select the vector layers and change the ${UI('Stroke')} (line icons) or ${UI('Fill')} (solid icons) in the right panel. Duo icons have a soft fill layer you can tint separately.`,
    resize: `Use the Scale tool (${K('K')}) so line thickness scales with the icon. Resizing with plain handles keeps strokes at 1.75 px, which looks thin when big. Want strokes turned into shapes? Use Figma’s ${UI('Outline stroke')} command.`,
    trouble: [
      ['Pasting gave me an image, not a vector.', 'You copied a PNG. Use the Copy SVG button, then paste again.'],
      ['Lines look thin at large sizes.', `Resize with the Scale tool (${K('K')}) instead of the handles.`],
      ['Colours look different in my export.', 'Check you changed the colour on the vector layers inside the group, not just the frame.'],
    ],
    related: ['canva', 'framer', 'webflow'],
  },
  {
    slug: 'word-google-docs', app: 'Google Docs & Word', group: 'docs', color: 'blueprint', icon: 'file-text', time: 2,
    title: 'How to add icons to Google Docs and Microsoft Word',
    desc: 'Put free icons in Google Docs and Microsoft Word: the right file to download, how to insert it, keep it in line with your text, resize and recolour it.',
    short: `Google Docs: ${P('Insert', 'Image', 'Upload from computer')} with a <b>PNG</b>. Word: ${P('Insert', 'Pictures', 'This Device')} with an <b>SVG</b>.`,
    format: { best: 'PNG / SVG', size: '256 px PNG', why: 'Google Docs needs a PNG (256 px is plenty for icons next to text). Word in Microsoft 365 and 2019+ takes SVG, which stays sharp and can be recoloured.' },
    app_ui: 'doc',
    steps: [
      pickStep('PNG', '256 px', 'check-circle', 'Using Word? Download the SVG instead.'),
      { t: 'Google Docs: insert the image', d: `Put your cursor where the icon should go, then choose ${P('Insert', 'Image', 'Upload from computer')}.`, ui: { k: 'menu', bar: ['File', 'Edit', 'View', 'Insert', 'Format'], path: ['Insert', 'Image', 'Upload from computer'] } },
      { t: 'Word: insert the picture', d: `Choose ${P('Insert', 'Pictures', 'This Device')} on Windows, or ${P('Insert', 'Pictures', 'Picture from File')} on a Mac, and pick the SVG.`, ui: { k: 'menu', bar: ['File', 'Home', 'Insert', 'Layout', 'View'], path: ['Insert', 'Pictures', 'This Device'] } },
      { t: 'Keep it in line with the text', d: `In Docs, click the icon and pick ${UI('In line')} in the bar under it. In Word, click ${UI('Layout Options')} and choose ${UI('In Line with Text')}.`, ui: { k: 'inline', icon: 'check-circle' } },
      { t: 'Make it text-sized', d: 'Drag a corner until the icon is about as tall as a capital letter. Around 0.45 cm (0.18 in) suits 11 pt text.', ui: { k: 'resize', icon: 'check-circle' } },
    ],
    recolor: `Word (SVG): select the icon and use ${P('Graphics Format', 'Graphics Fill')}. Google Docs (PNG): ${P('Image options', 'Recolor')} gives a few tints, but it’s easier to choose the colour on with icons before downloading.`,
    resize: `Drag a corner handle. For exact sizes: Docs ${P('Image options', 'Size & Rotation')}; Word ${UI('Graphics Format')} tab, Height and Width.`,
    trouble: [
      ['The icon jumps around when I type.', 'Set it to In line (Docs) or In Line with Text (Word). Then it moves with your words.'],
      ['The icon sits too high or low next to text.', 'Make it a bit smaller, about the height of a capital letter.'],
      ['Google Docs won’t take my SVG.', 'Docs doesn’t support SVG. Download the PNG instead.'],
    ],
    related: ['notion', 'google-slides', 'powerpoint'],
  },
  {
    slug: 'notion', app: 'Notion', group: 'docs', color: 'sketch', icon: 'sticky-note', time: 1,
    title: 'How to use custom icons in Notion',
    desc: 'Use free icons as Notion page icons, callout icons and inline images. Which size to download, how to upload it and how to make it look good in dark mode.',
    short: `Hover over the page title, click ${UI('Add icon')}, open the ${UI('Upload')} tab and choose a <b>PNG at 256 px</b>.`,
    format: { best: 'PNG', size: '256 px', why: 'Notion page and callout icons are small squares. A 256 px transparent PNG looks crisp on every screen. For images inside the page, 512 px is plenty.' },
    app_ui: 'notion',
    steps: [
      pickStep('PNG', '256 px', 'rocket', 'Tip: a mid-tone colour (like our cobalt or tomato) looks good in both light and dark mode.'),
      { t: 'Open the icon menu', d: `Hover over your page title and click ${UI('Add icon')}. If the page already has an icon, click that icon instead.`, ui: { k: 'side', tab: 'Add icon', button: 'Upload', notion: true } },
      { t: 'Upload your PNG', d: `Switch to the ${UI('Upload')} tab and choose the file. It becomes the page icon, in the sidebar too.`, ui: { k: 'notion-icon', icon: 'rocket' } },
      { t: 'Callouts work the same way', d: 'Click the icon at the start of any callout block, choose Upload, and pick your PNG.', ui: { k: 'callout', icon: 'lightbulb' } },
      { t: 'Inside the page', d: `Type ${K('/')}image, press ${K('Enter')}, choose ${UI('Upload')} and pick the file. Drag the side handles to resize it.`, ui: { k: 'place', icon: 'rocket' } },
    ],
    recolor: 'Notion can’t change an image’s colour. Download the icon again in a new colour. For pages people view in dark mode, pick a mid-tone colour rather than black.',
    resize: 'Page icons are sized by Notion. For images inside the page, drag the handles on the left or right side.',
    trouble: [
      ['My icon disappears in dark mode.', 'Black icons vanish on dark backgrounds. Re-download it in a mid-tone or light colour.'],
      ['It looks blurry as a page icon.', 'Upload a bigger PNG (256 or 512 px).'],
      ['Can I use SVG?', 'Stick to PNG in Notion. It works everywhere in Notion, every time.'],
    ],
    related: ['word-google-docs', 'email-signatures', 'canva'],
  },
  {
    slug: 'wordpress', app: 'WordPress', group: 'web', color: 'line', icon: 'globe', time: 3,
    title: 'How to add icons to WordPress',
    desc: 'Add free icons to a WordPress site with the block editor: as an image, or as crisp SVG code you can recolour. Plus why WordPress blocks SVG uploads.',
    short: `Easiest: add an ${UI('Image')} block and upload a <b>PNG</b>. Sharpest: add a ${UI('Custom HTML')} block and paste the SVG code.`,
    format: { best: 'PNG or SVG code', size: '128 px PNG', why: 'WordPress blocks SVG file uploads by default for safety, so upload a PNG, or paste the SVG as code in a Custom HTML block. Pasted SVG stays sharp and takes any colour.' },
    app_ui: 'web',
    steps: [
      pickStep('PNG', '128 px', 'shield-check', 'Want it razor sharp? Click Copy SVG instead and use step 4.'),
      { t: 'Add an Image block', d: `In the block editor, click the ${UI('+')} (Block Inserter), choose ${UI('Image')}, then ${UI('Upload')} and pick the PNG.`, ui: { k: 'side', tab: '+', button: 'Image', wp: true } },
      { t: 'Set its size', d: `In the block settings on the right, set the width (for example 64 px). Use the alignment buttons to centre it.`, ui: { k: 'resize', icon: 'shield-check' } },
      { t: 'Sharper option: paste SVG code', d: `Add a ${UI('Custom HTML')} block and paste the SVG you copied. Change <code>width</code> and <code>height</code> in the code to resize it, and add <code>style="color:#2F5BFF"</code> to colour it.`, ui: { k: 'code', icon: 'shield-check', lines: ['<svg width="48" height="48"', '  style="color:#2F5BFF" …>', '  …', '</svg>'] } },
      { t: 'Preview and publish', d: `Click ${UI('Preview')} to check it, then ${UI('Update')} or ${UI('Publish')}.`, ui: { k: 'done', icon: 'shield-check' } },
    ],
    recolor: 'PNG: download it again in the colour you want. SVG code: add <code>style="color:#yourcolour"</code> to the <code>&lt;svg&gt;</code> tag. The icon follows that colour because it uses “currentColor”.',
    resize: 'Image block: set the width in the block settings. SVG code: change the <code>width</code> and <code>height</code> numbers (keep them the same).',
    trouble: [
      ['“Sorry, you are not allowed to upload this file type.”', 'That’s WordPress blocking SVG uploads. Upload the PNG, or paste the SVG into a Custom HTML block.'],
      ['I don’t see the Custom HTML block.', 'Your user role may not allow it. Ask the site admin, or use the PNG option.'],
      ['The pasted icon is huge.', 'Set width="32" height="32" (or any size) on the svg tag.'],
    ],
    related: ['html', 'webflow', 'wix-squarespace'],
  },
  {
    slug: 'webflow', app: 'Webflow', group: 'web', color: 'duo', icon: 'layers', time: 3,
    title: 'How to add icons to Webflow',
    desc: 'Add free icons to Webflow as SVG assets or as a Code Embed that follows your text colour, including hover colours. Simple steps with pictures.',
    short: `Upload the <b>SVG</b> in the ${UI('Assets')} panel, or paste the SVG code into a ${UI('Code Embed')} element so it follows your text colour.`,
    format: { best: 'SVG', size: 'any size', why: 'Webflow accepts SVG assets. Pasting the SVG into a Code Embed goes one better: the icon takes the text colour of its parent, so hover colours just work.' },
    app_ui: 'web',
    steps: [
      pickStep('SVG', '', 'zap', 'Or click Copy SVG if you’ll use the Code Embed method.'),
      { t: 'Simple: upload as an asset', d: `Open the ${UI('Assets')} panel, upload the SVG, and drag it onto the page. It becomes an Image element.`, ui: { k: 'side', tab: 'Assets', button: 'Upload' } },
      { t: 'Smarter: use a Code Embed', d: `From the ${UI('Add')} panel, drag a ${UI('Code Embed')} element onto the page and paste the SVG code.`, ui: { k: 'code', icon: 'zap', lines: ['<svg width="1em" height="1em"', '  viewBox="0 0 24 24" …>', '  …', '</svg>'] } },
      { t: 'Colour it with Typography', d: `Because our icons use “currentColor”, a Code Embed icon takes the ${UI('Color')} from the ${UI('Typography')} section in the Style panel. Set a hover state and it changes on hover.`, ui: { k: 'recolor', icon: 'zap', label: 'Typography › Color' } },
      { t: 'Size it with the font size', d: 'Set width="1em" height="1em" in the code, then the icon grows and shrinks with the font size. Perfect next to button text.', ui: { k: 'resize', icon: 'zap' } },
    ],
    recolor: 'Image element: download the SVG again in a new colour. Code Embed: change the text colour of the embed (or its parent) in the Style panel, including hover states.',
    resize: 'Image element: set width in the Style panel. Code Embed: use width="1em" height="1em" and control it with font size.',
    trouble: [
      ['My Code Embed icon is black.', 'Set a text colour on the embed or its parent. The icon uses currentColor.'],
      ['The icon doesn’t show in the Designer.', 'Some embeds only render in preview or on the published site. Check with Preview.'],
      ['It’s the wrong size.', 'Check the width and height in the SVG code; set both to the same value.'],
    ],
    related: ['framer', 'html', 'figma'],
  },
  {
    slug: 'framer', app: 'Framer', group: 'web', color: 'solid', icon: 'wand', time: 1,
    title: 'How to add icons to Framer',
    desc: 'Paste free SVG icons straight onto your Framer canvas, recolour and resize them. Quick, illustrated steps.',
    short: `Click ${UI('Copy SVG')} on any icon and paste it onto your Framer canvas with ${K('Ctrl', 'V')} / ${K('⌘', 'V')}.`,
    format: { best: 'SVG', size: 'copy & paste', why: 'Framer turns pasted SVG into a graphic layer that stays sharp at every size. You can also drag an .svg file onto the canvas.' },
    app_ui: 'design',
    steps: [
      { t: 'Copy the icon', d: `Open <a href="../icons.html">the library</a>, click an icon, choose a colour and press ${UI('Copy SVG')}.`, ui: { k: 'pick', fmt: 'Copy SVG', icon: 'send' } },
      { t: 'Paste it into Framer', d: `Select the frame or section you want and press ${K('Ctrl', 'V')} (${K('⌘', 'V')} on Mac).`, ui: { k: 'paste', icon: 'send' } },
      { t: 'Change the colour', d: 'Select the icon and look for its colour in the right panel. If you can’t change it there, copy the icon again in the colour you want.', ui: { k: 'recolor', icon: 'send', label: 'Fill' } },
      { t: 'Resize and publish', d: 'Drag a corner or type a width and height in the right panel. It stays sharp on every screen.', ui: { k: 'resize', icon: 'send' } },
    ],
    recolor: 'Pick the colour in the library before you copy, or change it in Framer’s right panel when the option is there.',
    resize: 'Drag a corner, or set width and height in the right panel. Keep them equal so the icon isn’t squashed.',
    trouble: [
      ['Nothing happens when I paste.', 'Make sure you clicked Copy SVG (not Download), and that the Framer canvas is focused.'],
      ['The icon looks squashed.', 'Set the same value for width and height.'],
    ],
    related: ['webflow', 'figma', 'html'],
  },
  {
    slug: 'wix-squarespace', app: 'Wix & Squarespace', group: 'web', color: 'gloss', icon: 'store', time: 3,
    title: 'How to add icons to Wix and Squarespace',
    desc: 'Add free icons to a Wix or Squarespace website: which file to download, how to upload it, resize it and keep it sharp. Plain-English steps.',
    short: 'Wix: upload the <b>SVG</b> as an image or vector. Squarespace: add an Image block and upload a <b>PNG at 256 px</b>.',
    format: { best: 'SVG / PNG', size: '256 px PNG', why: 'Wix accepts SVG uploads, which stay sharp. Squarespace image blocks want PNG or JPG, so use a see-through 256 px PNG there.' },
    app_ui: 'web',
    steps: [
      pickStep('PNG', '256 px', 'shopping-bag', 'On Wix, download the SVG instead.'),
      { t: 'Wix: add it from your computer', d: `In the Wix Editor, click ${UI('Add Elements')} (the ${UI('+')}), choose an image or vector art option, and upload your file. The exact wording depends on your editor version.`, ui: { k: 'side', tab: '+', button: 'Upload' } },
      { t: 'Squarespace: add an Image block', d: `Edit your page, click an ${UI('Add Block')} point, choose ${UI('Image')}, then upload the PNG.`, ui: { k: 'side', tab: 'Add Block', button: 'Image' } },
      { t: 'Resize it', d: 'Drag the block’s corner or edges to resize. Keep icons small and consistent, for example the same size on every feature card.', ui: { k: 'resize', icon: 'shopping-bag' } },
      { t: 'Save and publish', d: 'Save, preview on mobile, then publish.', ui: { k: 'done', icon: 'shopping-bag' } },
    ],
    recolor: 'Pick the colour on with icons before downloading. Wix can often change the colours of uploaded SVG vector art in its design settings.',
    resize: 'Drag a corner. For a row of icons, set them all to the same size so they line up.',
    trouble: [
      ['Squarespace won’t take my SVG.', 'Use the PNG version in Image blocks.'],
      ['The icon looks blurry on phones.', 'Upload a bigger PNG (512 px). Phones have sharp screens.'],
      ['Icons are different sizes on each card.', 'Set every icon to the same width in its block settings.'],
    ],
    related: ['wordpress', 'webflow', 'html'],
  },
  {
    slug: 'email-signatures', app: 'Email signatures', group: 'email', color: 'blueprint', icon: 'mail', time: 3,
    title: 'How to add icons to your email signature',
    desc: 'Add small icons (phone, email, website, social) to your Gmail, Outlook or Apple Mail signature. Which PNG size to use and how to keep them looking sharp.',
    short: 'Use small <b>PNG</b> files (64 px), shown at about 16–20 px. Email apps don’t support SVG.',
    format: { best: 'PNG', size: '64 px', why: 'Most email apps can’t show SVG, so use PNG. Download 64 px and show it at 16–20 px: the extra pixels keep it crisp on sharp screens.' },
    app_ui: 'mail',
    steps: [
      pickStep('PNG', '64 px', 'phone', 'Grab a set, for example phone, mail, globe and map-pin, all in one colour.'),
      { t: 'Gmail: open your signature', d: `Click the gear icon, then ${UI('See all settings')}. On the ${UI('General')} tab, scroll to ${UI('Signature')} and click ${UI('Create new')} or edit yours.`, ui: { k: 'menu', bar: ['Settings', 'General', 'Labels', 'Inbox'], path: ['General', 'Signature', 'Create new'] } },
      { t: 'Insert the icon image', d: `Use the image button in the signature toolbar. Gmail asks for the image from Google Drive or a web address, so upload the PNGs there first (make sure they’re shared so others can see them).`, ui: { k: 'mailsig', icon: 'phone' } },
      { t: 'Outlook and Apple Mail', d: `New Outlook: ${P('Settings', 'Account', 'Signatures')}, then use the image button. Apple Mail: ${P('Mail', 'Settings', 'Signatures')}, then drag the PNG into the signature.`, ui: { k: 'menu', bar: ['Mail', 'File', 'Edit', 'View'], path: ['Mail', 'Settings', 'Signatures'] } },
      { t: 'Shrink it to text size', d: 'Click the icon and make it small. In Gmail choose Small; in other apps drag the corner to about 16–20 px.', ui: { k: 'resize', icon: 'phone' } },
    ],
    recolor: 'Email apps can’t recolour images. Download the icons in your brand colour, or a mid grey that works on light and dark backgrounds.',
    resize: 'Aim for 16–20 px on screen. Download at 64 px so they stay sharp on high-resolution screens.',
    trouble: [
      ['People see my icons as attachments.', 'Some email apps attach pasted images. Inserting the images from a web address (or Google Drive) avoids that.'],
      ['Icons don’t show for some people.', 'Their email app may block images until they click “show images”. Always keep your text details next to the icons.'],
      ['The icons are huge in Gmail.', 'Click each icon in the signature editor and choose Small.'],
    ],
    related: ['notion', 'word-google-docs', 'canva'],
  },
  {
    slug: 'html', app: 'Plain HTML website', group: 'web', color: 'sketch', icon: 'code', time: 2,
    title: 'How to add icons to an HTML website',
    desc: 'Add free icons to any website: paste inline SVG, use the zero-JavaScript icon classes, or link an image. Recolour with CSS color and resize with font-size.',
    short: `Paste the icon’s SVG code into your HTML, or add one stylesheet and write <code>&lt;i class="with with-home"&gt;&lt;/i&gt;</code>.`,
    format: { best: 'SVG', size: 'any size', why: 'Inline SVG is the sharpest, smallest and easiest to colour: it follows your CSS text colour. Icon classes do the same with one line of HTML per icon.' },
    app_ui: 'web',
    steps: [
      { t: 'Copy the SVG', d: `Open <a href="../icons.html">the library</a>, click an icon and press ${UI('Copy SVG')}.`, ui: { k: 'pick', fmt: 'Copy SVG', icon: 'home' } },
      { t: 'Paste it into your HTML', d: 'Paste the code where you want the icon. It’s plain HTML: no files to upload, nothing to install.', ui: { k: 'code', icon: 'home', lines: ['<a href="/">', '  <svg width="20" height="20" …>…</svg>', '  Home', '</a>'] } },
      { t: 'Or use icon classes', d: 'Add the stylesheet once in your <code>&lt;head&gt;</code>, then write one tag per icon. No JavaScript needed.', ui: { k: 'code', icon: 'home', lines: ['<link rel="stylesheet" href=".../with-line.css">', '', '<i class="with with-home"></i>', '<i class="with with-home with-solid"></i>'] } },
      { t: 'Colour it with CSS', d: 'Icons use <code>currentColor</code>, so they take the text colour: <code>color: #FF5A36</code>. Hover colours work too.', ui: { k: 'recolor', icon: 'home', label: 'color:' } },
      { t: 'Size it with CSS', d: 'Icon classes are <code>1em</code> square, so <code>font-size: 32px</code> makes a 32 px icon. For inline SVG, change <code>width</code> and <code>height</code>.', ui: { k: 'resize', icon: 'home' } },
    ],
    recolor: 'Set <code>color</code> on the icon or any parent: <code>.nav a { color: #2F5BFF }</code>. Duo icons also read <code>--with-duo</code> for their soft fill.',
    resize: 'Inline SVG: change width and height. Icon classes: change font-size, or add <code>with-2x</code> … <code>with-5x</code>.',
    trouble: [
      ['The icon is black and won’t change colour.', 'You used an <code>&lt;img&gt;</code> tag. Images can’t inherit CSS colour; paste the SVG inline or use icon classes.'],
      ['Icon classes show nothing.', 'Check the stylesheet link is in your <code>&lt;head&gt;</code> and the class names are right: <code>with with-home</code>.'],
      ['Screen readers read nothing.', 'Decorative icons should stay silent. If the icon is the only content of a button, add <code>aria-label</code> to the button.'],
    ],
    related: ['wordpress', 'webflow', 'framer'],
    code: true,
  },
]

export const GROUPS = [['all', 'All'], ['slides', 'Slides'], ['docs', 'Docs & notes'], ['design', 'Design tools'], ['web', 'Websites'], ['email', 'Email']]
